export const priorityBuilderCopy = {
  contactsSavedView: "Kontakty / uložené zobrazenie",
  evaluationOrder: "Poradie vyhodnotenia",
  evaluationHint: "Vyhráva prvý zodpovedajúci segment. Nezhodné oprávnené kontakty nasledujú raz.",
  eligibleContacts: "oprávnených kontaktov",
  personalView: "Osobné zobrazenie",
  savedViews: "Uložené zobrazenia",
  liveResult: "Živý výsledok",
  workNext: "Čo bude spracované ako ďalšie",
  dedupActive: "Deduplikácia je aktívna.",
  dedupDetail: "kontaktov zodpovedá viacerým pravidlám a zobrazí sa iba v najvyššom segmente.",
  whyThisOrder: "Prečo toto poradie?",
  whyOne: "sa vyhodnocuje pred",
  whyMany: "sa vyhodnocuje ako prvý, preto sa zodpovedajúce kontakty dostanú na začiatok frontu.",
  reset: "Obnoviť",
  fieldAll: "Pole: všetky",
  fieldName: "Meno",
  fieldPhone: "Telefón",
  fieldEmail: "E-mail",
  fieldCity: "Mesto",
  moreActions: "Ďalšie akcie segmentu",
  removeSegment: "Odstrániť segment",
  renameView: "Premenovať zobrazenie",
  auto: "Auto",
  autoOn: "zap.",
  autoOff: "vyp.",
  nextContact: "Ďalší kontakt",
  queueSyncHint: "Pred použitím Auto alebo Ďalší kontakt uložte zmeny.",
  dragHint: "Na úpravu priority použite šípky. Deduplikácia prebieha zhora nadol.",
  close: "Zavrieť",
  queuePosition: "Pozícia vo fronte",
  nextUp: "Ďalší na rade",
  group: "Skupina",
  referralsFirst: "Odporúčané kontakty ako prvé",
  referralBadge: "Odporúčanie",
  scheduledCallback: "Naplánovaný spätný hovor",
  notScheduled: "Nenaplánované",
  callAttempts: "Pokusy o hovor v tejto misii",
  noAttempts: "Bez pokusov",
  unknownAttempts: "Neznáme",
  otherGroup: "Ostatné oprávnené kontakty",
  groupByCity: "Zoskupiť podľa mesta",
  groupByCityHint: "Pred uložením zobrazenia zoradí oprávnené mestá AI.",
  cityRankingPending: "Zoraďujú sa mestá…",
  cityRankingReady: "Poradie miest AI je pripravené",
  cityRankingRetry: "Zopakovať poradie",
  cityRankingRefresh: "Obnoviť poradie",
  cityRankingEstimated: "Odhadované poradie",
  cityRankingLocations: "lokalít",
  unknownCity: "Neznáma lokalita",
  cityCountrySeparator: ", ",
  newReferrals: "Nové odporúčania",
  allCities: "Všetky mestá",
  onlySelectedCities: "Iba vybrané mestá",
  citySelectionHint: "Vyberte oprávnené mestá, ktoré zostanú v tomto zobrazení.",
  noSelectedCities: "Nie sú vybrané žiadne mestá.",
  noResults: "Nenašli sa žiadne kontakty.",
  save: "Uložiť",
  duplicate: "Duplikovať",
  delete: "Odstrániť",
  saved: "Uložené",
  unsaved: "Neuložené",
  groupLabels: {
    referral: "Nové odporúčania",
    scheduled_today: "Naplánované dnes",
    due: "Splatné teraz / po termíne",
    new: "Nové kontakty",
    my_scheduled: "Moje naplánované",
    team_scheduled: "Tímové naplánované",
    assigned_others: "Priradené iným",
    unhandled: "Nespracované / zmeškané",
    never_called: "Nikdy nevolané",
    recently_contacted: "Nedávno kontaktované",
    stale: "Neaktuálne kontakty",
  } as Record<string, string>,
  sortLabels: {
    priority: "Priorita",
    name_asc: "A–Ž",
    name_desc: "Ž–A",
    attempts_desc: "Pokusy od najvyšších",
    attempts_asc: "Pokusy od najnižších",
    last_contact_asc: "Najstarší kontakt",
    last_contact_desc: "Najnovší kontakt",
    callback_asc: "Najskorší hovor",
    callback_desc: "Najneskorší hovor",
    created_desc: "Najnovšie vytvorené",
    created_asc: "Najstaršie vytvorené",
  } as Record<string, string>,
  presetLabels: {
    referral_cities: "Odporúčania + mestá",
    referral_first: "Nové odporúčania",
    todays_callbacks: "Dnešné spätné hovory",
    fresh_opportunities: "Nové príležitosti",
    recovery_desk: "Obnova kontaktov",
  } as Record<string, string>,
};