import {
  BookOpen,
  Brain,
  Briefcase,
  Cigarette,
  Clock,
  Coffee,
  Droplets,
  Dumbbell,
  GraduationCap,
  Headphones,
  Heart,
  MessageSquare,
  Moon,
  Music,
  Pause,
  Phone,
  Shield,
  Star,
  Stethoscope,
  Sun,
  Timer,
  Users,
  Utensils,
  Zap,
} from "lucide-react";

export const AGENT_BREAK_ICON_OPTIONS = [
  { name: "Coffee", icon: Coffee },
  { name: "Utensils", icon: Utensils },
  { name: "Clock", icon: Clock },
  { name: "Timer", icon: Timer },
  { name: "BookOpen", icon: BookOpen },
  { name: "Briefcase", icon: Briefcase },
  { name: "Heart", icon: Heart },
  { name: "Phone", icon: Phone },
  { name: "MessageSquare", icon: MessageSquare },
  { name: "Pause", icon: Pause },
  { name: "Moon", icon: Moon },
  { name: "Sun", icon: Sun },
  { name: "Zap", icon: Zap },
  { name: "Shield", icon: Shield },
  { name: "Star", icon: Star },
  { name: "Music", icon: Music },
  { name: "Headphones", icon: Headphones },
  { name: "Dumbbell", icon: Dumbbell },
  { name: "Cigarette", icon: Cigarette },
  { name: "Droplets", icon: Droplets },
  { name: "Brain", icon: Brain },
  { name: "Stethoscope", icon: Stethoscope },
  { name: "GraduationCap", icon: GraduationCap },
  { name: "Users", icon: Users },
] as const;

export function getAgentBreakIcon(iconName?: string | null) {
  return AGENT_BREAK_ICON_OPTIONS.find((item) => item.name === iconName)?.icon || Coffee;
}