export const REGIONS_BY_COUNTRY: Record<string, string[]> = {
  SK: [
    "Bratislavský kraj",
    "Trnavský kraj",
    "Trenčiansky kraj",
    "Nitriansky kraj",
    "Žilinský kraj",
    "Banskobystrický kraj",
    "Prešovský kraj",
    "Košický kraj",
  ],
  CZ: [
    "Hlavní město Praha",
    "Středočeský kraj",
    "Jihočeský kraj",
    "Plzeňský kraj",
    "Karlovarský kraj",
    "Ústecký kraj",
    "Liberecký kraj",
    "Královéhradecký kraj",
    "Pardubický kraj",
    "Kraj Vysočina",
    "Jihomoravský kraj",
    "Olomoucký kraj",
    "Moravskoslezský kraj",
    "Zlínský kraj",
  ],
  HU: [
    "Budapest",
    "Baranya megye",
    "Bács-Kiskun megye",
    "Békés megye",
    "Borsod-Abaúj-Zemplén megye",
    "Csongrád-Csanád megye",
    "Fejér megye",
    "Győr-Moson-Sopron megye",
    "Hajdú-Bihar megye",
    "Heves megye",
    "Jász-Nagykun-Szolnok megye",
    "Komárom-Esztergom megye",
    "Nógrád megye",
    "Pest megye",
    "Somogy megye",
    "Szabolcs-Szatmár-Bereg megye",
    "Tolna megye",
    "Vas megye",
    "Veszprém megye",
    "Zala megye",
  ],
  RO: [
    "București",
    "Alba",
    "Arad",
    "Argeș",
    "Bacău",
    "Bihor",
    "Bistrița-Năsăud",
    "Botoșani",
    "Brașov",
    "Brăila",
    "Buzău",
    "Caraș-Severin",
    "Călărași",
    "Cluj",
    "Constanța",
    "Covasna",
    "Dâmbovița",
    "Dolj",
    "Galați",
    "Giurgiu",
    "Gorj",
    "Harghita",
    "Hunedoara",
    "Ialomița",
    "Iași",
    "Ilfov",
    "Maramureș",
    "Mehedinți",
    "Mureș",
    "Neamț",
    "Olt",
    "Prahova",
    "Satu Mare",
    "Sălaj",
    "Sibiu",
    "Suceava",
    "Teleorman",
    "Timiș",
    "Tulcea",
    "Vaslui",
    "Vâlcea",
    "Vrancea",
  ],
  IT: [
    "Abruzzo",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Friuli Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardia",
    "Marche",
    "Molise",
    "Piemonte",
    "Puglia",
    "Sardegna",
    "Sicilia",
    "Toscana",
    "Trentino-Alto Adige",
    "Umbria",
    "Valle d'Aosta",
    "Veneto",
  ],
  AT: [
    "Burgenland",
    "Kärnten",
    "Niederösterreich",
    "Oberösterreich",
    "Salzburg",
    "Steiermark",
    "Tirol",
    "Vorarlberg",
    "Wien",
  ],
  DE: [
    "Baden-Württemberg",
    "Bayern",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hessen",
    "Mecklenburg-Vorpommern",
    "Niedersachsen",
    "Nordrhein-Westfalen",
    "Rheinland-Pfalz",
    "Saarland",
    "Sachsen",
    "Sachsen-Anhalt",
    "Schleswig-Holstein",
    "Thüringen",
  ],
  US: [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
    "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky",
    "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi",
    "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico",
    "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania",
    "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont",
    "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming", "District of Columbia",
  ],
};

export const REGION_MAP: Record<string, Record<string, string>> = {
  SK: {
    "Bratislava": "Bratislavský kraj", "Pezinok": "Bratislavský kraj", "Senec": "Bratislavský kraj", "Malacky": "Bratislavský kraj",
    "Trnava": "Trnavský kraj", "Piešťany": "Trnavský kraj", "Dunajská Streda": "Trnavský kraj", "Galanta": "Trnavský kraj", "Hlohovec": "Trnavský kraj", "Senica": "Trnavský kraj", "Skalica": "Trnavský kraj",
    "Trenčín": "Trenčiansky kraj", "Považská Bystrica": "Trenčiansky kraj", "Púchov": "Trenčiansky kraj", "Prievidza": "Trenčiansky kraj", "Nové Mesto nad Váhom": "Trenčiansky kraj", "Partizánske": "Trenčiansky kraj", "Bánovce nad Bebravou": "Trenčiansky kraj", "Ilava": "Trenčiansky kraj", "Myjava": "Trenčiansky kraj",
    "Nitra": "Nitriansky kraj", "Komárno": "Nitriansky kraj", "Levice": "Nitriansky kraj", "Nové Zámky": "Nitriansky kraj", "Šaľa": "Nitriansky kraj", "Topoľčany": "Nitriansky kraj", "Zlaté Moravce": "Nitriansky kraj",
    "Žilina": "Žilinský kraj", "Martin": "Žilinský kraj", "Čadca": "Žilinský kraj", "Dolný Kubín": "Žilinský kraj", "Liptovský Mikuláš": "Žilinský kraj", "Námestovo": "Žilinský kraj", "Ružomberok": "Žilinský kraj", "Tvrdošín": "Žilinský kraj", "Turčianske Teplice": "Žilinský kraj", "Bytča": "Žilinský kraj", "Kysucké Nové Mesto": "Žilinský kraj",
    "Banská Bystrica": "Banskobystrický kraj", "Zvolen": "Banskobystrický kraj", "Lučenec": "Banskobystrický kraj", "Rimavská Sobota": "Banskobystrický kraj", "Žiar nad Hronom": "Banskobystrický kraj", "Brezno": "Banskobystrický kraj", "Detva": "Banskobystrický kraj", "Krupina": "Banskobystrický kraj", "Revúca": "Banskobystrický kraj", "Veľký Krtíš": "Banskobystrický kraj", "Banská Štiavnica": "Banskobystrický kraj", "Poltár": "Banskobystrický kraj",
    "Prešov": "Prešovský kraj", "Poprad": "Prešovský kraj", "Bardejov": "Prešovský kraj", "Humenné": "Prešovský kraj", "Kežmarok": "Prešovský kraj", "Levoča": "Prešovský kraj", "Medzilaborce": "Prešovský kraj", "Sabinov": "Prešovský kraj", "Snina": "Prešovský kraj", "Stará Ľubovňa": "Prešovský kraj", "Stropkov": "Prešovský kraj", "Svidník": "Prešovský kraj", "Vranov nad Topľou": "Prešovský kraj", "Svit": "Prešovský kraj", "Vysoké Tatry": "Prešovský kraj", "Starý Smokovec": "Prešovský kraj",
    "Košice": "Košický kraj", "Michalovce": "Košický kraj", "Spišská Nová Ves": "Košický kraj", "Trebišov": "Košický kraj", "Rožňava": "Košický kraj", "Gelnica": "Košický kraj", "Sobrance": "Košický kraj", "Moldava nad Bodvou": "Košický kraj",
  },
  CZ: {
    "Praha": "Hlavní město Praha", "Brno": "Jihomoravský kraj", "Ostrava": "Moravskoslezský kraj", "Plzeň": "Plzeňský kraj",
    "Liberec": "Liberecký kraj", "Olomouc": "Olomoucký kraj", "České Budějovice": "Jihočeský kraj", "Hradec Králové": "Královéhradecký kraj",
    "Ústí nad Labem": "Ústecký kraj", "Pardubice": "Pardubický kraj", "Zlín": "Zlínský kraj", "Jihlava": "Kraj Vysočina",
    "Karlovy Vary": "Karlovarský kraj", "Kladno": "Středočeský kraj",
  },
  HU: {
    "Budapest": "Budapest", "Debrecen": "Hajdú-Bihar megye", "Szeged": "Csongrád-Csanád megye", "Miskolc": "Borsod-Abaúj-Zemplén megye",
    "Pécs": "Baranya megye", "Győr": "Győr-Moson-Sopron megye", "Nyíregyháza": "Szabolcs-Szatmár-Bereg megye",
    "Kecskemét": "Bács-Kiskun megye", "Székesfehérvár": "Fejér megye", "Szombathely": "Vas megye", "Szolnok": "Jász-Nagykun-Szolnok megye",
    "Eger": "Heves megye", "Tatabánya": "Komárom-Esztergom megye", "Veszprém": "Veszprém megye", "Kaposvár": "Somogy megye",
    "Zalaegerszeg": "Zala megye", "Salgótarján": "Nógrád megye", "Szekszárd": "Tolna megye", "Békéscsaba": "Békés megye",
  },
  RO: {
    "București": "București", "Cluj-Napoca": "Cluj", "Timișoara": "Timiș", "Iași": "Iași", "Constanța": "Constanța",
    "Craiova": "Dolj", "Brașov": "Brașov", "Galați": "Galați", "Ploiești": "Prahova", "Oradea": "Bihor",
    "Brăila": "Brăila", "Arad": "Arad", "Pitești": "Argeș", "Sibiu": "Sibiu", "Bacău": "Bacău",
    "Târgu Mureș": "Mureș", "Baia Mare": "Maramureș", "Buzău": "Buzău", "Botoșani": "Botoșani", "Satu Mare": "Satu Mare",
    "Suceava": "Suceava", "Alba Iulia": "Alba", "Deva": "Hunedoara", "Bistrița": "Bistrița-Năsăud",
  },
  IT: {
    "Roma": "Lazio", "Milano": "Lombardia", "Napoli": "Campania", "Torino": "Piemonte", "Palermo": "Sicilia",
    "Genova": "Liguria", "Bologna": "Emilia-Romagna", "Firenze": "Toscana", "Bari": "Puglia", "Catania": "Sicilia",
    "Venezia": "Veneto", "Verona": "Veneto", "Messina": "Sicilia", "Padova": "Veneto", "Trieste": "Friuli Venezia Giulia",
    "Brescia": "Lombardia", "Parma": "Emilia-Romagna", "Taranto": "Puglia", "Modena": "Emilia-Romagna", "Reggio Calabria": "Calabria",
    "Perugia": "Umbria", "Cagliari": "Sardegna", "Ancona": "Marche", "L'Aquila": "Abruzzo", "Campobasso": "Molise",
    "Potenza": "Basilicata", "Trento": "Trentino-Alto Adige", "Aosta": "Valle d'Aosta",
  },
  AT: {
    "Wien": "Wien", "Graz": "Steiermark", "Linz": "Oberösterreich", "Salzburg": "Salzburg", "Innsbruck": "Tirol",
    "Klagenfurt": "Kärnten", "Villach": "Kärnten", "Wels": "Oberösterreich", "St. Pölten": "Niederösterreich",
    "Dornbirn": "Vorarlberg", "Wiener Neustadt": "Niederösterreich", "Steyr": "Oberösterreich", "Feldkirch": "Vorarlberg",
    "Bregenz": "Vorarlberg", "Leonding": "Oberösterreich", "Klosterneuburg": "Niederösterreich", "Baden": "Niederösterreich",
    "Leoben": "Steiermark", "Krems an der Donau": "Niederösterreich", "Traun": "Oberösterreich",
    "Amstetten": "Niederösterreich", "Lustenau": "Vorarlberg", "Kapfenberg": "Steiermark", "Mödling": "Niederösterreich",
    "Hallein": "Salzburg", "Kufstein": "Tirol", "Braunau am Inn": "Oberösterreich", "Schwechat": "Niederösterreich",
    "Stockerau": "Niederösterreich", "Saalfelden": "Salzburg", "Ansfelden": "Oberösterreich", "Tulln": "Niederösterreich",
    "Hohenems": "Vorarlberg", "Spittal an der Drau": "Kärnten", "Telfs": "Tirol", "Ternitz": "Niederösterreich",
    "Perchtoldsdorf": "Niederösterreich", "Eisenstadt": "Burgenland", "Feldkirchen": "Kärnten", "Bludenz": "Vorarlberg",
    "Bad Ischl": "Oberösterreich", "Wolfsberg": "Kärnten", "Korneuburg": "Niederösterreich", "Neunkirchen": "Niederösterreich",
    "Hard": "Vorarlberg", "Vöcklabruck": "Oberösterreich", "Lienz": "Tirol", "Judenburg": "Steiermark",
    "Hall in Tirol": "Tirol", "Mistelbach": "Niederösterreich", "Ried im Innkreis": "Oberösterreich",
    "Gmunden": "Oberösterreich", "Wörgl": "Tirol", "Oberwart": "Burgenland", "Zwettl": "Niederösterreich",
  },
  DE: {
    "Berlin": "Berlin", "Hamburg": "Hamburg", "München": "Bayern", "Köln": "Nordrhein-Westfalen", "Frankfurt": "Hessen",
    "Stuttgart": "Baden-Württemberg", "Düsseldorf": "Nordrhein-Westfalen", "Leipzig": "Sachsen", "Dortmund": "Nordrhein-Westfalen",
    "Essen": "Nordrhein-Westfalen", "Bremen": "Bremen", "Dresden": "Sachsen", "Hannover": "Niedersachsen",
    "Nürnberg": "Bayern", "Duisburg": "Nordrhein-Westfalen", "Bochum": "Nordrhein-Westfalen", "Wuppertal": "Nordrhein-Westfalen",
    "Bielefeld": "Nordrhein-Westfalen", "Bonn": "Nordrhein-Westfalen", "Münster": "Nordrhein-Westfalen",
    "Mannheim": "Baden-Württemberg", "Karlsruhe": "Baden-Württemberg", "Augsburg": "Bayern", "Wiesbaden": "Hessen",
    "Mainz": "Rheinland-Pfalz", "Kiel": "Schleswig-Holstein", "Magdeburg": "Sachsen-Anhalt", "Erfurt": "Thüringen",
    "Schwerin": "Mecklenburg-Vorpommern", "Potsdam": "Brandenburg", "Saarbrücken": "Saarland",
  },
  US: {
    "New York": "New York", "Los Angeles": "California", "Chicago": "Illinois", "Houston": "Texas",
    "Phoenix": "Arizona", "Philadelphia": "Pennsylvania", "San Antonio": "Texas", "San Diego": "California",
    "Dallas": "Texas", "San Jose": "California", "Austin": "Texas", "Jacksonville": "Florida",
    "Fort Worth": "Texas", "Columbus": "Ohio", "Charlotte": "North Carolina", "Indianapolis": "Indiana",
    "San Francisco": "California", "Seattle": "Washington", "Denver": "Colorado", "Nashville": "Tennessee",
    "Oklahoma City": "Oklahoma", "Washington": "District of Columbia", "El Paso": "Texas", "Boston": "Massachusetts",
    "Portland": "Oregon", "Las Vegas": "Nevada", "Memphis": "Tennessee", "Louisville": "Kentucky",
    "Baltimore": "Maryland", "Milwaukee": "Wisconsin", "Albuquerque": "New Mexico", "Tucson": "Arizona",
    "Fresno": "California", "Sacramento": "California", "Mesa": "Arizona", "Kansas City": "Missouri",
    "Atlanta": "Georgia", "Omaha": "Nebraska", "Colorado Springs": "Colorado", "Raleigh": "North Carolina",
    "Long Beach": "California", "Virginia Beach": "Virginia", "Miami": "Florida", "Oakland": "California",
    "Minneapolis": "Minnesota", "Tampa": "Florida", "Tulsa": "Oklahoma", "Arlington": "Texas",
    "New Orleans": "Louisiana", "Cleveland": "Ohio", "Honolulu": "Hawaii", "Pittsburgh": "Pennsylvania",
    "St. Louis": "Missouri", "Cincinnati": "Ohio", "Detroit": "Michigan",
  },
};

export const DISTRICTS_BY_REGION: Record<string, Record<string, string[]>> = {
  SK: {
    "Bratislavský kraj": ["Bratislava I", "Bratislava II", "Bratislava III", "Bratislava IV", "Bratislava V", "Malacky", "Pezinok", "Senec"],
    "Trnavský kraj": ["Dunajská Streda", "Galanta", "Hlohovec", "Piešťany", "Senica", "Skalica", "Trnava"],
    "Trenčiansky kraj": ["Bánovce nad Bebravou", "Ilava", "Myjava", "Nové Mesto nad Váhom", "Partizánske", "Považská Bystrica", "Prievidza", "Púchov", "Trenčín"],
    "Nitriansky kraj": ["Komárno", "Levice", "Nitra", "Nové Zámky", "Šaľa", "Topoľčany", "Zlaté Moravce"],
    "Žilinský kraj": ["Bytča", "Čadca", "Dolný Kubín", "Kysucké Nové Mesto", "Liptovský Mikuláš", "Martin", "Námestovo", "Ružomberok", "Turčianske Teplice", "Tvrdošín", "Žilina"],
    "Banskobystrický kraj": ["Banská Bystrica", "Banská Štiavnica", "Brezno", "Detva", "Krupina", "Lučenec", "Poltár", "Revúca", "Rimavská Sobota", "Veľký Krtíš", "Zvolen", "Žiar nad Hronom"],
    "Prešovský kraj": ["Bardejov", "Humenné", "Kežmarok", "Levoča", "Medzilaborce", "Poprad", "Prešov", "Sabinov", "Snina", "Stará Ľubovňa", "Stropkov", "Svidník", "Vranov nad Topľou"],
    "Košický kraj": ["Gelnica", "Košice I", "Košice II", "Košice III", "Košice IV", "Košice-okolie", "Michalovce", "Rožňava", "Sobrance", "Spišská Nová Ves", "Trebišov"],
  },
  CZ: {
    "Hlavní město Praha": ["Praha"],
    "Středočeský kraj": ["Benešov", "Beroun", "Kladno", "Kolín", "Kutná Hora", "Mělník", "Mladá Boleslav", "Nymburk", "Praha-východ", "Praha-západ", "Příbram", "Rakovník"],
    "Jihočeský kraj": ["České Budějovice", "Český Krumlov", "Jindřichův Hradec", "Písek", "Prachatice", "Strakonice", "Tábor"],
    "Plzeňský kraj": ["Domažlice", "Klatovy", "Plzeň-město", "Plzeň-jih", "Plzeň-sever", "Rokycany", "Tachov"],
    "Karlovarský kraj": ["Cheb", "Karlovy Vary", "Sokolov"],
    "Ústecký kraj": ["Děčín", "Chomutov", "Litoměřice", "Louny", "Most", "Teplice", "Ústí nad Labem"],
    "Liberecký kraj": ["Česká Lípa", "Jablonec nad Nisou", "Liberec", "Semily"],
    "Královéhradecký kraj": ["Hradec Králové", "Jičín", "Náchod", "Rychnov nad Kněžnou", "Trutnov"],
    "Pardubický kraj": ["Chrudim", "Pardubice", "Svitavy", "Ústí nad Orlicí"],
    "Kraj Vysočina": ["Havlíčkův Brod", "Jihlava", "Pelhřimov", "Třebíč", "Žďár nad Sázavou"],
    "Jihomoravský kraj": ["Blansko", "Brno-město", "Brno-venkov", "Břeclav", "Hodonín", "Vyškov", "Znojmo"],
    "Olomoucký kraj": ["Jeseník", "Olomouc", "Prostějov", "Přerov", "Šumperk"],
    "Moravskoslezský kraj": ["Bruntál", "Frýdek-Místek", "Karviná", "Nový Jičín", "Opava", "Ostrava-město"],
    "Zlínský kraj": ["Kroměříž", "Uherské Hradiště", "Vsetín", "Zlín"],
  },
  HU: {
    "Budapest": ["Budapest"],
    "Baranya megye": ["Pécs", "Komló", "Mohács", "Siklós", "Szigetvár"],
    "Bács-Kiskun megye": ["Kecskemét", "Baja", "Kalocsa", "Kiskunfélegyháza", "Kiskunhalas"],
    "Békés megye": ["Békéscsaba", "Gyula", "Orosháza", "Szarvas"],
    "Borsod-Abaúj-Zemplén megye": ["Miskolc", "Kazincbarcika", "Ózd", "Tiszaújváros", "Sárospatak"],
    "Csongrád-Csanád megye": ["Szeged", "Hódmezővásárhely", "Makó", "Szentes"],
    "Fejér megye": ["Székesfehérvár", "Dunaújváros", "Mór"],
    "Győr-Moson-Sopron megye": ["Győr", "Sopron", "Mosonmagyaróvár", "Csorna"],
    "Hajdú-Bihar megye": ["Debrecen", "Hajdúböszörmény", "Hajdúszoboszló", "Balmazújváros"],
    "Heves megye": ["Eger", "Gyöngyös", "Hatvan"],
    "Jász-Nagykun-Szolnok megye": ["Szolnok", "Jászberény", "Karcag", "Mezőtúr"],
    "Komárom-Esztergom megye": ["Tatabánya", "Esztergom", "Komárom", "Oroszlány"],
    "Nógrád megye": ["Salgótarján", "Balassagyarmat", "Pásztó"],
    "Pest megye": ["Budapest-agglomeráció", "Érd", "Gödöllő", "Szentendre", "Vác", "Cegléd", "Nagykőrös"],
    "Somogy megye": ["Kaposvár", "Siófok", "Marcali"],
    "Szabolcs-Szatmár-Bereg megye": ["Nyíregyháza", "Kisvárda", "Mátészalka", "Fehérgyarmat"],
    "Tolna megye": ["Szekszárd", "Dombóvár", "Paks", "Bonyhád"],
    "Vas megye": ["Szombathely", "Kőszeg", "Sárvár", "Celldömölk"],
    "Veszprém megye": ["Veszprém", "Ajka", "Pápa", "Balatonfüred"],
    "Zala megye": ["Zalaegerszeg", "Nagykanizsa", "Keszthely", "Lenti"],
  },
  RO: {
    "București": ["Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 6"],
    "Alba": ["Alba Iulia", "Aiud", "Blaj", "Sebeș", "Cugir"],
    "Arad": ["Arad", "Ineu", "Lipova", "Pecica", "Chișineu-Criș"],
    "Argeș": ["Pitești", "Câmpulung", "Curtea de Argeș", "Mioveni", "Costești"],
    "Bacău": ["Bacău", "Onești", "Moinești", "Comănești", "Buhuși"],
    "Bihor": ["Oradea", "Salonta", "Beiuș", "Marghita", "Aleșd"],
    "Bistrița-Năsăud": ["Bistrița", "Năsăud", "Beclean", "Sângeorz-Băi"],
    "Botoșani": ["Botoșani", "Dorohoi", "Darabani", "Săveni"],
    "Brașov": ["Brașov", "Făgăraș", "Săcele", "Codlea", "Zărnești", "Râșnov"],
    "Brăila": ["Brăila", "Ianca", "Însurăței", "Făurei"],
    "Buzău": ["Buzău", "Râmnicu Sărat", "Nehoiu", "Pătârlagele"],
    "Caraș-Severin": ["Reșița", "Caransebeș", "Oțelu Roșu", "Moldova Nouă", "Anina"],
    "Călărași": ["Călărași", "Oltenița", "Budești", "Fundulea"],
    "Cluj": ["Cluj-Napoca", "Turda", "Dej", "Câmpia Turzii", "Gherla", "Huedin"],
    "Constanța": ["Constanța", "Mangalia", "Medgidia", "Cernavodă", "Năvodari"],
    "Covasna": ["Sfântu Gheorghe", "Târgu Secuiesc", "Covasna", "Baraolt"],
    "Dâmbovița": ["Târgoviște", "Moreni", "Pucioasa", "Găești", "Titu"],
    "Dolj": ["Craiova", "Băilești", "Calafat", "Filiași", "Segarcea"],
    "Galați": ["Galați", "Tecuci", "Târgu Bujor", "Berești"],
    "Giurgiu": ["Giurgiu", "Bolintin-Vale", "Mihăilești"],
    "Gorj": ["Târgu Jiu", "Motru", "Rovinari", "Bumbești-Jiu", "Novaci", "Țicleni"],
    "Harghita": ["Miercurea Ciuc", "Odorheiu Secuiesc", "Gheorgheni", "Toplița", "Cristuru Secuiesc"],
    "Hunedoara": ["Deva", "Hunedoara", "Petroșani", "Brad", "Orăștie", "Lupeni", "Vulcan"],
    "Ialomița": ["Slobozia", "Fetești", "Urziceni", "Țăndărei"],
    "Iași": ["Iași", "Pașcani", "Hârlău", "Târgu Frumos"],
    "Ilfov": ["Voluntari", "Pantelimon", "Buftea", "Popești-Leordeni", "Chitila", "Măgurele", "Otopeni", "Bragadiru"],
    "Maramureș": ["Baia Mare", "Sighetu Marmației", "Borșa", "Vișeu de Sus"],
    "Mehedinți": ["Drobeta-Turnu Severin", "Strehaia", "Orșova", "Baia de Aramă"],
    "Mureș": ["Târgu Mureș", "Reghin", "Sighișoara", "Luduș", "Iernut"],
    "Neamț": ["Piatra Neamț", "Roman", "Târgu Neamț", "Bicaz", "Roznov"],
    "Olt": ["Slatina", "Caracal", "Balș", "Scornicești", "Corabia"],
    "Prahova": ["Ploiești", "Câmpina", "Băicoi", "Sinaia", "Vălenii de Munte", "Bușteni"],
    "Satu Mare": ["Satu Mare", "Carei", "Negrești-Oaș", "Tășnad"],
    "Sălaj": ["Zalău", "Șimleu Silvaniei", "Jibou", "Cehu Silvaniei"],
    "Sibiu": ["Sibiu", "Mediaș", "Cisnădie", "Avrig", "Agnita", "Dumbrăveni"],
    "Suceava": ["Suceava", "Fălticeni", "Rădăuți", "Câmpulung Moldovenesc", "Vatra Dornei", "Gura Humorului"],
    "Teleorman": ["Alexandria", "Turnu Măgurele", "Roșiori de Vede", "Zimnicea"],
    "Timiș": ["Timișoara", "Lugoj", "Sânnicolau Mare", "Jimbolia", "Buziaș", "Făget", "Deta"],
    "Tulcea": ["Tulcea", "Măcin", "Babadag", "Isaccea", "Sulina"],
    "Vaslui": ["Vaslui", "Bârlad", "Huși", "Negrești", "Murgeni"],
    "Vâlcea": ["Râmnicu Vâlcea", "Drăgășani", "Băile Olănești", "Călimănești", "Horezu", "Brezoi", "Berbești"],
    "Vrancea": ["Focșani", "Adjud", "Mărășești", "Panciu", "Odobești"],
  },
  IT: {
    "Abruzzo": ["L'Aquila", "Chieti", "Pescara", "Teramo"],
    "Basilicata": ["Potenza", "Matera"],
    "Calabria": ["Catanzaro", "Cosenza", "Crotone", "Reggio Calabria", "Vibo Valentia"],
    "Campania": ["Napoli", "Avellino", "Benevento", "Caserta", "Salerno"],
    "Emilia-Romagna": ["Bologna", "Ferrara", "Forlì-Cesena", "Modena", "Parma", "Piacenza", "Ravenna", "Reggio Emilia", "Rimini"],
    "Friuli Venezia Giulia": ["Trieste", "Gorizia", "Pordenone", "Udine"],
    "Lazio": ["Roma", "Frosinone", "Latina", "Rieti", "Viterbo"],
    "Liguria": ["Genova", "Imperia", "La Spezia", "Savona"],
    "Lombardia": ["Milano", "Bergamo", "Brescia", "Como", "Cremona", "Lecco", "Lodi", "Mantova", "Monza e Brianza", "Pavia", "Sondrio", "Varese"],
    "Marche": ["Ancona", "Ascoli Piceno", "Fermo", "Macerata", "Pesaro e Urbino"],
    "Molise": ["Campobasso", "Isernia"],
    "Piemonte": ["Torino", "Alessandria", "Asti", "Biella", "Cuneo", "Novara", "Verbano-Cusio-Ossola", "Vercelli"],
    "Puglia": ["Bari", "Barletta-Andria-Trani", "Brindisi", "Foggia", "Lecce", "Taranto"],
    "Sardegna": ["Cagliari", "Nuoro", "Oristano", "Sassari", "Sud Sardegna"],
    "Sicilia": ["Palermo", "Agrigento", "Caltanissetta", "Catania", "Enna", "Messina", "Ragusa", "Siracusa", "Trapani"],
    "Toscana": ["Firenze", "Arezzo", "Grosseto", "Livorno", "Lucca", "Massa-Carrara", "Pisa", "Pistoia", "Prato", "Siena"],
    "Trentino-Alto Adige": ["Trento", "Bolzano"],
    "Umbria": ["Perugia", "Terni"],
    "Valle d'Aosta": ["Aosta"],
    "Veneto": ["Venezia", "Belluno", "Padova", "Rovigo", "Treviso", "Verona", "Vicenza"],
  },
  DE: {
    "Baden-Württemberg": ["Stuttgart", "Karlsruhe", "Freiburg", "Tübingen", "Mannheim", "Heidelberg", "Heilbronn", "Pforzheim", "Reutlingen", "Ulm", "Konstanz", "Esslingen", "Ludwigsburg", "Böblingen", "Göppingen", "Rastatt", "Ravensburg", "Lörrach"],
    "Bayern": ["München", "Nürnberg", "Augsburg", "Regensburg", "Würzburg", "Ingolstadt", "Fürth", "Erlangen", "Bamberg", "Bayreuth", "Passau", "Rosenheim", "Landshut", "Aschaffenburg", "Kempten"],
    "Berlin": ["Berlin"],
    "Brandenburg": ["Potsdam", "Cottbus", "Frankfurt (Oder)", "Brandenburg an der Havel", "Oranienburg", "Falkensee", "Eberswalde"],
    "Bremen": ["Bremen", "Bremerhaven"],
    "Hamburg": ["Hamburg"],
    "Hessen": ["Frankfurt am Main", "Wiesbaden", "Kassel", "Darmstadt", "Offenbach", "Hanau", "Gießen", "Marburg", "Fulda", "Rüsselsheim", "Bad Homburg"],
    "Mecklenburg-Vorpommern": ["Schwerin", "Rostock", "Stralsund", "Greifswald", "Wismar", "Neubrandenburg"],
    "Niedersachsen": ["Hannover", "Braunschweig", "Oldenburg", "Osnabrück", "Wolfsburg", "Göttingen", "Salzgitter", "Hildesheim", "Wilhelmshaven", "Lüneburg", "Celle", "Emden"],
    "Nordrhein-Westfalen": ["Düsseldorf", "Köln", "Dortmund", "Essen", "Duisburg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Münster", "Gelsenkirchen", "Aachen", "Mönchengladbach", "Krefeld", "Oberhausen", "Hagen", "Hamm", "Herne", "Solingen", "Leverkusen", "Paderborn", "Siegen"],
    "Rheinland-Pfalz": ["Mainz", "Ludwigshafen", "Koblenz", "Trier", "Kaiserslautern", "Worms", "Neustadt", "Speyer", "Bad Kreuznach"],
    "Saarland": ["Saarbrücken", "Neunkirchen", "Homburg", "Völklingen", "Sankt Ingbert", "Saarlouis", "Merzig"],
    "Sachsen": ["Dresden", "Leipzig", "Chemnitz", "Zwickau", "Plauen", "Görlitz", "Freiberg", "Bautzen", "Pirna"],
    "Sachsen-Anhalt": ["Magdeburg", "Halle", "Dessau-Roßlau", "Wittenberg", "Stendal", "Halberstadt", "Wernigerode"],
    "Schleswig-Holstein": ["Kiel", "Lübeck", "Flensburg", "Neumünster", "Norderstedt", "Elmshorn", "Pinneberg", "Itzehoe"],
    "Thüringen": ["Erfurt", "Jena", "Gera", "Weimar", "Gotha", "Eisenach", "Suhl", "Nordhausen", "Altenburg"],
  },
  US: {
    "Alabama": ["Jefferson", "Mobile", "Madison", "Montgomery", "Shelby", "Baldwin", "Tuscaloosa"],
    "Alaska": ["Anchorage", "Fairbanks North Star", "Matanuska-Susitna", "Kenai Peninsula"],
    "Arizona": ["Maricopa", "Pima", "Pinal", "Yavapai", "Mohave", "Yuma", "Coconino"],
    "Arkansas": ["Pulaski", "Benton", "Washington", "Sebastian", "Faulkner", "Saline"],
    "California": ["Los Angeles", "San Diego", "Orange", "Riverside", "San Bernardino", "Santa Clara", "Alameda", "Sacramento", "San Francisco", "Contra Costa", "Fresno", "San Mateo", "Kern", "Ventura"],
    "Colorado": ["Denver", "El Paso", "Arapahoe", "Jefferson", "Adams", "Douglas", "Larimer", "Boulder", "Weld"],
    "Connecticut": ["Fairfield", "Hartford", "New Haven", "Litchfield", "Middlesex", "New London", "Tolland", "Windham"],
    "Delaware": ["New Castle", "Kent", "Sussex"],
    "Florida": ["Miami-Dade", "Broward", "Palm Beach", "Hillsborough", "Orange", "Pinellas", "Duval", "Lee", "Polk", "Brevard"],
    "Georgia": ["Fulton", "Gwinnett", "Cobb", "DeKalb", "Chatham", "Cherokee", "Clayton", "Henry", "Forsyth"],
    "Hawaii": ["Honolulu", "Hawaii", "Maui", "Kauai"],
    "Idaho": ["Ada", "Canyon", "Kootenai", "Bonneville", "Bannock", "Twin Falls"],
    "Illinois": ["Cook", "DuPage", "Lake", "Will", "Kane", "McHenry", "Winnebago", "Madison", "St. Clair", "Sangamon"],
    "Indiana": ["Marion", "Lake", "Allen", "Hamilton", "St. Joseph", "Elkhart", "Tippecanoe", "Hendricks", "Johnson"],
    "Iowa": ["Polk", "Linn", "Scott", "Johnson", "Black Hawk", "Woodbury", "Dubuque", "Story", "Dallas"],
    "Kansas": ["Johnson", "Sedgwick", "Shawnee", "Wyandotte", "Douglas", "Leavenworth", "Riley"],
    "Kentucky": ["Jefferson", "Fayette", "Kenton", "Boone", "Warren", "Hardin", "Daviess", "Campbell"],
    "Louisiana": ["East Baton Rouge", "Jefferson", "Orleans", "St. Tammany", "Caddo", "Calcasieu", "Lafayette", "Ouachita"],
    "Maine": ["Cumberland", "York", "Penobscot", "Kennebec", "Androscoggin"],
    "Maryland": ["Montgomery", "Prince George's", "Baltimore", "Anne Arundel", "Howard", "Baltimore City", "Frederick", "Harford"],
    "Massachusetts": ["Middlesex", "Worcester", "Essex", "Suffolk", "Norfolk", "Bristol", "Plymouth", "Hampden"],
    "Michigan": ["Wayne", "Oakland", "Macomb", "Kent", "Genesee", "Washtenaw", "Ingham", "Ottawa", "Kalamazoo"],
    "Minnesota": ["Hennepin", "Ramsey", "Dakota", "Anoka", "Washington", "Scott", "Olmsted", "St. Louis"],
    "Mississippi": ["Hinds", "Harrison", "DeSoto", "Rankin", "Jackson", "Madison", "Lee", "Forrest"],
    "Missouri": ["St. Louis", "Jackson", "St. Charles", "Greene", "Clay", "Jefferson", "Boone", "Jasper"],
    "Montana": ["Yellowstone", "Missoula", "Gallatin", "Flathead", "Cascade", "Lewis and Clark"],
    "Nebraska": ["Douglas", "Lancaster", "Sarpy", "Hall", "Buffalo", "Scotts Bluff"],
    "Nevada": ["Clark", "Washoe", "Carson City", "Elko", "Douglas", "Lyon"],
    "New Hampshire": ["Hillsborough", "Rockingham", "Merrimack", "Strafford", "Grafton"],
    "New Jersey": ["Bergen", "Middlesex", "Essex", "Hudson", "Monmouth", "Ocean", "Union", "Passaic", "Camden", "Morris", "Burlington"],
    "New Mexico": ["Bernalillo", "Doña Ana", "Santa Fe", "Sandoval", "San Juan", "Valencia"],
    "New York": ["Kings", "Queens", "New York", "Suffolk", "Bronx", "Nassau", "Westchester", "Erie", "Monroe", "Richmond", "Onondaga", "Albany"],
    "North Carolina": ["Mecklenburg", "Wake", "Guilford", "Forsyth", "Cumberland", "Durham", "Buncombe", "New Hanover", "Gaston"],
    "North Dakota": ["Cass", "Burleigh", "Grand Forks", "Ward", "Williams", "Stark"],
    "Ohio": ["Franklin", "Cuyahoga", "Hamilton", "Summit", "Montgomery", "Lucas", "Butler", "Stark", "Warren"],
    "Oklahoma": ["Oklahoma", "Tulsa", "Cleveland", "Canadian", "Comanche", "Rogers"],
    "Oregon": ["Multnomah", "Washington", "Clackamas", "Lane", "Marion", "Jackson", "Deschutes"],
    "Pennsylvania": ["Philadelphia", "Allegheny", "Montgomery", "Bucks", "Delaware", "Chester", "Lancaster", "York", "Berks", "Lehigh"],
    "Rhode Island": ["Providence", "Kent", "Washington", "Newport", "Bristol"],
    "South Carolina": ["Greenville", "Richland", "Charleston", "Horry", "Spartanburg", "Lexington", "York"],
    "South Dakota": ["Minnehaha", "Pennington", "Lincoln", "Brown", "Brookings", "Codington"],
    "Tennessee": ["Shelby", "Davidson", "Knox", "Hamilton", "Rutherford", "Williamson", "Sullivan", "Sumner"],
    "Texas": ["Harris", "Dallas", "Tarrant", "Bexar", "Travis", "Collin", "Hidalgo", "El Paso", "Denton", "Fort Bend", "Williamson", "Montgomery"],
    "Utah": ["Salt Lake", "Utah", "Davis", "Weber", "Washington", "Cache", "Tooele"],
    "Vermont": ["Chittenden", "Rutland", "Washington", "Windsor", "Windham", "Franklin"],
    "Virginia": ["Fairfax", "Prince William", "Virginia Beach", "Loudoun", "Chesterfield", "Henrico", "Arlington", "Norfolk"],
    "Washington": ["King", "Pierce", "Snohomish", "Spokane", "Clark", "Thurston", "Kitsap", "Yakima"],
    "West Virginia": ["Kanawha", "Berkeley", "Cabell", "Monongalia", "Wood", "Raleigh"],
    "Wisconsin": ["Milwaukee", "Dane", "Waukesha", "Brown", "Racine", "Outagamie", "Winnebago", "Kenosha", "Rock"],
    "Wyoming": ["Laramie", "Natrona", "Campbell", "Sweetwater", "Fremont", "Albany"],
    "District of Columbia": ["District of Columbia"],
  },
  AT: {
    "Burgenland": ["Eisenstadt", "Güssing", "Jennersdorf", "Mattersburg", "Neusiedl am See", "Oberpullendorf", "Oberwart"],
    "Kärnten": ["Klagenfurt", "Villach", "Feldkirchen", "Hermagor", "Sankt Veit an der Glan", "Spittal an der Drau", "Völkermarkt", "Wolfsberg"],
    "Niederösterreich": ["Amstetten", "Baden", "Bruck an der Leitha", "Gänserndorf", "Gmünd", "Hollabrunn", "Horn", "Korneuburg", "Krems an der Donau", "Lilienfeld", "Melk", "Mistelbach", "Mödling", "Neunkirchen", "Sankt Pölten", "Scheibbs", "Tulln", "Waidhofen an der Thaya", "Wiener Neustadt", "Zwettl"],
    "Oberösterreich": ["Braunau am Inn", "Eferding", "Freistadt", "Gmunden", "Grieskirchen", "Kirchdorf an der Krems", "Linz", "Perg", "Ried im Innkreis", "Rohrbach", "Schärding", "Steyr", "Urfahr-Umgebung", "Vöcklabruck", "Wels"],
    "Salzburg": ["Hallein", "Salzburg", "Sankt Johann im Pongau", "Tamsweg", "Zell am See"],
    "Steiermark": ["Bruck-Mürzzuschlag", "Deutschlandsberg", "Graz", "Graz-Umgebung", "Hartberg-Fürstenfeld", "Leibnitz", "Leoben", "Liezen", "Murau", "Murtal", "Südoststeiermark", "Voitsberg", "Weiz"],
    "Tirol": ["Imst", "Innsbruck", "Innsbruck-Land", "Kitzbühel", "Kufstein", "Landeck", "Lienz", "Reutte", "Schwaz"],
    "Vorarlberg": ["Bludenz", "Bregenz", "Dornbirn", "Feldkirch"],
    "Wien": ["Wien"],
  },
};

export const DISTRICT_MAP: Record<string, Record<string, string>> = {
  SK: {
    "Bratislava": "Bratislava I", "Pezinok": "Pezinok", "Senec": "Senec", "Malacky": "Malacky",
    "Trnava": "Trnava", "Piešťany": "Piešťany", "Dunajská Streda": "Dunajská Streda", "Galanta": "Galanta", "Hlohovec": "Hlohovec", "Senica": "Senica", "Skalica": "Skalica",
    "Trenčín": "Trenčín", "Považská Bystrica": "Považská Bystrica", "Púchov": "Púchov", "Prievidza": "Prievidza", "Nové Mesto nad Váhom": "Nové Mesto nad Váhom", "Partizánske": "Partizánske", "Bánovce nad Bebravou": "Bánovce nad Bebravou", "Ilava": "Ilava", "Myjava": "Myjava",
    "Nitra": "Nitra", "Komárno": "Komárno", "Levice": "Levice", "Nové Zámky": "Nové Zámky", "Šaľa": "Šaľa", "Topoľčany": "Topoľčany", "Zlaté Moravce": "Zlaté Moravce",
    "Žilina": "Žilina", "Martin": "Martin", "Čadca": "Čadca", "Dolný Kubín": "Dolný Kubín", "Liptovský Mikuláš": "Liptovský Mikuláš", "Námestovo": "Námestovo", "Ružomberok": "Ružomberok", "Tvrdošín": "Tvrdošín", "Turčianske Teplice": "Turčianske Teplice", "Bytča": "Bytča", "Kysucké Nové Mesto": "Kysucké Nové Mesto",
    "Banská Bystrica": "Banská Bystrica", "Zvolen": "Zvolen", "Lučenec": "Lučenec", "Rimavská Sobota": "Rimavská Sobota", "Žiar nad Hronom": "Žiar nad Hronom", "Brezno": "Brezno", "Detva": "Detva", "Krupina": "Krupina", "Revúca": "Revúca", "Veľký Krtíš": "Veľký Krtíš", "Banská Štiavnica": "Banská Štiavnica", "Poltár": "Poltár",
    "Prešov": "Prešov", "Poprad": "Poprad", "Bardejov": "Bardejov", "Humenné": "Humenné", "Kežmarok": "Kežmarok", "Levoča": "Levoča", "Medzilaborce": "Medzilaborce", "Sabinov": "Sabinov", "Snina": "Snina", "Stará Ľubovňa": "Stará Ľubovňa", "Stropkov": "Stropkov", "Svidník": "Svidník", "Vranov nad Topľou": "Vranov nad Topľou",
    "Košice": "Košice I", "Michalovce": "Michalovce", "Spišská Nová Ves": "Spišská Nová Ves", "Trebišov": "Trebišov", "Rožňava": "Rožňava", "Gelnica": "Gelnica", "Sobrance": "Sobrance", "Moldava nad Bodvou": "Košice-okolie",
  },
  CZ: {
    "Praha": "Praha", "Brno": "Brno-město", "Ostrava": "Ostrava-město", "Plzeň": "Plzeň-město",
    "Liberec": "Liberec", "Olomouc": "Olomouc", "České Budějovice": "České Budějovice", "Hradec Králové": "Hradec Králové",
    "Ústí nad Labem": "Ústí nad Labem", "Pardubice": "Pardubice", "Zlín": "Zlín", "Jihlava": "Jihlava",
    "Karlovy Vary": "Karlovy Vary", "Kladno": "Kladno",
  },
  HU: {
    "Budapest": "Budapest", "Debrecen": "Debrecen", "Szeged": "Szeged", "Miskolc": "Miskolc",
    "Pécs": "Pécs", "Győr": "Győr", "Nyíregyháza": "Nyíregyháza", "Kecskemét": "Kecskemét",
    "Székesfehérvár": "Székesfehérvár", "Szombathely": "Szombathely", "Szolnok": "Szolnok",
    "Eger": "Eger", "Tatabánya": "Tatabánya", "Veszprém": "Veszprém", "Kaposvár": "Kaposvár",
    "Zalaegerszeg": "Zalaegerszeg", "Salgótarján": "Salgótarján", "Szekszárd": "Szekszárd", "Békéscsaba": "Békéscsaba",
  },
  RO: {
    "București": "Sector 1", "Cluj-Napoca": "Cluj-Napoca", "Timișoara": "Timișoara", "Iași": "Iași", "Constanța": "Constanța",
    "Craiova": "Craiova", "Brașov": "Brașov", "Galați": "Galați", "Ploiești": "Ploiești", "Oradea": "Oradea",
    "Brăila": "Brăila", "Arad": "Arad", "Pitești": "Pitești", "Sibiu": "Sibiu", "Bacău": "Bacău",
    "Târgu Mureș": "Târgu Mureș", "Baia Mare": "Baia Mare", "Buzău": "Buzău", "Botoșani": "Botoșani", "Satu Mare": "Satu Mare",
    "Suceava": "Suceava", "Alba Iulia": "Alba Iulia", "Deva": "Deva", "Bistrița": "Bistrița",
  },
  IT: {
    "Roma": "Roma", "Milano": "Milano", "Napoli": "Napoli", "Torino": "Torino", "Palermo": "Palermo",
    "Genova": "Genova", "Bologna": "Bologna", "Firenze": "Firenze", "Bari": "Bari", "Catania": "Catania",
    "Venezia": "Venezia", "Verona": "Verona", "Padova": "Padova", "Trieste": "Trieste",
    "Brescia": "Brescia", "Parma": "Parma", "Modena": "Modena", "Perugia": "Perugia", "Cagliari": "Cagliari",
    "Ancona": "Ancona", "Messina": "Messina", "Taranto": "Taranto",
  },
  DE: {
    "Berlin": "Berlin", "Hamburg": "Hamburg", "München": "München", "Köln": "Köln", "Frankfurt": "Frankfurt am Main",
    "Stuttgart": "Stuttgart", "Düsseldorf": "Düsseldorf", "Leipzig": "Leipzig", "Dortmund": "Dortmund",
    "Essen": "Essen", "Bremen": "Bremen", "Dresden": "Dresden", "Hannover": "Hannover",
    "Nürnberg": "Nürnberg", "Mannheim": "Mannheim", "Karlsruhe": "Karlsruhe", "Augsburg": "Augsburg",
    "Wiesbaden": "Wiesbaden", "Mainz": "Mainz", "Kiel": "Kiel", "Magdeburg": "Magdeburg",
    "Erfurt": "Erfurt", "Schwerin": "Schwerin", "Potsdam": "Potsdam", "Saarbrücken": "Saarbrücken",
  },
  US: {
    "New York": "New York", "Los Angeles": "Los Angeles", "Chicago": "Cook", "Houston": "Harris",
    "Phoenix": "Maricopa", "Philadelphia": "Philadelphia", "San Antonio": "Bexar", "San Diego": "San Diego",
    "Dallas": "Dallas", "San Jose": "Santa Clara", "Austin": "Travis", "Jacksonville": "Duval",
    "San Francisco": "San Francisco", "Seattle": "King", "Denver": "Denver", "Nashville": "Davidson",
    "Boston": "Suffolk", "Portland": "Multnomah", "Las Vegas": "Clark", "Miami": "Miami-Dade",
    "Atlanta": "Fulton", "Minneapolis": "Hennepin", "Tampa": "Hillsborough", "Cleveland": "Cuyahoga",
    "Pittsburgh": "Allegheny", "St. Louis": "St. Louis", "Cincinnati": "Hamilton", "Detroit": "Wayne",
    "Washington": "District of Columbia", "Baltimore": "Baltimore", "Milwaukee": "Milwaukee",
  },
  AT: {
    "Wien": "Wien", "Graz": "Graz", "Linz": "Linz", "Salzburg": "Salzburg", "Innsbruck": "Innsbruck",
    "Klagenfurt": "Klagenfurt", "Villach": "Villach", "Wels": "Wels", "St. Pölten": "Sankt Pölten",
    "Dornbirn": "Dornbirn", "Wiener Neustadt": "Wiener Neustadt", "Steyr": "Steyr", "Feldkirch": "Feldkirch",
    "Bregenz": "Bregenz", "Leonding": "Linz", "Klosterneuburg": "Tulln", "Baden": "Baden",
    "Leoben": "Leoben", "Krems an der Donau": "Krems an der Donau", "Traun": "Linz",
    "Amstetten": "Amstetten", "Lustenau": "Dornbirn", "Kapfenberg": "Bruck-Mürzzuschlag", "Mödling": "Mödling",
    "Hallein": "Hallein", "Kufstein": "Kufstein", "Braunau am Inn": "Braunau am Inn", "Schwechat": "Bruck an der Leitha",
    "Stockerau": "Korneuburg", "Saalfelden": "Zell am See", "Ansfelden": "Linz", "Tulln": "Tulln",
    "Hohenems": "Dornbirn", "Spittal an der Drau": "Spittal an der Drau", "Telfs": "Innsbruck-Land", "Ternitz": "Neunkirchen",
    "Perchtoldsdorf": "Mödling", "Eisenstadt": "Eisenstadt", "Feldkirchen": "Feldkirchen", "Bludenz": "Bludenz",
    "Bad Ischl": "Gmunden", "Wolfsberg": "Wolfsberg", "Korneuburg": "Korneuburg", "Neunkirchen": "Neunkirchen",
    "Hard": "Bregenz", "Vöcklabruck": "Vöcklabruck", "Lienz": "Lienz", "Judenburg": "Murtal",
    "Hall in Tirol": "Innsbruck-Land", "Mistelbach": "Mistelbach", "Ried im Innkreis": "Ried im Innkreis",
    "Gmunden": "Gmunden", "Wörgl": "Kufstein", "Oberwart": "Oberwart", "Zwettl": "Zwettl",
  },
};

export function getAutoRegion(countryCode: string, city: string): string | null {
  if (!countryCode || !city) return null;
  const countryMap = REGION_MAP[countryCode];
  if (!countryMap) return null;
  const trimmed = city.trim();
  if (countryMap[trimmed]) return countryMap[trimmed];
  const lower = trimmed.toLowerCase();
  for (const [key, region] of Object.entries(countryMap)) {
    if (key.toLowerCase() === lower) return region;
    if (lower.startsWith(key.toLowerCase())) return region;
  }
  return null;
}

export function getAutoDistrict(countryCode: string, city: string): string | null {
  if (!countryCode || !city) return null;
  const countryMap = DISTRICT_MAP[countryCode];
  if (!countryMap) return null;
  const trimmed = city.trim();
  if (countryMap[trimmed]) return countryMap[trimmed];
  const lower = trimmed.toLowerCase();
  for (const [key, district] of Object.entries(countryMap)) {
    if (key.toLowerCase() === lower) return district;
    if (lower.startsWith(key.toLowerCase())) return district;
  }
  return null;
}

export function getDistrictsForRegion(countryCode: string, region: string, currentDistrict?: string): string[] {
  const countryDistricts = DISTRICTS_BY_REGION[countryCode];
  const list = countryDistricts ? (countryDistricts[region] || []) : [];
  if (currentDistrict && currentDistrict.trim() && !list.includes(currentDistrict)) {
    return [currentDistrict, ...list];
  }
  return list;
}

export interface GeoLabels {
  region: string;
  district: string;
  city: string;
}

const GEO_LABELS: Record<string, GeoLabels> = {
  SK: { region: "Kraj", district: "Okres", city: "Obec" },
  CZ: { region: "Kraj", district: "Okres", city: "Obec" },
  HU: { region: "Vármegye", district: "Járás", city: "Település" },
  DE: { region: "Bundesland", district: "Landkreis", city: "Gemeinde" },
  AT: { region: "Bundesland", district: "Bezirk", city: "Gemeinde" },
  IT: { region: "Regione", district: "Provincia", city: "Comune" },
  RO: { region: "Județ", district: "Localitate", city: "Sat/Sector" },
  US: { region: "State", district: "County", city: "City" },
};

const DEFAULT_GEO_LABELS: GeoLabels = { region: "Region", district: "District", city: "City" };

export function getGeoLabels(countryCode: string): GeoLabels {
  return GEO_LABELS[countryCode] || DEFAULT_GEO_LABELS;
}
