import { useState } from "react";
import { ArrowRight, BriefcaseBusiness, Check, ChevronDown, Clock3, Headphones, Phone, Search, Users } from "lucide-react";

const missions = ["FMO", "Medical Partner Cooperation", "Zdravotná poisťovňa Dôvera", "Prvá stavebná sporiteľňa", "CZ Účty a platby", "HU Customer Care", "Obnova zmlúv 2026", "Retencia klientov"];
const queues = ["Inbound Medical Partner", "Inbound FMO", "Inbound Dôvera", "Klientská linka – SK", "CZ zákaznícka podpora", "Retencia – prioritná linka"];

export function CommandCenter() {
  const [missionSet, setMissionSet] = useState<string[]>(missions.slice(0, 2));
  const [queueSet, setQueueSet] = useState<string[]>([queues[1]]);
  const [office, setOffice] = useState(false);
  const [query, setQuery] = useState("");
  const [expanded, setExpanded] = useState<string[]>(["Medical Partner Cooperation", "Inbound FMO"]);
  const [started, setStarted] = useState(false);
  const filteredMissions = missions.filter((item) => item.toLowerCase().includes(query.toLowerCase()));
  const filteredQueues = queues.filter((item) => item.toLowerCase().includes(query.toLowerCase()));
  const selected = missionSet.length + queueSet.length + (office ? 1 : 0);
  const toggle = (list: string[], set: (value: string[]) => void, item: string) => set(list.includes(item) ? list.filter((x) => x !== item) : [...list, item]);
  if (started) return <div className="flex min-h-screen items-center justify-center bg-[#edf1f7] p-8 font-sans"><div className="w-full max-w-md rounded-3xl bg-white p-9 text-center shadow-xl"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#e5f7ed] text-[#199653]"><Check size={28} /></div><h2 className="mt-4 text-xl font-bold text-[#1d2d43]">Zmena je spustená</h2><p className="mt-2 text-sm text-[#718094]">{selected} oblastí je pripravených.</p><button onClick={() => setStarted(false)} className="mt-6 rounded-lg border border-[#d4dce7] px-4 py-2 text-sm">Upraviť výber</button></div></div>;
  return <div className="min-h-screen bg-[#edf1f7] p-4 font-sans text-[#243247]">
    <div className="mx-auto flex min-h-[calc(100vh-2rem)] max-w-[1240px] flex-col overflow-hidden rounded-3xl border border-[#d3dce8] bg-white shadow-[0_25px_80px_rgba(40,57,83,.18)]">
      <header className="flex items-center justify-between border-b border-[#e4e9f0] bg-[#fffaf8] px-7 py-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#c8102e] text-white"><Headphones size={20} /></div><div><div className="text-[17px] font-bold">Prihlásenie do zmeny</div><div className="text-xs text-[#7d8999]">Vyberte všetky pracovné oblasti pre dnešnú zmenu</div></div></div><div className="flex items-center gap-3 rounded-xl border border-[#dfe5ed] bg-white px-3 py-2 text-xs"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#dce8f8] font-bold text-[#386da9]">PR</div><div><b>Peter Repman</b><div className="text-[10px] text-[#8a95a4]">seman@dialcom.sk</div></div><span className="rounded-full bg-[#eefbf2] px-2 py-1 text-[#249251]">Online</span></div></header>
      <div className="grid flex-1 grid-cols-[270px_1fr]">
        <aside className="border-r border-[#e4e9f0] bg-[#f8fafc] p-6"><div className="text-[11px] font-bold uppercase tracking-[.14em] text-[#8995a5]">Dnešná zmena</div><h1 className="mt-2 text-2xl font-bold tracking-[-.04em]">Pripravení na štart?</h1><p className="mt-2 text-sm leading-6 text-[#718094]">Vyberte aspoň jednu Misiu alebo inbound frontu.</p><div className="mt-6 rounded-2xl border border-[#dfe6ee] bg-white p-4"><div className="text-[10px] uppercase tracking-wider text-[#8995a5]">Vybrané oblasti</div><div className="mt-1 text-3xl font-bold text-[#c8102e]">{selected}</div><div className="mt-1 text-xs text-[#718094]">{missionSet.length} Misií · {queueSet.length} fronty{office ? " · Back Office" : ""}</div></div><div className="mt-4 space-y-2"><Metric label="Kontakty" value="18 / 40" pct="45%" color="#397fe6" /><Metric label="Hovory" value="12 / 30" pct="40%" color="#c8102e" /><Metric label="Konverzie" value="4 / 8" pct="50%" color="#1a9b57" /></div><div className="mt-5 border-t border-[#e1e7ef] pt-5"><div className="mb-2 flex justify-between text-[11px] font-bold uppercase tracking-wider text-[#8995a5]"><span>Plánovaná fronta</span><span className="text-[#33445a]">27</span></div><Metric label="Dnes" value="12" pct="100%" color="#397fe6" /><Metric label="Zajtra" value="9" pct="75%" color="#397fe6" /><Metric label="St 25. 9." value="6" pct="50%" color="#397fe6" /></div><div className="mt-5 border-t border-[#e1e7ef] pt-5"><div className="mb-2 flex items-center justify-between text-[11px] font-bold uppercase tracking-wider text-[#8995a5]"><span>Back Office agenda</span><BriefcaseBusiness size={14} className="text-[#7c5ac8]" /></div><div className="grid grid-cols-3 gap-1"><Mini label="Nové" value="4" /><Mini label="Čaká" value="7" /><Mini label="Týždeň" value="19" /></div></div></aside>
        <main className="flex min-h-0 flex-col"><div className="flex items-center gap-3 border-b border-[#e4e9f0] px-6 py-4"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#9aa6b5]" size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Hľadať podľa názvu, krajiny alebo čísla…" className="h-10 w-full rounded-xl border border-[#d8e0ea] bg-[#fafbfd] pl-9 pr-3 text-sm outline-none focus:border-[#7ca3db]" /></div><span className="rounded-xl bg-[#f0f4f9] px-3 py-2 text-xs text-[#718094]">{selected} vybrané</span></div><div className="flex-1 overflow-auto p-6"><Group title="Misie" count={`${missionSet.length} / ${missions.length}`} color="#397fe6">{filteredMissions.map((item) => <Row key={item} label={item} selected={missionSet.includes(item)} onClick={() => toggle(missionSet, setMissionSet, item)} open={expanded.includes(item)} expand={() => setExpanded((p) => p.includes(item) ? p.filter((x) => x !== item) : [...p, item])} color="#397fe6" detail="SK · Telefón · 09:00 – 17:00 · Aktívna verzia v1" />)}</Group><Group title="Inbound fronty" count={`${queueSet.length} / ${queues.length}`} color="#1a9b57">{filteredQueues.map((item, index) => <Row key={item} label={item} selected={queueSet.includes(item)} onClick={() => toggle(queueSet, setQueueSet, item)} open={expanded.includes(item)} expand={() => setExpanded((p) => p.includes(item) ? p.filter((x) => x !== item) : [...p, item])} color="#1a9b57" detail={`${index === 1 ? "023 239 9030 · 1 online · 3 čaká" : "02 555 014 40 · 2 online · 09:00 – 17:00"}`} />)}</Group><button onClick={() => setOffice(!office)} className={`mt-5 flex w-full items-center gap-3 rounded-xl border p-4 text-left ${office ? "border-[#bca9de] bg-[#fbfaff]" : "border-[#e0d9ed] bg-white"}`}><div className="h-8 w-1 rounded-full bg-[#7c5ac8]" /><BriefcaseBusiness size={18} className="text-[#7c5ac8]" /><div className="flex-1"><b className="text-sm">Back Office</b><div className="text-[11px] text-[#887b9e]">Úlohy a interné požiadavky</div></div><span className={`flex h-5 w-5 items-center justify-center rounded border-2 ${office ? "border-[#7c5ac8] bg-[#7c5ac8] text-white" : "border-[#cbd5e1]"}`}>{office && <Check size={13} />}</span></button></div><footer className="flex items-center justify-between border-t border-[#e4e9f0] bg-[#fbfcfe] px-6 py-4"><span className="flex items-center gap-2 text-xs text-[#718094]"><Users size={15} /><b className="text-[#33445a]">{selected}</b> oblastí pripravených</span><button onClick={() => setStarted(true)} disabled={!selected} className="flex items-center gap-2 rounded-xl bg-[#c8102e] px-6 py-3 text-sm font-semibold text-white disabled:opacity-40">Začať zmenu <ArrowRight size={17} /></button></footer></main>
      </div>
    </div>
  </div>;
}
function Metric({ label, value, pct, color }: { label: string; value: string; pct: string; color: string }) { return <div className="mb-2"><div className="flex justify-between text-[10px]"><span className="text-[#718094]">{label}</span><b>{value}</b></div><div className="mt-1 h-1 rounded-full bg-[#e8edf3]"><div className="h-1 rounded-full" style={{ width: pct, background: color }} /></div></div>; }
function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-[#e1e7ef] bg-white px-2 py-2 text-center"><div className="text-base font-bold text-[#7c5ac8]">{value}</div><div className="text-[9px] text-[#8b98a8]">{label}</div></div>; }
function Group({ title, count, color, children }: { title: string; count: string; color: string; children: React.ReactNode }) { return <section className="mb-6"><div className="mb-3 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.14em] text-[#748193]"><span className="h-2 w-2 rounded-full" style={{ background: color }} />{title}<span className="normal-case tracking-normal text-[#a0aab8]">· {count}</span></div><div className="grid gap-2 xl:grid-cols-2">{children}</div></section>; }
function Row({ label, selected, onClick, open, expand, color, detail }: { label: string; selected: boolean; onClick: () => void; open: boolean; expand: () => void; color: string; detail: string }) { return <div className={`rounded-xl border ${selected ? "bg-[#f8fbff]" : "bg-white"} ${selected ? "border-[#a9c9f4]" : "border-[#e2e7ee]"}`}><div className="flex cursor-pointer items-center gap-3 p-3" onClick={onClick}><div className="h-9 w-1 rounded-full" style={{ background: color }} /><div className="flex h-8 w-8 items-center justify-center rounded-lg" style={{ background: `${color}13`, color }}><Phone size={15} /></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{label}</div><div className="mt-1 text-[10px] text-[#8793a2]">{detail.split(" · ").slice(0, 2).join(" · ")}</div></div><button onClick={(e) => { e.stopPropagation(); expand(); }} className="rounded p-1 text-[#93a0b0]">{open ? <ChevronDown size={16} /> : <Clock3 size={15} />}</button><span className="flex h-[18px] w-[18px] items-center justify-center rounded border-2" style={{ background: selected ? color : "transparent", borderColor: selected ? color : "#cbd5e1" }}>{selected && <Check size={12} color="white" />}</span></div>{open && <div className="border-t border-[#e7edf4] px-14 py-2 text-[10px] text-[#6f7c8d]">{detail}</div>}</div>; }