import { useMemo, useState } from "react";
import { ArrowUpDown, CalendarClock, ChevronDown, ChevronUp, Filter, PhoneCall, Search, SlidersHorizontal, Stethoscope, Users, X } from "lucide-react";
import "./PulseOriginalRedesign.css";

type Contact={name:string;phone:string;email:string;city:string;address:string;zip:string;region:string;district:string;country:string;ico:string;date:string;attempts:number;group:string;status:string;note:string;disposition:string;isReferral:boolean};
const contacts:Contact[]=[
 {name:"Melichar SRO — MUDr. Peter Seman",phone:"+421 948 519 438",email:"recepcia@melichar.sk",city:"Bratislava",address:"Ružinovská 12",zip:"821 01",region:"Bratislavský",district:"Bratislava II",country:"Slovakia",ico:"51234001",date:"18.09.2026 09:00",attempts:18,group:"Due",status:"Due",note:"Call reception before 10:00",disposition:"Callback overdue",isReferral:true},
 {name:"Tes AmbuMed Partner — MUDr. Martin Kabát",phone:"+421 915 796 900",email:"ambulancia@ambumed.sk",city:"Košice",address:"Trieda SNP 41",zip:"040 11",region:"Košický",district:"Košice II",country:"Slovakia",ico:"47392018",date:"16.09.2026 09:00",attempts:1,group:"Pending",status:"Pending",note:"Waiting for clinic confirmation",disposition:"No outcome",isReferral:true},
 {name:"Tes Klinika Medifem X — MUDr. Martin Kabát",phone:"+421 905 773 403",email:"kontakt@medifem.sk",city:"Nitra",address:"Štefánikova 8",zip:"949 01",region:"Nitriansky",district:"Nitra",country:"Slovakia",ico:"36841022",date:"07.09.2026 09:00",attempts:0,group:"Team callbacks",status:"Team callbacks",note:"Assigned to partner team",disposition:"Scheduled",isReferral:true},
 {name:"Tes Zdravotné centrum Iris — MUDr. Martin Kabát",phone:"+421 915 796 900",email:"iris@zciris.sk",city:"Žilina",address:"Hurbanova 19",zip:"010 01",region:"Žilinský",district:"Žilina",country:"Slovakia",ico:"52901173",date:"10.10.2026 09:00",attempts:9,group:"My callbacks",status:"My callbacks",note:"Ask for MUDr. Kabát",disposition:"Scheduled",isReferral:true},
 {name:"Polaris Medical s.r.o. — MUDr. Jana Horváthová",phone:"+421 907 229 311",email:"office@polaris-med.sk",city:"Prešov",address:"Levočská 5",zip:"080 01",region:"Prešovský",district:"Prešov",country:"Slovakia",ico:"44710392",date:"11.10.2026 13:30",attempts:3,group:"Due",status:"Due",note:"Follow up on cooperation terms",disposition:"Callback due",isReferral:false},
 {name:"MediPoint klinika — MUDr. Andrej Bielik",phone:"+421 903 441 820",email:"hello@medipoint.sk",city:"Trnava",address:"Hlavná 27",zip:"917 01",region:"Trnavský",district:"Trnava",country:"Slovakia",ico:"50381940",date:"12.10.2026 08:30",attempts:0,group:"Pending",status:"Pending",note:"First contact not completed",disposition:"Unhandled",isReferral:false},
 {name:"Ambulancia Aurora — MUDr. Ivana Nováková",phone:"+421 904 112 775",email:"info@aurora.sk",city:"Banská Bystrica",address:"Dolná 14",zip:"974 01",region:"Banskobystrický",district:"Banská Bystrica",country:"Slovakia",ico:"54110982",date:"13.10.2026 10:15",attempts:2,group:"Other callbacks",status:"Other callbacks",note:"Callback owned by another agent",disposition:"Team callback",isReferral:false},
];
const tabs=["All","Due","My callbacks","Team callbacks","Pending","New referrals"];
const fields=["All fields","Name","Phone","Email","City","Address","ZIP","Region","District","Country","IČO","New referrals"];
const sorts=["Callback soonest","Name (A–Z)","Attempts high → low"];
const initials=(name:string)=>name.split(" ").filter(Boolean).slice(0,2).map(x=>x[0]).join("");

export function PulseOriginalRedesign(){
 const [active,setActive]=useState("New referrals"),[query,setQuery]=useState(""),[field,setField]=useState("All fields"),[fieldOpen,setFieldOpen]=useState(false),[sortOpen,setSortOpen]=useState(false),[sort,setSort]=useState("Callback soonest"),[collapsed,setCollapsed]=useState<Record<string,boolean>>({});
 const filtered=useMemo(()=>contacts.filter(c=>{const values:Record<string,string>={Name:c.name,Phone:c.phone,Email:c.email,City:c.city,Address:c.address,ZIP:c.zip,Region:c.region,District:c.district,Country:c.country,"IČO":c.ico,"New referrals":c.isReferral?"new referral":""};const hay=field==="All fields"?Object.values(values).join(" "):values[field]||"";const matchesTab=active==="All"||(active==="New referrals"?c.isReferral:c.status===active);return (!query||hay.toLowerCase().includes(query.toLowerCase()))&&matchesTab}).sort((a,b)=>sort==="Name (A–Z)"?a.name.localeCompare(b.name):sort==="Attempts high → low"?b.attempts-a.attempts:a.date.localeCompare(b.date)),[active,field,query,sort]);
 const groups=Array.from(new Set(filtered.map(c=>c.group)));
 return <main className="porq-stage"><section className="porq-window" aria-label="Mission contacts">
  <header className="porq-top"><div className="porq-mark"><Users size={19}/></div><div><h1>Mission contacts</h1><p>Medical Partner Cooperation · Agent Workspace Queue</p></div><button className="porq-close" aria-label="Close"><X size={18}/></button></header>
   <div className="porq-tools"><div className="porq-searchrow"><label className="porq-search"><Search size={15}/><input aria-label="Search contacts" value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${field === "All fields" ? "all contact fields" : field.toLowerCase()}…`}/>{query&&<button className="porq-icon porq-clear" onClick={()=>setQuery("")} aria-label="Clear search"><X size={14}/></button>}</label>
   <div className="porq-relative"><button className={`porq-btn ${fieldOpen?"active":""}`} onClick={()=>{setFieldOpen(!fieldOpen);setSortOpen(false)}}><SlidersHorizontal size={14}/>{field}<ChevronDown size={13}/></button>{fieldOpen&&<div className="porq-popover" role="menu">{fields.map(x=><label key={x}><input type="radio" checked={field===x} onChange={()=>{setField(x);setFieldOpen(false)}}/>{x}</label>)}</div>}</div>
    <div className="porq-relative"><button className={`porq-btn ${sortOpen?"active":""}`} onClick={()=>{setSortOpen(!sortOpen);setFieldOpen(false)}}><ArrowUpDown size={14}/>{sort}<ChevronDown size={13}/></button>{sortOpen&&<div className="porq-popover" role="menu">{sorts.map(x=><label key={x}><input type="radio" checked={sort===x} onChange={()=>{setSort(x);setSortOpen(false)}}/>{x}</label>)}</div>}</div>
  </div><nav className="porq-tabs" aria-label="Queue filters">{tabs.map(t=><button className={`porq-tab ${active===t?"active":""}`} key={t} onClick={()=>setActive(t)}>{t}<em>{t==="All"?contacts.length:contacts.filter(c=>t==="New referrals"?c.isReferral:c.status===t).length}</em></button>)}</nav></div>
  <div className="porq-body"><div className="porq-summary"><h2>{query?`Results for “${query}”`:active==="All"?"All queue contacts":`${active} contacts`}</h2><span>{filtered.length} MATCHED</span></div>
   {filtered.length===0?<div className="porq-empty"><Search size={22}/><strong>No contacts found</strong><span>Try another search term or clear the active filters.</span></div>:groups.map(group=>{const list=filtered.filter(c=>c.group===group),isClosed=collapsed[group];return <section className="porq-group" key={group}><button className="porq-grouphead" onClick={()=>setCollapsed(p=>({...p,[group]:!p[group]}))} aria-expanded={!isClosed}><span className="porq-groupicon">{list.some(c=>c.isReferral)?<Stethoscope size={15}/>:<Filter size={15}/>}</span><span><strong>{group}</strong><small>{list.length} contacts · operational queue</small></span><b className="porq-count">{list.length}</b>{isClosed?<ChevronDown size={16}/>:<ChevronUp size={16}/>}</button>{!isClosed&&<div className="porq-list">{list.map(c=><article className="porq-card" key={c.name}><div className="porq-avatar">{initials(c.name)}</div><div><strong>{c.name}</strong><span>{c.phone} · {c.email}</span><span>{c.note} · {c.disposition}{c.isReferral?" · New referral":""}</span></div><div className="porq-meta"><CalendarClock size={13}/>{c.date}</div><div><span>{c.city}</span>{c.attempts>0&&<span className="porq-chip">{c.attempts} attempts</span>}</div><button className="porq-icon" aria-label={`Call ${c.name}`}><PhoneCall size={15}/></button></article>)}</div>}</section>})}
   <div className="porq-footer">Queue synced just now · field-specific search enabled</div>
  </div>
 </section></main>
}