import "./_group.css";
import { useMemo, useState } from "react";
import { AlertTriangle, ArrowDown, ArrowUp, ArrowUpDown, Calendar, CalendarClock, Check, Clock, Mail, MailPlus, MapPin, Megaphone, MessageSquare, MessageSquarePlus, Phone, PhoneCall, PhoneForwarded, PhoneIncoming, Search, Send, Trash2 } from "lucide-react";

type QueueType = "callback" | "email" | "sms";
type Item = {
  id:string; campaignContactId:string; type:QueueType; contactId:string; contactName:string; contactPhone:string; contactEmail:string;
  campaignId:string; campaignName:string; scheduledAt:string; notes:string; status:string; stepName?:string; stepIndex?:number;
  contactType?:string; hasReferral?:boolean; priorityCity?:string; priorityCountryCode?:string; dispositionName?:string;
  callbackStatusListLabel?:string; campaignQueueDisplayMode?:string; isOutsideMission?:boolean; calledBack?:boolean;
  workflowMode?: "status_list"|"disposition"; dispositionChecklistNames?:string[];
};
const plus = (days:number,hour:number) => { const d=new Date(); d.setDate(d.getDate()+days); d.setHours(hour, days < 0 ? 15 : 0, 0, 0); return d.toISOString(); };
const fixtures:Item[] = [
 {id:"sq-101",campaignContactId:"cc-101",type:"callback",contactId:"c-101",contactName:"Mária Kováčová",contactPhone:"+421 903 441 286",contactEmail:"maria.kovacova@example.sk",campaignId:"cmp-ortho",campaignName:"Q2 Orthopedic Referrals",scheduledAt:plus(-1,16),notes:"Asked to call after her clinic closes.",status:"callback_scheduled",stepName:"Follow-up call",stepIndex:2,contactType:"clinic",hasReferral:true,priorityCity:"Bratislava",priorityCountryCode:"SK",workflowMode:"status_list",callbackStatusListLabel:"Callback requested",dispositionName:"Interested"},
 {id:"sq-102",campaignContactId:"cc-102",type:"email",contactId:"c-102",contactName:"Dr. Peter Novák",contactPhone:"+421 911 208 674",contactEmail:"peter.novak@medcentrum.sk",campaignId:"cmp-hosp",campaignName:"Hospital Partners 2024",scheduledAt:plus(0,11),notes:"Send the updated partnership deck.",status:"callback_scheduled",stepName:"Send introduction",stepIndex:1,contactType:"hospital",priorityCity:"Košice",priorityCountryCode:"SK",workflowMode:"disposition",dispositionName:"Materials requested",dispositionChecklistNames:["Pricing attached","Deck approved"]},
 {id:"sq-103",campaignContactId:"cc-103",type:"sms",contactId:"c-103",contactName:"Lucia Horváthová",contactPhone:"+421 905 733 902",contactEmail:"lucia.horvathova@example.com",campaignId:"cmp-patients",campaignName:"Patient Care Check-in",scheduledAt:plus(2,9),notes:"Confirm preferred appointment window.",status:"callback_scheduled",stepName:"Appointment reminder",stepIndex:3,contactType:"customer",priorityCity:"Žilina",priorityCountryCode:"SK",workflowMode:"status_list",callbackStatusListLabel:"Reminder"},
 {id:"sq-104",campaignContactId:"cc-104",type:"callback",contactId:"c-104",contactName:"Ambulancia Nové Mesto",contactPhone:"+421 2 4444 2201",contactEmail:"recepcia@ambulancia.sk",campaignId:"cmp-ortho",campaignName:"Q2 Orthopedic Referrals",scheduledAt:plus(6,14),notes:"",status:"callback_scheduled",stepName:"Decision maker",stepIndex:4,contactType:"clinic",priorityCity:"Nitra",priorityCountryCode:"SK",calledBack:true},
 {id:"sq-105",campaignContactId:"cc-105",type:"email",contactId:"c-105",contactName:"Martin Benko",contactPhone:"+421 948 551 007",contactEmail:"martin.benko@partner.eu",campaignId:"cmp-eu",campaignName:"EU Partner Outreach",scheduledAt:plus(10,10),notes:"",status:"callback_scheduled",contactType:"collaborator",isOutsideMission:true},
 {id:"sq-106",campaignContactId:"cc-106",type:"sms",contactId:"c-106",contactName:"Ján Šimek",contactPhone:"+421 907 882 133",contactEmail:"jan.simek@example.sk",campaignId:"cmp-patients",campaignName:"Patient Care Check-in",scheduledAt:plus(1,15),notes:"",status:"callback_scheduled",stepName:"Check-in",stepIndex:2,contactType:"customer",priorityCity:"Prešov",priorityCountryCode:"SK"},
];
const fmtDate=(s:string)=>new Intl.DateTimeFormat("sk-SK",{day:"numeric",month:"numeric",year:"numeric"}).format(new Date(s));
const fmtTime=(s:string)=>new Intl.DateTimeFormat("sk-SK",{hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(s));
const typeLabel=(t:QueueType)=>t==="callback"?"Callback":t==="email"?"Email":"SMS";
const TypeIcon=({type}:{type:QueueType})=>type==="callback"?<PhoneForwarded className="h-3.5 w-3.5"/>:type==="email"?<MailPlus className="h-3.5 w-3.5"/>:<MessageSquarePlus className="h-3.5 w-3.5"/>;

function Reschedule({item,onSave}:{item:Item;onSave:(id:string,v:string)=>void}) {
 const [open,setOpen]=useState(false); const initial=item.scheduledAt.slice(0,16); const [value,setValue]=useState(initial);
 return <div className="relative"><button className="icon-btn" title="Reschedule" data-testid={`btn-scheduled-reschedule-${item.id}`} onClick={()=>{setValue(item.scheduledAt.slice(0,16));setOpen(!open)}}><CalendarClock className="h-3.5 w-3.5"/></button>{open&&<div className="popover"><div className="flex items-start gap-2 mb-2"><div className="pop-icon"><CalendarClock className="h-3.5 w-3.5"/></div><div><b>Reschedule</b><small>{item.contactName}</small></div></div><label className="text-[10px] text-slate-500">Date and time</label><input type="datetime-local" value={value} min={new Date().toISOString().slice(0,16)} onChange={e=>setValue(e.target.value)} className="datetime"/>{item.notes&&<div className="note"><MessageSquare className="h-3 w-3 shrink-0"/>{item.notes}</div>}<div className="pop-actions"><button onClick={()=>setOpen(false)}>Cancel</button><button className="ok" onClick={()=>{onSave(item.id,new Date(value).toISOString());setOpen(false)}}><Check className="h-3 w-3"/> OK</button></div></div>}</div>
}

function Badges({item}:{item:Item}) { return <>{item.hasReferral&&<span className="pill referral">Referral</span>}{item.priorityCity&&<span className="pill city"><MapPin className="h-2.5 w-2.5"/>{item.priorityCity}, {item.priorityCountryCode}</span>}</>; }

export function Current() {
 const [items,setItems]=useState(fixtures); const [q,setQ]=useState(""); const [type,setType]=useState<"all"|QueueType>("all"); const [bucket,setBucket]=useState("all"); const [sort,setSort]=useState<"date"|"name"|"campaign">("date"); const [desc,setDesc]=useState(false); const [mine,setMine]=useState(false);
 const now=Date.now(), day=86400000;
 const getBucket=(s:string)=>{const t=new Date(s).getTime();if(t<now)return"overdue";const n=Math.floor((t-now)/day);return n===0?"today":n<7?"thisWeek":n<14?"nextWeek":"later"};
 const counts=useMemo(()=>{const x:any={overdue:0,today:0,thisWeek:0,nextWeek:0,later:0,callback:0,email:0,sms:0};items.forEach(i=>{x[getBucket(i.scheduledAt)]++;x[i.type]++});return x},[items]);
 const visible=useMemo(()=>items.filter(i=>(type==="all"||i.type===type)&&(bucket==="all"||getBucket(i.scheduledAt)===bucket)&&(!mine||i.id!=="sq-105")&&(!q||[i.contactName,i.contactPhone,i.contactEmail,i.campaignName,i.notes].join(" ").toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>{const av=sort==="date"?+new Date(a.scheduledAt):sort==="name"?a.contactName.localeCompare(b.contactName):a.campaignName.localeCompare(b.campaignName);const bv=sort==="date"?+new Date(b.scheduledAt):sort==="name"?b.contactName.localeCompare(a.contactName):b.campaignName.localeCompare(a.campaignName);return (sort==="date"?av-bv:av)- (sort==="date"?bv-av:0)}),[items,q,type,bucket,sort,desc,mine]);
 const toggleSort=(s:any)=>{if(sort===s)setDesc(!desc);else{setSort(s);setDesc(false)}};
 const sorted=desc?[...visible].reverse():visible;
 const cancel=(id:string)=>setItems(v=>v.filter(i=>i.id!==id));
 const openContact=(i:Item,channel:string)=>alert(`${channel==="phone"?"Opening call":"Opening "+channel} for ${i.contactName}`);
 const filters=[["all","All",items.length,CalendarClock],["overdue","Overdue",counts.overdue,AlertTriangle],["today","Today",counts.today,Clock],["thisWeek","This week",counts.thisWeek,Calendar],["nextWeek","Next week",counts.nextWeek,Calendar],["later","Later",counts.later,Calendar]];
 return <main className="queue-shell"><header><div className="title-icon"><CalendarClock className="h-4 w-4"/></div><div><h1>Scheduled queue <span>{items.length}</span></h1><p>{counts.overdue>0&&<strong>{counts.overdue} overdue</strong>}{counts.overdue>0&&counts.today>0&&" · "}{counts.today>0&&`${counts.today} today`}</p></div><label className="mine"><input type="checkbox" checked={mine} onChange={e=>setMine(e.target.checked)}/> Only assigned to me</label></header>
 <section className="toolbar"><div className="search"><Search className="h-3.5 w-3.5"/><input placeholder="Search..." value={q} onChange={e=>setQ(e.target.value)} data-testid="input-scheduled-search"/></div>{(["date","name","campaign"] as const).map(s=><button className={"sort "+(sort===s?"active":"")} onClick={()=>toggleSort(s)} key={s}>{s==="date"?"Date":s==="name"?"Name":"Campaign"}{sort===s?(desc?<ArrowDown/>:<ArrowUp/>):<ArrowUpDown/>}</button>)}</section>
 <div className="filters"><b>DATE</b>{filters.map(([k,label,c,Icon]:any)=><button className={bucket===k?"filter active":"filter"} onClick={()=>setBucket(k)} key={k}><Icon/><span>{label}</span><em>{c}</em></button>)}<i/><b>TYPE</b>{(["all","callback","email","sms"] as const).map(k=><button className={type===k?"filter active":"filter"} onClick={()=>setType(k)} key={k}>{k==="all"?<CalendarClock/>:<TypeIcon type={k}/>}<span>{k==="all"?"All":k==="callback"?"Calls":k==="email"?"Emails":"SMS"}</span><em>{k==="all"?items.length:counts[k]}</em></button>)}</div>
 <div className="summary"><span><strong>{sorted.length}</strong> / <strong>{items.length}</strong> total</span><span>● Scheduled queue</span></div><div className="columns"><span>CONTACT</span><span>DATE</span><span>STEP / STATUS</span><span>CAMPAIGN</span><span>ACTIONS</span></div>
 <div className="rows">{sorted.length===0?<div className="empty"><CalendarClock/><p>{items.length?"No matching scheduled items":"No scheduled items"}</p><button onClick={()=>{setQ("");setType("all");setBucket("all")}}>All</button></div>:sorted.map((i,idx)=>{const overdue=getBucket(i.scheduledAt)==="overdue";return <article className={"row "+(overdue?"overdue":"")} key={i.id} data-testid={`scheduled-item-${i.id}`}><div className="contact"><div className={"avatar "+(overdue?"warn":i.type)}>{overdue?<AlertTriangle/>:<TypeIcon type={i.type}/>}</div><div className="contact-info"><div className="name-line"><button className="name" onClick={()=>openContact(i,i.type==="callback"?"phone":i.type)}>{i.contactName}</button><span className="tag">{typeLabel(i.type)}</span>{overdue&&<span className="overdue-tag"><AlertTriangle/> Overdue</span>}<Badges item={i}/></div><div className="details"><span><Phone/>{i.contactPhone}</span><span><Mail/>{i.contactEmail}</span></div></div></div>{i.calledBack?<span className="done"><Check/> Callback done</span>:<div className={"date "+(overdue?"red":"")}><span><Calendar/>{fmtDate(i.scheduledAt)}</span><small><Clock/>{fmtTime(i.scheduledAt)}</small></div>}<div className="step">{i.callbackStatusListLabel?<><span className="status blue">{i.callbackStatusListLabel}</span><span className="status sub">↳ {i.dispositionName||typeLabel(i.type)}</span></>:i.dispositionName?<><span className="status purple">{i.dispositionName}</span>{i.dispositionChecklistNames?.map(n=><span className="status sub purple-sub" key={n}>↳ {n}</span>)}</>:i.stepName?<span className="step-label">{i.stepIndex}. {i.stepName}</span>:<span>—</span>}</div><div className="campaign">{i.isOutsideMission?<span className="outside"><PhoneIncoming/> Outside mission</span>:<span><Megaphone/>{i.campaignName}</span>}</div><div className="actions">{i.type==="callback"?<button className="icon-btn blue-btn" title="Call now" onClick={()=>openContact(i,"phone")}><PhoneCall/></button>:<button className="icon-btn green-btn" title="Send now" onClick={()=>openContact(i,i.type)}><Send/></button>}<Reschedule item={i} onSave={(id,v)=>setItems(xs=>xs.map(x=>x.id===id?{...x,scheduledAt:v}:x))}/><button className="icon-btn cancel-btn" title="Cancel" onClick={()=>cancel(i.id)}><Trash2/></button></div></article>})}</div><footer>{sorted.length} / {items.length} total {bucket!=="all"&&` · ${filters.find(f=>f[0]===bucket)?.[1]}`}{type!=="all"&&` · ${typeLabel(type)}`}</footer></main>
}