export const germanHospitals = [
  // UNIVERSITÄTSKLINIKEN (University Hospitals)
  {
    name: "Charité - Universitätsmedizin Berlin",
    address: "Charitéplatz 1",
    city: "Berlin",
    postalCode: "10117",
    countryCode: "DE",
    phone: "+49 30 450 50",
    email: "info@charite.de",
    website: "www.charite.de",
    latitude: "52.5256",
    longitude: "13.3785",
    category: "university",
  },
  {
    name: "Charité Campus Virchow-Klinikum",
    address: "Augustenburger Platz 1",
    city: "Berlin",
    postalCode: "13353",
    countryCode: "DE",
    phone: "+49 30 450 50",
    email: "info@charite.de",
    website: "www.charite.de",
    latitude: "52.5422",
    longitude: "13.3431",
    category: "university",
  },
  {
    name: "Charité Campus Benjamin Franklin",
    address: "Hindenburgdamm 30",
    city: "Berlin",
    postalCode: "12203",
    countryCode: "DE",
    phone: "+49 30 450 50",
    email: "info@charite.de",
    website: "www.charite.de",
    latitude: "52.4419",
    longitude: "13.3169",
    category: "university",
  },
  {
    name: "Universitätsklinikum Hamburg-Eppendorf",
    address: "Martinistraße 52",
    city: "Hamburg",
    postalCode: "20246",
    countryCode: "DE",
    phone: "+49 40 7410 0",
    email: "info@uke.de",
    website: "www.uke.de",
    latitude: "53.5900",
    longitude: "9.9767",
    category: "university",
  },
  {
    name: "Universitätsklinikum München - LMU Klinikum",
    address: "Marchioninistraße 15",
    city: "München",
    postalCode: "81377",
    countryCode: "DE",
    phone: "+49 89 4400 0",
    email: "info@klinikum.uni-muenchen.de",
    website: "www.klinikum.uni-muenchen.de",
    latitude: "48.1103",
    longitude: "11.4647",
    category: "university",
  },
  {
    name: "Klinikum rechts der Isar der TU München",
    address: "Ismaninger Straße 22",
    city: "München",
    postalCode: "81675",
    countryCode: "DE",
    phone: "+49 89 4140 0",
    email: "info@mri.tum.de",
    website: "www.mri.tum.de",
    latitude: "48.1378",
    longitude: "11.5997",
    category: "university",
  },
  {
    name: "Universitätsklinikum Frankfurt",
    address: "Theodor-Stern-Kai 7",
    city: "Frankfurt am Main",
    postalCode: "60590",
    countryCode: "DE",
    phone: "+49 69 6301 0",
    email: "info@unimedizin-ffm.de",
    website: "www.unimedizin-ffm.de",
    latitude: "50.0939",
    longitude: "8.6650",
    category: "university",
  },
  {
    name: "Universitätsklinikum Köln",
    address: "Kerpener Straße 62",
    city: "Köln",
    postalCode: "50937",
    countryCode: "DE",
    phone: "+49 221 478 0",
    email: "info@uk-koeln.de",
    website: "www.uk-koeln.de",
    latitude: "50.9247",
    longitude: "6.9178",
    category: "university",
  },
  {
    name: "Universitätsklinikum Düsseldorf",
    address: "Moorenstraße 5",
    city: "Düsseldorf",
    postalCode: "40225",
    countryCode: "DE",
    phone: "+49 211 811 0",
    email: "info@uniklinik-duesseldorf.de",
    website: "www.uniklinik-duesseldorf.de",
    latitude: "51.1936",
    longitude: "6.7897",
    category: "university",
  },
  {
    name: "Universitätsklinikum Heidelberg",
    address: "Im Neuenheimer Feld 672",
    city: "Heidelberg",
    postalCode: "69120",
    countryCode: "DE",
    phone: "+49 6221 56 0",
    email: "info@med.uni-heidelberg.de",
    website: "www.klinikum.uni-heidelberg.de",
    latitude: "49.4178",
    longitude: "8.6694",
    category: "university",
  },
  {
    name: "Universitätsklinikum Tübingen",
    address: "Geissweg 3",
    city: "Tübingen",
    postalCode: "72076",
    countryCode: "DE",
    phone: "+49 7071 29 0",
    email: "info@med.uni-tuebingen.de",
    website: "www.medizin.uni-tuebingen.de",
    latitude: "48.5333",
    longitude: "9.0333",
    category: "university",
  },
  {
    name: "Universitätsklinikum Freiburg",
    address: "Hugstetter Straße 55",
    city: "Freiburg",
    postalCode: "79106",
    countryCode: "DE",
    phone: "+49 761 270 0",
    email: "info@uniklinik-freiburg.de",
    website: "www.uniklinik-freiburg.de",
    latitude: "48.0028",
    longitude: "7.8411",
    category: "university",
  },
  {
    name: "Universitätsklinikum Leipzig",
    address: "Liebigstraße 20",
    city: "Leipzig",
    postalCode: "04103",
    countryCode: "DE",
    phone: "+49 341 97 109",
    email: "info@medizin.uni-leipzig.de",
    website: "www.uniklinikum-leipzig.de",
    latitude: "51.3333",
    longitude: "12.3833",
    category: "university",
  },
  {
    name: "Universitätsklinikum Dresden",
    address: "Fetscherstraße 74",
    city: "Dresden",
    postalCode: "01307",
    countryCode: "DE",
    phone: "+49 351 458 0",
    email: "info@uniklinikum-dresden.de",
    website: "www.uniklinikum-dresden.de",
    latitude: "51.0575",
    longitude: "13.7678",
    category: "university",
  },
  {
    name: "Universitätsklinikum Jena",
    address: "Am Klinikum 1",
    city: "Jena",
    postalCode: "07747",
    countryCode: "DE",
    phone: "+49 3641 9 0",
    email: "info@med.uni-jena.de",
    website: "www.uniklinikum-jena.de",
    latitude: "50.9167",
    longitude: "11.5833",
    category: "university",
  },
  {
    name: "Universitätsklinikum Göttingen",
    address: "Robert-Koch-Straße 40",
    city: "Göttingen",
    postalCode: "37075",
    countryCode: "DE",
    phone: "+49 551 39 0",
    email: "info@med.uni-goettingen.de",
    website: "www.umg.eu",
    latitude: "51.5333",
    longitude: "9.9333",
    category: "university",
  },
  {
    name: "Universitätsklinikum Bonn",
    address: "Venusberg-Campus 1",
    city: "Bonn",
    postalCode: "53127",
    countryCode: "DE",
    phone: "+49 228 287 0",
    email: "info@ukbonn.de",
    website: "www.ukbonn.de",
    latitude: "50.6944",
    longitude: "7.0903",
    category: "university",
  },
  {
    name: "Universitätsklinikum Münster",
    address: "Albert-Schweitzer-Campus 1",
    city: "Münster",
    postalCode: "48149",
    countryCode: "DE",
    phone: "+49 251 83 0",
    email: "info@ukmuenster.de",
    website: "www.ukmuenster.de",
    latitude: "51.9606",
    longitude: "7.5981",
    category: "university",
  },
  {
    name: "Universitätsklinikum Essen",
    address: "Hufelandstraße 55",
    city: "Essen",
    postalCode: "45147",
    countryCode: "DE",
    phone: "+49 201 723 0",
    email: "info@uk-essen.de",
    website: "www.uk-essen.de",
    latitude: "51.4350",
    longitude: "6.9892",
    category: "university",
  },
  {
    name: "Universitätsklinikum Aachen",
    address: "Pauwelsstraße 30",
    city: "Aachen",
    postalCode: "52074",
    countryCode: "DE",
    phone: "+49 241 80 0",
    email: "info@ukaachen.de",
    website: "www.ukaachen.de",
    latitude: "50.7678",
    longitude: "6.0472",
    category: "university",
  },
  // KOMMUNALE KLINIKEN (Municipal Hospitals)
  {
    name: "Klinikum Stuttgart",
    address: "Kriegsbergstraße 60",
    city: "Stuttgart",
    postalCode: "70174",
    countryCode: "DE",
    phone: "+49 711 278 0",
    email: "info@klinikum-stuttgart.de",
    website: "www.klinikum-stuttgart.de",
    latitude: "48.7822",
    longitude: "9.1697",
    category: "regional",
  },
  {
    name: "Städtisches Klinikum Karlsruhe",
    address: "Moltkestraße 90",
    city: "Karlsruhe",
    postalCode: "76133",
    countryCode: "DE",
    phone: "+49 721 974 0",
    email: "info@klinikum-karlsruhe.de",
    website: "www.klinikum-karlsruhe.de",
    latitude: "49.0167",
    longitude: "8.3833",
    category: "regional",
  },
  {
    name: "Klinikum Nürnberg",
    address: "Prof.-Ernst-Nathan-Straße 1",
    city: "Nürnberg",
    postalCode: "90419",
    countryCode: "DE",
    phone: "+49 911 398 0",
    email: "info@klinikum-nuernberg.de",
    website: "www.klinikum-nuernberg.de",
    latitude: "49.4628",
    longitude: "11.0536",
    category: "regional",
  },
  {
    name: "Klinikum Augsburg",
    address: "Stenglinstraße 2",
    city: "Augsburg",
    postalCode: "86156",
    countryCode: "DE",
    phone: "+49 821 400 01",
    email: "info@uk-augsburg.de",
    website: "www.uk-augsburg.de",
    latitude: "48.3917",
    longitude: "10.8781",
    category: "regional",
  },
  {
    name: "Klinikum Bremen-Mitte",
    address: "St.-Jürgen-Straße 1",
    city: "Bremen",
    postalCode: "28177",
    countryCode: "DE",
    phone: "+49 421 497 0",
    email: "info@klinikum-bremen-mitte.de",
    website: "www.klinikum-bremen-mitte.de",
    latitude: "53.0733",
    longitude: "8.8150",
    category: "regional",
  },
  {
    name: "Klinikum Hannover",
    address: "Carl-Neuberg-Straße 1",
    city: "Hannover",
    postalCode: "30625",
    countryCode: "DE",
    phone: "+49 511 532 0",
    email: "info@mh-hannover.de",
    website: "www.mh-hannover.de",
    latitude: "52.3833",
    longitude: "9.8000",
    category: "university",
  },
  {
    name: "Städtisches Klinikum Braunschweig",
    address: "Freisestraße 9-10",
    city: "Braunschweig",
    postalCode: "38118",
    countryCode: "DE",
    phone: "+49 531 595 0",
    email: "info@klinikum-braunschweig.de",
    website: "www.klinikum-braunschweig.de",
    latitude: "52.2667",
    longitude: "10.5167",
    category: "regional",
  },
  {
    name: "Klinikum Kassel",
    address: "Mönchebergstraße 41-43",
    city: "Kassel",
    postalCode: "34125",
    countryCode: "DE",
    phone: "+49 561 980 0",
    email: "info@klinikum-kassel.de",
    website: "www.klinikum-kassel.de",
    latitude: "51.3167",
    longitude: "9.5000",
    category: "regional",
  },
  {
    name: "Klinikum Dortmund",
    address: "Beurhausstraße 40",
    city: "Dortmund",
    postalCode: "44137",
    countryCode: "DE",
    phone: "+49 231 953 0",
    email: "info@klinikumdo.de",
    website: "www.klinikumdo.de",
    latitude: "51.5167",
    longitude: "7.4667",
    category: "regional",
  },
  {
    name: "Universitätsklinikum Schleswig-Holstein Kiel",
    address: "Arnold-Heller-Straße 3",
    city: "Kiel",
    postalCode: "24105",
    countryCode: "DE",
    phone: "+49 431 500 0",
    email: "info@uksh.de",
    website: "www.uksh.de",
    latitude: "54.3333",
    longitude: "10.1333",
    category: "university",
  },
  {
    name: "Universitätsklinikum Schleswig-Holstein Lübeck",
    address: "Ratzeburger Allee 160",
    city: "Lübeck",
    postalCode: "23538",
    countryCode: "DE",
    phone: "+49 451 500 0",
    email: "info@uksh.de",
    website: "www.uksh.de",
    latitude: "53.8333",
    longitude: "10.6833",
    category: "university",
  },
  {
    name: "Universitätsklinikum Magdeburg",
    address: "Leipziger Straße 44",
    city: "Magdeburg",
    postalCode: "39120",
    countryCode: "DE",
    phone: "+49 391 67 01",
    email: "info@med.uni-magdeburg.de",
    website: "www.klinikum.uni-magdeburg.de",
    latitude: "52.1167",
    longitude: "11.6333",
    category: "university",
  },
  {
    name: "Universitätsklinikum Rostock",
    address: "Ernst-Heydemann-Straße 6",
    city: "Rostock",
    postalCode: "18057",
    countryCode: "DE",
    phone: "+49 381 494 0",
    email: "info@med.uni-rostock.de",
    website: "www.med.uni-rostock.de",
    latitude: "54.0833",
    longitude: "12.1333",
    category: "university",
  },
  {
    name: "Universitätsklinikum Greifswald",
    address: "Fleischmannstraße 8",
    city: "Greifswald",
    postalCode: "17475",
    countryCode: "DE",
    phone: "+49 3834 86 0",
    email: "info@uni-greifswald.de",
    website: "www.medizin.uni-greifswald.de",
    latitude: "54.0917",
    longitude: "13.3833",
    category: "university",
  },
  // PRIVATE KLINIKEN (Private Hospitals)
  {
    name: "Helios Klinikum Berlin-Buch",
    address: "Schwanebecker Chaussee 50",
    city: "Berlin",
    postalCode: "13125",
    countryCode: "DE",
    phone: "+49 30 9401 0",
    email: "info@helios-gesundheit.de",
    website: "www.helios-gesundheit.de",
    latitude: "52.6333",
    longitude: "13.4833",
    category: "private",
  },
  {
    name: "Vivantes Klinikum Neukölln",
    address: "Rudower Straße 48",
    city: "Berlin",
    postalCode: "12351",
    countryCode: "DE",
    phone: "+49 30 130 14 0",
    email: "info@vivantes.de",
    website: "www.vivantes.de",
    latitude: "52.4500",
    longitude: "13.4333",
    category: "private",
  },
  {
    name: "Asklepios Klinik Altona",
    address: "Paul-Ehrlich-Straße 1",
    city: "Hamburg",
    postalCode: "22763",
    countryCode: "DE",
    phone: "+49 40 1818 81 0",
    email: "info@asklepios.com",
    website: "www.asklepios.com",
    latitude: "53.5500",
    longitude: "9.9167",
    category: "private",
  },
  {
    name: "Schön Klinik München Harlaching",
    address: "Harlachinger Straße 51",
    city: "München",
    postalCode: "81547",
    countryCode: "DE",
    phone: "+49 89 6211 0",
    email: "info@schoen-klinik.de",
    website: "www.schoen-klinik.de",
    latitude: "48.0833",
    longitude: "11.5667",
    category: "private",
  },
  {
    name: "Klinikum Sana Berlin-Lichtenberg",
    address: "Fanningerstraße 32",
    city: "Berlin",
    postalCode: "10365",
    countryCode: "DE",
    phone: "+49 30 5518 0",
    email: "info@sana.de",
    website: "www.sana.de",
    latitude: "52.5167",
    longitude: "13.4833",
    category: "private",
  },
  // SPEZIALKLIKEN FÜR FRAUEN UND KINDER (Women's and Children's Hospitals)
  {
    name: "Klinikum Dritter Orden - Frauenklinik",
    address: "Menzinger Straße 44",
    city: "München",
    postalCode: "80638",
    countryCode: "DE",
    phone: "+49 89 1795 0",
    email: "info@dritter-orden.de",
    website: "www.dritter-orden.de",
    latitude: "48.1678",
    longitude: "11.5031",
    category: "specialized",
  },
  {
    name: "Dr. von Haunersches Kinderspital",
    address: "Lindwurmstraße 4",
    city: "München",
    postalCode: "80337",
    countryCode: "DE",
    phone: "+49 89 4400 0",
    email: "info@klinikum.uni-muenchen.de",
    website: "www.klinikum.uni-muenchen.de",
    latitude: "48.1328",
    longitude: "11.5639",
    category: "specialized",
  },
  {
    name: "Universitäts-Kinderspital beider Basel",
    address: "Spitalstrasse 33",
    city: "Basel",
    postalCode: "4056",
    countryCode: "DE",
    phone: "+49 61 704 1212",
    email: "info@ukbb.ch",
    website: "www.ukbb.ch",
    latitude: "47.5614",
    longitude: "7.5811",
    category: "specialized",
  },
];
