export const hungarianHospitals = [
  // EGYETEMI KLINIKÁK (University Hospitals)
  {
    name: "Semmelweis Egyetem - I. Sz. Szülészeti és Nőgyógyászati Klinika",
    address: "Baross utca 27",
    city: "Budapest",
    postalCode: "1088",
    countryCode: "HU",
    phone: "+36 1 266 0473",
    email: "info@noi1.sote.hu",
    website: "www.semmelweis.hu",
    latitude: "47.4897",
    longitude: "19.0722",
    category: "university",
  },
  {
    name: "Semmelweis Egyetem - II. Sz. Szülészeti és Nőgyógyászati Klinika",
    address: "Üllői út 78/a",
    city: "Budapest",
    postalCode: "1082",
    countryCode: "HU",
    phone: "+36 1 210 0285",
    email: "info@noi2.sote.hu",
    website: "www.semmelweis.hu",
    latitude: "47.4808",
    longitude: "19.0833",
    category: "university",
  },
  {
    name: "Semmelweis Egyetem - I. Sz. Gyermekgyógyászati Klinika",
    address: "Bókay János utca 53-54",
    city: "Budapest",
    postalCode: "1083",
    countryCode: "HU",
    phone: "+36 1 334 3186",
    email: "info@gyer1.sote.hu",
    website: "www.semmelweis.hu",
    latitude: "47.4878",
    longitude: "19.0886",
    category: "university",
  },
  {
    name: "Debreceni Egyetem Klinikai Központ - Szülészeti és Nőgyógyászati Klinika",
    address: "Nagyerdei körút 98",
    city: "Debrecen",
    postalCode: "4032",
    countryCode: "HU",
    phone: "+36 52 255 500",
    email: "info@med.unideb.hu",
    website: "www.kenezykorhaz.hu",
    latitude: "47.5569",
    longitude: "21.6250",
    category: "university",
  },
  {
    name: "Szegedi Tudományegyetem - Szülészeti és Nőgyógyászati Klinika",
    address: "Semmelweis utca 1",
    city: "Szeged",
    postalCode: "6725",
    countryCode: "HU",
    phone: "+36 62 545 499",
    email: "info@med.u-szeged.hu",
    website: "www.med.u-szeged.hu",
    latitude: "46.2545",
    longitude: "20.1500",
    category: "university",
  },
  {
    name: "Pécsi Tudományegyetem - Szülészeti és Nőgyógyászati Klinika",
    address: "Édesanyák útja 17",
    city: "Pécs",
    postalCode: "7624",
    countryCode: "HU",
    phone: "+36 72 536 000",
    email: "info@aok.pte.hu",
    website: "www.aok.pte.hu",
    latitude: "46.0722",
    longitude: "18.2328",
    category: "university",
  },
  // ORSZÁGOS INTÉZETEK (National Institutes)
  {
    name: "Országos Onkológiai Intézet",
    address: "Ráth György utca 7-9",
    city: "Budapest",
    postalCode: "1122",
    countryCode: "HU",
    phone: "+36 1 224 8600",
    email: "info@oncol.hu",
    website: "www.oncol.hu",
    latitude: "47.4983",
    longitude: "19.0217",
    category: "specialized",
  },
  {
    name: "Gottsegen György Országos Kardiológiai Intézet",
    address: "Haller utca 29",
    city: "Budapest",
    postalCode: "1096",
    countryCode: "HU",
    phone: "+36 1 215 1220",
    email: "info@kardio.hu",
    website: "www.kardio.hu",
    latitude: "47.4756",
    longitude: "19.0892",
    category: "specialized",
  },
  {
    name: "Heim Pál Országos Gyermekgyógyászati Intézet",
    address: "Üllői út 86",
    city: "Budapest",
    postalCode: "1089",
    countryCode: "HU",
    phone: "+36 1 459 9100",
    email: "info@heimpalkorhaz.hu",
    website: "www.heimpalkorhaz.hu",
    latitude: "47.4769",
    longitude: "19.0889",
    category: "specialized",
  },
  // MEGYEI KÓRHÁZAK (County Hospitals)
  {
    name: "Szent János Kórház és Észak-budai Egyesített Kórházak",
    address: "Diós árok 1-3",
    city: "Budapest",
    postalCode: "1125",
    countryCode: "HU",
    phone: "+36 1 458 4500",
    email: "info@janoskorhaz.hu",
    website: "www.janoskorhaz.hu",
    latitude: "47.5017",
    longitude: "18.9917",
    category: "regional",
  },
  {
    name: "Péterfy Sándor utcai Kórház-Rendelőintézet és Baleseti Központ",
    address: "Péterfy Sándor utca 8-20",
    city: "Budapest",
    postalCode: "1076",
    countryCode: "HU",
    phone: "+36 1 461 4700",
    email: "info@peterfykorhaz.hu",
    website: "www.peterfykorhaz.hu",
    latitude: "47.5072",
    longitude: "19.0750",
    category: "regional",
  },
  {
    name: "Bajcsy-Zsilinszky Kórház és Rendelőintézet",
    address: "Maglódi út 89-91",
    city: "Budapest",
    postalCode: "1106",
    countryCode: "HU",
    phone: "+36 1 432 7500",
    email: "info@bajcsy.hu",
    website: "www.bajcsy.hu",
    latitude: "47.4833",
    longitude: "19.1458",
    category: "regional",
  },
  {
    name: "Jahn Ferenc Dél-pesti Kórház és Rendelőintézet",
    address: "Köves út 1",
    city: "Budapest",
    postalCode: "1204",
    countryCode: "HU",
    phone: "+36 1 289 2400",
    email: "info@jahnkorhaz.hu",
    website: "www.jahnkorhaz.hu",
    latitude: "47.4317",
    longitude: "19.1142",
    category: "regional",
  },
  {
    name: "Uzsoki Utcai Kórház",
    address: "Uzsoki utca 29-41",
    city: "Budapest",
    postalCode: "1145",
    countryCode: "HU",
    phone: "+36 1 467 3700",
    email: "info@uzsoki.hu",
    website: "www.uzsoki.hu",
    latitude: "47.5131",
    longitude: "19.0969",
    category: "regional",
  },
  {
    name: "Borsod-Abaúj-Zemplén Megyei Központi Kórház és Egyetemi Oktatókórház",
    address: "Szentpéteri kapu 72-76",
    city: "Miskolc",
    postalCode: "3526",
    countryCode: "HU",
    phone: "+36 46 515 200",
    email: "info@bazmkorhaz.hu",
    website: "www.bazmkorhaz.hu",
    latitude: "48.1111",
    longitude: "20.7978",
    category: "regional",
  },
  {
    name: "Győr-Moson-Sopron Megyei Petz Aladár Egyetemi Oktató Kórház",
    address: "Vasvári Pál utca 2-4",
    city: "Győr",
    postalCode: "9024",
    countryCode: "HU",
    phone: "+36 96 418 244",
    email: "info@pfrkorhaz.hu",
    website: "www.pfrkorhaz.hu",
    latitude: "47.6847",
    longitude: "17.6328",
    category: "regional",
  },
  {
    name: "Fejér Megyei Szent György Egyetemi Oktató Kórház",
    address: "Seregélyesi út 3",
    city: "Székesfehérvár",
    postalCode: "8000",
    countryCode: "HU",
    phone: "+36 22 535 500",
    email: "info@fmkorhaz.hu",
    website: "www.fmkorhaz.hu",
    latitude: "47.1856",
    longitude: "18.4219",
    category: "regional",
  },
  {
    name: "Szabolcs-Szatmár-Bereg Megyei Kórházak és Egyetemi Oktatókórház",
    address: "Szent István utca 68",
    city: "Nyíregyháza",
    postalCode: "4400",
    countryCode: "HU",
    phone: "+36 42 599 700",
    email: "info@szszbmk.hu",
    website: "www.szszbmk.hu",
    latitude: "47.9472",
    longitude: "21.7167",
    category: "regional",
  },
  {
    name: "Somogy Megyei Kaposi Mór Oktató Kórház",
    address: "Tallián Gyula utca 20-32",
    city: "Kaposvár",
    postalCode: "7400",
    countryCode: "HU",
    phone: "+36 82 501 000",
    email: "info@kfrkorhaz.hu",
    website: "www.kfrkorhaz.hu",
    latitude: "46.3639",
    longitude: "17.7844",
    category: "regional",
  },
  {
    name: "Zala Megyei Szent Rafael Kórház",
    address: "Zrínyi Miklós utca 1",
    city: "Zalaegerszeg",
    postalCode: "8900",
    countryCode: "HU",
    phone: "+36 92 507 500",
    email: "info@zmkorhaz.hu",
    website: "www.zmkorhaz.hu",
    latitude: "46.8403",
    longitude: "16.8519",
    category: "regional",
  },
  {
    name: "Veszprém Megyei Csolnoky Ferenc Kórház",
    address: "Kórház utca 1",
    city: "Veszprém",
    postalCode: "8200",
    countryCode: "HU",
    phone: "+36 88 556 000",
    email: "info@vmkorhaz.hu",
    website: "www.vmkorhaz.hu",
    latitude: "47.0939",
    longitude: "17.9086",
    category: "regional",
  },
  {
    name: "Békés Megyei Központi Kórház",
    address: "Semmelweis utca 1",
    city: "Gyula",
    postalCode: "5700",
    countryCode: "HU",
    phone: "+36 66 526 526",
    email: "info@bekesmkorhaz.hu",
    website: "www.bekesmkorhaz.hu",
    latitude: "46.6444",
    longitude: "21.2833",
    category: "regional",
  },
  {
    name: "Jász-Nagykun-Szolnok Megyei Hetényi Géza Kórház-Rendelőintézet",
    address: "Tószegi út 21",
    city: "Szolnok",
    postalCode: "5000",
    countryCode: "HU",
    phone: "+36 56 503 603",
    email: "info@hetenyikorhaz.hu",
    website: "www.hetenyikorhaz.hu",
    latitude: "47.1744",
    longitude: "20.1833",
    category: "regional",
  },
  {
    name: "Tolna Megyei Balassa János Kórház",
    address: "Béri Balogh Ádám utca 5-7",
    city: "Szekszárd",
    postalCode: "7100",
    countryCode: "HU",
    phone: "+36 74 501 900",
    email: "info@tmkorhaz.hu",
    website: "www.tmkorhaz.hu",
    latitude: "46.3478",
    longitude: "18.7094",
    category: "regional",
  },
  {
    name: "Nógrád Megyei Kórház",
    address: "Füleki út 54-56",
    city: "Salgótarján",
    postalCode: "3100",
    countryCode: "HU",
    phone: "+36 32 512 300",
    email: "info@nmkorhaz.hu",
    website: "www.nmkorhaz.hu",
    latitude: "48.1072",
    longitude: "19.8000",
    category: "regional",
  },
  {
    name: "Heves Megyei Markhot Ferenc Oktatókórház és Rendelőintézet",
    address: "Széchenyi utca 27-29",
    city: "Eger",
    postalCode: "3300",
    countryCode: "HU",
    phone: "+36 36 411 444",
    email: "info@mfrkorhaz.hu",
    website: "www.mfrkorhaz.hu",
    latitude: "47.9006",
    longitude: "20.3772",
    category: "regional",
  },
  {
    name: "Vas Megyei Markusovszky Egyetemi Oktatókórház",
    address: "Markusovszky Lajos utca 5",
    city: "Szombathely",
    postalCode: "9700",
    countryCode: "HU",
    phone: "+36 94 515 100",
    email: "info@markusovszky.hu",
    website: "www.markusovszky.hu",
    latitude: "47.2356",
    longitude: "16.6183",
    category: "regional",
  },
  {
    name: "Csongrád Megyei Dr. Bugyi István Kórház",
    address: "Felszabadulás útja 73",
    city: "Szentes",
    postalCode: "6600",
    countryCode: "HU",
    phone: "+36 63 561 700",
    email: "info@csmkorhaz.hu",
    website: "www.csmkorhaz.hu",
    latitude: "46.6547",
    longitude: "20.2608",
    category: "regional",
  },
  {
    name: "Hajdú-Bihar Megyei Kenézy Gyula Kórház",
    address: "Bartók Béla út 2-26",
    city: "Debrecen",
    postalCode: "4031",
    countryCode: "HU",
    phone: "+36 52 511 777",
    email: "info@kenezykorhaz.hu",
    website: "www.kenezykorhaz.hu",
    latitude: "47.5344",
    longitude: "21.6267",
    category: "regional",
  },
  // MAGÁNKÓRHÁZAK (Private Hospitals)
  {
    name: "Duna Medical Center",
    address: "Lechner Ödön fasor 7",
    city: "Budapest",
    postalCode: "1095",
    countryCode: "HU",
    phone: "+36 1 790 7070",
    email: "info@dunamedical.hu",
    website: "www.dunamedical.hu",
    latitude: "47.4739",
    longitude: "19.0708",
    category: "private",
  },
  {
    name: "Róbert Károly Magánkórház",
    address: "Róbert Károly körút 82-84",
    city: "Budapest",
    postalCode: "1134",
    countryCode: "HU",
    phone: "+36 1 700 7000",
    email: "info@rkk.hu",
    website: "www.rkk.hu",
    latitude: "47.5208",
    longitude: "19.0686",
    category: "private",
  },
  {
    name: "Medicover Kórház",
    address: "Vérmező út 8",
    city: "Budapest",
    postalCode: "1012",
    countryCode: "HU",
    phone: "+36 1 465 3100",
    email: "info@medicover.hu",
    website: "www.medicover.hu",
    latitude: "47.5019",
    longitude: "19.0303",
    category: "private",
  },
  {
    name: "Dr. Rose Magánkórház",
    address: "Pasaréti út 59-67",
    city: "Budapest",
    postalCode: "1026",
    countryCode: "HU",
    phone: "+36 1 391 8900",
    email: "info@drrose.hu",
    website: "www.drrose.hu",
    latitude: "47.5247",
    longitude: "18.9814",
    category: "private",
  },
  // VÁROSI KÓRHÁZAK (City Hospitals)
  {
    name: "Orosházi Kórház",
    address: "Könd utca 59",
    city: "Orosháza",
    postalCode: "5900",
    countryCode: "HU",
    phone: "+36 68 311 166",
    email: "info@oroshazakorhaz.hu",
    website: "www.oroshazakorhaz.hu",
    latitude: "46.5672",
    longitude: "20.6639",
    category: "general",
  },
  {
    name: "Mezőtúri Kórház és Rendelőintézet",
    address: "Mező Imre körút 2",
    city: "Mezőtúr",
    postalCode: "5400",
    countryCode: "HU",
    phone: "+36 56 350 333",
    email: "info@mezoturkorhaz.hu",
    website: "www.mezoturkorhaz.hu",
    latitude: "47.0008",
    longitude: "20.6278",
    category: "general",
  },
  {
    name: "Mátrai Gyógyintézet",
    address: "Kékesi út 1",
    city: "Mátraháza",
    postalCode: "3233",
    countryCode: "HU",
    phone: "+36 37 574 000",
    email: "info@matrai.hu",
    website: "www.matrai.hu",
    latitude: "47.8653",
    longitude: "19.9847",
    category: "specialized",
  },
  {
    name: "Kátai Gábor Kórház",
    address: "Puskin tér 1",
    city: "Karcag",
    postalCode: "5300",
    countryCode: "HU",
    phone: "+36 59 500 300",
    email: "info@kataikorhaz.hu",
    website: "www.kataikorhaz.hu",
    latitude: "47.3136",
    longitude: "20.9214",
    category: "general",
  },
  {
    name: "Mohács Városi Kórház",
    address: "Szabadság utca 39",
    city: "Mohács",
    postalCode: "7700",
    countryCode: "HU",
    phone: "+36 69 300 200",
    email: "info@mohacskorhaz.hu",
    website: "www.mohacskorhaz.hu",
    latitude: "45.9939",
    longitude: "18.6844",
    category: "general",
  },
  {
    name: "Szigetvári Kórház",
    address: "Szent István ltp. 7",
    city: "Szigetvár",
    postalCode: "7900",
    countryCode: "HU",
    phone: "+36 73 510 430",
    email: "info@szigetvarkorhaz.hu",
    website: "www.szigetvarkorhaz.hu",
    latitude: "46.0489",
    longitude: "17.8003",
    category: "general",
  },
  {
    name: "Sátoraljaújhelyi Erzsébet Kórház",
    address: "Mártírok útja 30",
    city: "Sátoraljaújhely",
    postalCode: "3980",
    countryCode: "HU",
    phone: "+36 47 323 133",
    email: "info@saukorhaz.hu",
    website: "www.saukorhaz.hu",
    latitude: "48.3944",
    longitude: "21.6536",
    category: "general",
  },
  {
    name: "Siófok Város Kórház-Rendelőintézet",
    address: "Semmelweis utca 1",
    city: "Siófok",
    postalCode: "8600",
    countryCode: "HU",
    phone: "+36 84 501 900",
    email: "info@siofokkorhaz.hu",
    website: "www.siofokkorhaz.hu",
    latitude: "46.9042",
    longitude: "18.0508",
    category: "general",
  },
  {
    name: "Nagyatád Város Kórháza",
    address: "Szent Imre utca 2",
    city: "Nagyatád",
    postalCode: "7500",
    countryCode: "HU",
    phone: "+36 82 404 700",
    email: "info@nagyatadkorhaz.hu",
    website: "www.nagyatadkorhaz.hu",
    latitude: "46.2294",
    longitude: "17.3567",
    category: "general",
  },
  {
    name: "Dunaújvárosi Szent Pantaleon Kórház",
    address: "Korányi Sándor utca 4-6",
    city: "Dunaújváros",
    postalCode: "2400",
    countryCode: "HU",
    phone: "+36 25 512 600",
    email: "info@pantaleon.hu",
    website: "www.pantaleon.hu",
    latitude: "46.9792",
    longitude: "18.9233",
    category: "general",
  },
  {
    name: "Tatabányai Szent Borbála Kórház",
    address: "Dózsa György út 77",
    city: "Tatabánya",
    postalCode: "2800",
    countryCode: "HU",
    phone: "+36 34 515 700",
    email: "info@tbkorhaz.hu",
    website: "www.tbkorhaz.hu",
    latitude: "47.5856",
    longitude: "18.3919",
    category: "regional",
  },
  {
    name: "Esztergomi Vaszary Kolos Kórház",
    address: "Petőfi Sándor utca 26-28",
    city: "Esztergom",
    postalCode: "2500",
    countryCode: "HU",
    phone: "+36 33 542 300",
    email: "info@eskorhaz.hu",
    website: "www.eskorhaz.hu",
    latitude: "47.7922",
    longitude: "18.7383",
    category: "general",
  },
  {
    name: "Kiskunhalasi Semmelweis Kórház",
    address: "Dr. Monszpart László utca 1",
    city: "Kiskunhalas",
    postalCode: "6400",
    countryCode: "HU",
    phone: "+36 77 503 000",
    email: "info@kiskhalas.hu",
    website: "www.kiskhalas.hu",
    latitude: "46.4314",
    longitude: "19.4856",
    category: "general",
  },
  {
    name: "Kecskeméti Bács-Kiskun Megyei Kórház",
    address: "Nyíri út 38",
    city: "Kecskemét",
    postalCode: "6000",
    countryCode: "HU",
    phone: "+36 76 516 700",
    email: "info@kmk.hu",
    website: "www.kmk.hu",
    latitude: "46.9058",
    longitude: "19.7042",
    category: "regional",
  },
];
