export const italianHospitals = [
  // POLICLINICI UNIVERSITARI (University Hospitals)
  {
    name: "Policlinico Umberto I",
    address: "Viale del Policlinico 155",
    city: "Roma",
    postalCode: "00161",
    countryCode: "IT",
    phone: "+39 06 49971",
    email: "info@policlinicoumberto1.it",
    website: "www.policlinicoumberto1.it",
    latitude: "41.9053",
    longitude: "12.5094",
    category: "university",
  },
  {
    name: "Policlinico Agostino Gemelli",
    address: "Largo Agostino Gemelli 8",
    city: "Roma",
    postalCode: "00168",
    countryCode: "IT",
    phone: "+39 06 30151",
    email: "info@policlinicogemelli.it",
    website: "www.policlinicogemelli.it",
    latitude: "41.9300",
    longitude: "12.4267",
    category: "university",
  },
  {
    name: "Ospedale San Raffaele",
    address: "Via Olgettina 60",
    city: "Milano",
    postalCode: "20132",
    countryCode: "IT",
    phone: "+39 02 26431",
    email: "info@hsr.it",
    website: "www.hsr.it",
    latitude: "45.5050",
    longitude: "9.2644",
    category: "university",
  },
  {
    name: "Policlinico di Milano",
    address: "Via Francesco Sforza 35",
    city: "Milano",
    postalCode: "20122",
    countryCode: "IT",
    phone: "+39 02 55031",
    email: "info@policlinico.mi.it",
    website: "www.policlinico.mi.it",
    latitude: "45.4594",
    longitude: "9.1969",
    category: "university",
  },
  {
    name: "Ospedale Maggiore Policlinico",
    address: "Via Francesco Sforza 28",
    city: "Milano",
    postalCode: "20122",
    countryCode: "IT",
    phone: "+39 02 5503 1",
    email: "info@policlinico.mi.it",
    website: "www.policlinico.mi.it",
    latitude: "45.4600",
    longitude: "9.1958",
    category: "university",
  },
  {
    name: "Policlinico Sant'Orsola-Malpighi",
    address: "Via Pietro Albertoni 15",
    city: "Bologna",
    postalCode: "40138",
    countryCode: "IT",
    phone: "+39 051 214 1111",
    email: "info@aosp.bo.it",
    website: "www.aosp.bo.it",
    latitude: "44.4897",
    longitude: "11.3675",
    category: "university",
  },
  {
    name: "Azienda Ospedaliero-Universitaria Careggi",
    address: "Largo Giovanni Alessandro Brambilla 3",
    city: "Firenze",
    postalCode: "50134",
    countryCode: "IT",
    phone: "+39 055 794111",
    email: "info@aou-careggi.toscana.it",
    website: "www.aou-careggi.toscana.it",
    latitude: "43.8003",
    longitude: "11.2539",
    category: "university",
  },
  {
    name: "Policlinico Federico II",
    address: "Via Sergio Pansini 5",
    city: "Napoli",
    postalCode: "80131",
    countryCode: "IT",
    phone: "+39 081 7461111",
    email: "info@policlinico.unina.it",
    website: "www.policlinico.unina.it",
    latitude: "40.8553",
    longitude: "14.2222",
    category: "university",
  },
  {
    name: "Azienda Ospedaliero-Universitaria Pisana",
    address: "Via Roma 67",
    city: "Pisa",
    postalCode: "56126",
    countryCode: "IT",
    phone: "+39 050 992111",
    email: "info@ao-pisa.toscana.it",
    website: "www.ao-pisa.toscana.it",
    latitude: "43.7167",
    longitude: "10.4000",
    category: "university",
  },
  {
    name: "Policlinico Tor Vergata",
    address: "Viale Oxford 81",
    city: "Roma",
    postalCode: "00133",
    countryCode: "IT",
    phone: "+39 06 20901",
    email: "info@ptvonline.it",
    website: "www.ptvonline.it",
    latitude: "41.8533",
    longitude: "12.6200",
    category: "university",
  },
  {
    name: "Azienda Ospedaliero-Universitaria di Padova",
    address: "Via Nicolò Giustiniani 2",
    city: "Padova",
    postalCode: "35128",
    countryCode: "IT",
    phone: "+39 049 8211111",
    email: "info@aopd.veneto.it",
    website: "www.aopd.veneto.it",
    latitude: "45.4028",
    longitude: "11.8783",
    category: "university",
  },
  {
    name: "Policlinico San Matteo",
    address: "Piazzale Camillo Golgi 19",
    city: "Pavia",
    postalCode: "27100",
    countryCode: "IT",
    phone: "+39 0382 5011",
    email: "info@smatteo.pv.it",
    website: "www.smatteo.pv.it",
    latitude: "45.1922",
    longitude: "9.1456",
    category: "university",
  },
  {
    name: "Azienda Ospedaliero-Universitaria di Verona",
    address: "Piazzale Aristide Stefani 1",
    city: "Verona",
    postalCode: "37126",
    countryCode: "IT",
    phone: "+39 045 8121111",
    email: "info@aovr.veneto.it",
    website: "www.aovr.veneto.it",
    latitude: "45.4333",
    longitude: "10.9833",
    category: "university",
  },
  // OSPEDALI REGIONALI (Regional Hospitals)
  {
    name: "Ospedale Niguarda Ca' Granda",
    address: "Piazza Ospedale Maggiore 3",
    city: "Milano",
    postalCode: "20162",
    countryCode: "IT",
    phone: "+39 02 64441",
    email: "info@ospedaleniguarda.it",
    website: "www.ospedaleniguarda.it",
    latitude: "45.5153",
    longitude: "9.1894",
    category: "regional",
  },
  {
    name: "Ospedale Papa Giovanni XXIII",
    address: "Piazza OMS 1",
    city: "Bergamo",
    postalCode: "24127",
    countryCode: "IT",
    phone: "+39 035 2671",
    email: "info@hpg23.it",
    website: "www.asst-pg23.it",
    latitude: "45.6861",
    longitude: "9.6689",
    category: "regional",
  },
  {
    name: "Ospedale Civile di Brescia",
    address: "Piazzale Spedali Civili 1",
    city: "Brescia",
    postalCode: "25123",
    countryCode: "IT",
    phone: "+39 030 39951",
    email: "info@asst-spedalicivili.it",
    website: "www.asst-spedalicivili.it",
    latitude: "45.5333",
    longitude: "10.2167",
    category: "regional",
  },
  {
    name: "Ospedale Santa Maria Nuova",
    address: "Viale Risorgimento 80",
    city: "Reggio Emilia",
    postalCode: "42123",
    countryCode: "IT",
    phone: "+39 0522 296111",
    email: "info@ausl.re.it",
    website: "www.ausl.re.it",
    latitude: "44.6972",
    longitude: "10.6333",
    category: "regional",
  },
  {
    name: "Ospedale Santa Chiara",
    address: "Largo Medaglie d'Oro 9",
    city: "Trento",
    postalCode: "38122",
    countryCode: "IT",
    phone: "+39 0461 903111",
    email: "info@apss.tn.it",
    website: "www.apss.tn.it",
    latitude: "46.0667",
    longitude: "11.1167",
    category: "regional",
  },
  {
    name: "Ospedale di Bolzano",
    address: "Via Lorenz Böhler 5",
    city: "Bolzano",
    postalCode: "39100",
    countryCode: "IT",
    phone: "+39 0471 908111",
    email: "info@asbz.it",
    website: "www.asbz.it",
    latitude: "46.4983",
    longitude: "11.3547",
    category: "regional",
  },
  {
    name: "Azienda Ospedaliera Santa Maria degli Angeli",
    address: "Via Montereale 24",
    city: "Pordenone",
    postalCode: "33170",
    countryCode: "IT",
    phone: "+39 0434 399111",
    email: "info@aopn.sanita.fvg.it",
    website: "www.aopn.sanita.fvg.it",
    latitude: "45.9583",
    longitude: "12.6556",
    category: "regional",
  },
  {
    name: "Ospedale di Cattinara",
    address: "Strada di Fiume 447",
    city: "Trieste",
    postalCode: "34149",
    countryCode: "IT",
    phone: "+39 040 3991111",
    email: "info@asugi.sanita.fvg.it",
    website: "www.asugi.sanita.fvg.it",
    latitude: "45.6456",
    longitude: "13.8083",
    category: "regional",
  },
  {
    name: "Ospedale Santa Maria della Misericordia",
    address: "Piazzale Santa Maria della Misericordia 15",
    city: "Udine",
    postalCode: "33100",
    countryCode: "IT",
    phone: "+39 0432 5521",
    email: "info@asufc.sanita.fvg.it",
    website: "www.asufc.sanita.fvg.it",
    latitude: "46.0650",
    longitude: "13.2472",
    category: "regional",
  },
  {
    name: "Azienda Ospedaliera Universitaria Integrata Verona",
    address: "Piazzale Aristide Stefani 1",
    city: "Verona",
    postalCode: "37126",
    countryCode: "IT",
    phone: "+39 045 8121111",
    email: "info@aovr.veneto.it",
    website: "www.aovr.veneto.it",
    latitude: "45.4333",
    longitude: "10.9833",
    category: "regional",
  },
  {
    name: "Ospedale Civico Di Cristina Benfratelli",
    address: "Piazza Nicola Leotta 4",
    city: "Palermo",
    postalCode: "90127",
    countryCode: "IT",
    phone: "+39 091 6662111",
    email: "info@arnascivico.it",
    website: "www.arnascivico.it",
    latitude: "38.1194",
    longitude: "13.3617",
    category: "regional",
  },
  {
    name: "Ospedale Garibaldi",
    address: "Piazza Santa Maria di Gesù 5",
    city: "Catania",
    postalCode: "95123",
    countryCode: "IT",
    phone: "+39 095 7594111",
    email: "info@ao-garibaldi.ct.it",
    website: "www.ao-garibaldi.ct.it",
    latitude: "37.5000",
    longitude: "15.0833",
    category: "regional",
  },
  {
    name: "Azienda Ospedaliera Brotzu",
    address: "Piazzale Alessandro Ferraro 1",
    city: "Cagliari",
    postalCode: "09134",
    countryCode: "IT",
    phone: "+39 070 539561",
    email: "info@aobrotzu.it",
    website: "www.aobrotzu.it",
    latitude: "39.2278",
    longitude: "9.1050",
    category: "regional",
  },
  {
    name: "Ospedale Sant'Anna",
    address: "Corso Spezia 60",
    city: "Torino",
    postalCode: "10126",
    countryCode: "IT",
    phone: "+39 011 3134444",
    email: "info@cittadellasalute.to.it",
    website: "www.cittadellasalute.to.it",
    latitude: "45.0408",
    longitude: "7.6717",
    category: "specialized",
  },
  {
    name: "Ospedale Infantile Regina Margherita",
    address: "Piazza Polonia 94",
    city: "Torino",
    postalCode: "10126",
    countryCode: "IT",
    phone: "+39 011 3135437",
    email: "info@cittadellasalute.to.it",
    website: "www.cittadellasalute.to.it",
    latitude: "45.0389",
    longitude: "7.6692",
    category: "specialized",
  },
  {
    name: "Istituto Giannina Gaslini",
    address: "Via Gerolamo Gaslini 5",
    city: "Genova",
    postalCode: "16147",
    countryCode: "IT",
    phone: "+39 010 56361",
    email: "info@gaslini.org",
    website: "www.gaslini.org",
    latitude: "44.3844",
    longitude: "8.9639",
    category: "specialized",
  },
  {
    name: "Ospedale dei Bambini Vittore Buzzi",
    address: "Via Lodovico Castelvetro 32",
    city: "Milano",
    postalCode: "20154",
    countryCode: "IT",
    phone: "+39 02 57991",
    email: "info@asst-fbf-sacco.it",
    website: "www.asst-fbf-sacco.it",
    latitude: "45.4822",
    longitude: "9.1644",
    category: "specialized",
  },
  // OSPEDALI PRIVATI (Private Hospitals)
  {
    name: "Humanitas Research Hospital",
    address: "Via Alessandro Manzoni 56",
    city: "Rozzano",
    postalCode: "20089",
    countryCode: "IT",
    phone: "+39 02 82241",
    email: "info@humanitas.it",
    website: "www.humanitas.it",
    latitude: "45.3806",
    longitude: "9.1611",
    category: "private",
  },
  {
    name: "Istituto Clinico Humanitas",
    address: "Via Alessandro Manzoni 113",
    city: "Rozzano",
    postalCode: "20089",
    countryCode: "IT",
    phone: "+39 02 82242400",
    email: "info@humanitas.it",
    website: "www.humanitas.it",
    latitude: "45.3811",
    longitude: "9.1606",
    category: "private",
  },
  {
    name: "Casa di Cura San Pio X",
    address: "Via Francesco Nava 31",
    city: "Milano",
    postalCode: "20159",
    countryCode: "IT",
    phone: "+39 02 69516111",
    email: "info@sanpiox.net",
    website: "www.sanpiox.net",
    latitude: "45.4956",
    longitude: "9.1789",
    category: "private",
  },
  {
    name: "Clinica Mangiagalli",
    address: "Via della Commenda 12",
    city: "Milano",
    postalCode: "20122",
    countryCode: "IT",
    phone: "+39 02 55031",
    email: "info@policlinico.mi.it",
    website: "www.policlinico.mi.it",
    latitude: "45.4600",
    longitude: "9.1972",
    category: "specialized",
  },
  {
    name: "GVM Care & Research - Maria Cecilia Hospital",
    address: "Via Corriera 1",
    city: "Cotignola",
    postalCode: "48033",
    countryCode: "IT",
    phone: "+39 0545 217111",
    email: "info@gvm.it",
    website: "www.gvm.it",
    latitude: "44.3822",
    longitude: "11.9372",
    category: "private",
  },
];
