export const romanianHospitals = [
  // SPITALE UNIVERSITARE (University Hospitals)
  {
    name: "Spitalul Universitar de Urgență București",
    address: "Splaiul Independenței 169",
    city: "București",
    postalCode: "050098",
    countryCode: "RO",
    phone: "+40 21 318 0522",
    email: "secretariat@suub.ro",
    website: "www.suub.ro",
    latitude: "44.4350",
    longitude: "26.0733",
    category: "university",
  },
  {
    name: "Spitalul Clinic de Urgență Floreasca",
    address: "Calea Floreasca 8",
    city: "București",
    postalCode: "014461",
    countryCode: "RO",
    phone: "+40 21 317 0190",
    email: "secretariat@urgentafloreasca.ro",
    website: "www.urgentafloreasca.ro",
    latitude: "44.4589",
    longitude: "26.0994",
    category: "university",
  },
  {
    name: "Spitalul Clinic Filantropia",
    address: "Bulevardul Ion Mihalache 11-13",
    city: "București",
    postalCode: "011171",
    countryCode: "RO",
    phone: "+40 21 318 8930",
    email: "secretariat@filantropia.ro",
    website: "www.filantropia.ro",
    latitude: "44.4586",
    longitude: "26.0664",
    category: "university",
  },
  {
    name: "Institutul Național pentru Sănătatea Mamei și Copilului Alessandrescu-Rusescu",
    address: "Bulevardul Lacul Tei 120",
    city: "București",
    postalCode: "020395",
    countryCode: "RO",
    phone: "+40 21 318 3643",
    email: "secretariat@insmc.ro",
    website: "www.insmc.ro",
    latitude: "44.4669",
    longitude: "26.1194",
    category: "university",
  },
  {
    name: "Spitalul Clinic de Obstetrică și Ginecologie Polizu",
    address: "Strada Polizu 38-52",
    city: "București",
    postalCode: "011062",
    countryCode: "RO",
    phone: "+40 21 315 1250",
    email: "secretariat@polizu.ro",
    website: "www.polizu.ro",
    latitude: "44.4539",
    longitude: "26.0639",
    category: "university",
  },
  {
    name: "Spitalul Clinic de Copii Marie Curie",
    address: "Bulevardul Constantin Brâncoveanu 20",
    city: "București",
    postalCode: "041451",
    countryCode: "RO",
    phone: "+40 21 460 4260",
    email: "secretariat@mariecurie.ro",
    website: "www.mariecurie.ro",
    latitude: "44.4097",
    longitude: "26.1042",
    category: "specialized",
  },
  {
    name: "Spitalul Clinic de Urgență pentru Copii Grigore Alexandrescu",
    address: "Bulevardul Iancu de Hunedoara 30-32",
    city: "București",
    postalCode: "011743",
    countryCode: "RO",
    phone: "+40 21 316 9366",
    email: "secretariat@copii-grigore.ro",
    website: "www.copii-grigore.ro",
    latitude: "44.4614",
    longitude: "26.0858",
    category: "specialized",
  },
  // SPITALE REGIONALE (Regional Hospitals)
  {
    name: "Spitalul Clinic Județean de Urgență Cluj-Napoca",
    address: "Strada Clinicilor 3-5",
    city: "Cluj-Napoca",
    postalCode: "400006",
    countryCode: "RO",
    phone: "+40 264 592 771",
    email: "secretariat@scju-cluj.ro",
    website: "www.scju-cluj.ro",
    latitude: "46.7667",
    longitude: "23.5833",
    category: "regional",
  },
  {
    name: "Spitalul Clinic de Obstetrică Ginecologie Dominic Stanca Cluj-Napoca",
    address: "Strada Republicii 47-49",
    city: "Cluj-Napoca",
    postalCode: "400162",
    countryCode: "RO",
    phone: "+40 264 431 903",
    email: "secretariat@maternitatecluj.ro",
    website: "www.maternitatecluj.ro",
    latitude: "46.7708",
    longitude: "23.5917",
    category: "specialized",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Timișoara",
    address: "Bulevardul Liviu Rebreanu 156",
    city: "Timișoara",
    postalCode: "300723",
    countryCode: "RO",
    phone: "+40 256 433 111",
    email: "secretariat@hosptm.ro",
    website: "www.hosptm.ro",
    latitude: "45.7489",
    longitude: "21.2269",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Bega Timișoara",
    address: "Strada Gheorghe Dima 5",
    city: "Timișoara",
    postalCode: "300079",
    countryCode: "RO",
    phone: "+40 256 221 173",
    email: "secretariat@maternitatea-bega.ro",
    website: "www.maternitatea-bega.ro",
    latitude: "45.7569",
    longitude: "21.2283",
    category: "specialized",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Târgu Mureș",
    address: "Strada Gheorghe Marinescu 50",
    city: "Târgu Mureș",
    postalCode: "540136",
    countryCode: "RO",
    phone: "+40 265 212 111",
    email: "secretariat@spitalmures.ro",
    website: "www.spitalmures.ro",
    latitude: "46.5456",
    longitude: "24.5628",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Iași",
    address: "Bulevardul Independenței 1",
    city: "Iași",
    postalCode: "700111",
    countryCode: "RO",
    phone: "+40 232 213 666",
    email: "secretariat@scjuiasi.ro",
    website: "www.scjuiasi.ro",
    latitude: "47.1586",
    longitude: "27.5875",
    category: "regional",
  },
  {
    name: "Maternitatea Cuza Vodă Iași",
    address: "Strada Cuza Vodă 34",
    city: "Iași",
    postalCode: "700038",
    countryCode: "RO",
    phone: "+40 232 210 390",
    email: "secretariat@maternitateaiasi.ro",
    website: "www.maternitateaiasi.ro",
    latitude: "47.1583",
    longitude: "27.5839",
    category: "specialized",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Constanța",
    address: "Bulevardul Tomis 145",
    city: "Constanța",
    postalCode: "900591",
    countryCode: "RO",
    phone: "+40 241 503 255",
    email: "secretariat@spitalulconstanta.ro",
    website: "www.spitalulconstanta.ro",
    latitude: "44.1833",
    longitude: "28.6333",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Craiova",
    address: "Strada Tabaci 1",
    city: "Craiova",
    postalCode: "200642",
    countryCode: "RO",
    phone: "+40 251 502 200",
    email: "secretariat@scjucraiova.ro",
    website: "www.scjucraiova.ro",
    latitude: "44.3172",
    longitude: "23.7969",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Brașov",
    address: "Calea București 25-27",
    city: "Brașov",
    postalCode: "500326",
    countryCode: "RO",
    phone: "+40 268 320 022",
    email: "secretariat@hospbv.ro",
    website: "www.hospbv.ro",
    latitude: "45.6486",
    longitude: "25.5928",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Sibiu",
    address: "Bulevardul Corneliu Coposu 2-4",
    city: "Sibiu",
    postalCode: "550245",
    countryCode: "RO",
    phone: "+40 269 215 050",
    email: "secretariat@scjusibiu.ro",
    website: "www.scjusibiu.ro",
    latitude: "45.7928",
    longitude: "24.1519",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Oradea",
    address: "Strada Republicii 37",
    city: "Oradea",
    postalCode: "410167",
    countryCode: "RO",
    phone: "+40 259 401 650",
    email: "secretariat@spitaljudetoradea.ro",
    website: "www.spitaljudetoradea.ro",
    latitude: "47.0458",
    longitude: "21.9189",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Arad",
    address: "Calea Victoriei 1-3",
    city: "Arad",
    postalCode: "310158",
    countryCode: "RO",
    phone: "+40 257 256 561",
    email: "secretariat@spitalarad.ro",
    website: "www.spitalarad.ro",
    latitude: "46.1756",
    longitude: "21.3192",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Ploiești",
    address: "Strada Găgeni 100",
    city: "Ploiești",
    postalCode: "100281",
    countryCode: "RO",
    phone: "+40 244 523 904",
    email: "secretariat@scjuploiesti.ro",
    website: "www.scjuploiesti.ro",
    latitude: "44.9419",
    longitude: "26.0250",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Galați",
    address: "Strada Brăilei 177",
    city: "Galați",
    postalCode: "800578",
    countryCode: "RO",
    phone: "+40 236 317 232",
    email: "secretariat@spitalgalati.ro",
    website: "www.spitalgalati.ro",
    latitude: "45.4253",
    longitude: "28.0353",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Brăila",
    address: "Calea Călărașilor 282",
    city: "Brăila",
    postalCode: "810112",
    countryCode: "RO",
    phone: "+40 239 693 000",
    email: "secretariat@spitalbraila.ro",
    website: "www.spitalbraila.ro",
    latitude: "45.2692",
    longitude: "27.9575",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Buzău",
    address: "Bulevardul 1 Decembrie 1918 nr. 26",
    city: "Buzău",
    postalCode: "120144",
    countryCode: "RO",
    phone: "+40 238 720 988",
    email: "secretariat@spitalbuzau.ro",
    website: "www.spitalbuzau.ro",
    latitude: "45.1500",
    longitude: "26.8167",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Suceava",
    address: "Bulevardul 1 Mai 21",
    city: "Suceava",
    postalCode: "720224",
    countryCode: "RO",
    phone: "+40 230 214 931",
    email: "secretariat@spitalsuceava.ro",
    website: "www.spitalsuceava.ro",
    latitude: "47.6514",
    longitude: "26.2556",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Piatra Neamț",
    address: "Bulevardul Traian 1",
    city: "Piatra Neamț",
    postalCode: "610083",
    countryCode: "RO",
    phone: "+40 233 212 930",
    email: "secretariat@spitalpiatraneamt.ro",
    website: "www.spitalpiatraneamt.ro",
    latitude: "46.9278",
    longitude: "26.3708",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Baia Mare",
    address: "Strada George Coșbuc 31",
    city: "Baia Mare",
    postalCode: "430031",
    countryCode: "RO",
    phone: "+40 262 278 100",
    email: "secretariat@spitaljudmm.ro",
    website: "www.spitaljudmm.ro",
    latitude: "47.6567",
    longitude: "23.5700",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Satu Mare",
    address: "Strada Prahovei 1",
    city: "Satu Mare",
    postalCode: "440055",
    countryCode: "RO",
    phone: "+40 261 805 100",
    email: "secretariat@spitaljudsm.ro",
    website: "www.spitaljudsm.ro",
    latitude: "47.7900",
    longitude: "22.8850",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Pitești",
    address: "Strada Drăgășani 4",
    city: "Pitești",
    postalCode: "110304",
    countryCode: "RO",
    phone: "+40 248 287 500",
    email: "secretariat@spitalpitesti.ro",
    website: "www.spitalpitesti.ro",
    latitude: "44.8564",
    longitude: "24.8692",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Alba Iulia",
    address: "Bulevardul Revoluției 1989 nr. 23",
    city: "Alba Iulia",
    postalCode: "510077",
    countryCode: "RO",
    phone: "+40 258 820 825",
    email: "secretariat@spitalalba.ro",
    website: "www.spitalalba.ro",
    latitude: "46.0686",
    longitude: "23.5722",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Bistrița",
    address: "Strada General Grigore Bălan 43",
    city: "Bistrița",
    postalCode: "420053",
    countryCode: "RO",
    phone: "+40 263 231 404",
    email: "secretariat@spitalbistrita.ro",
    website: "www.spitalbistrita.ro",
    latitude: "47.1333",
    longitude: "24.5000",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Deva",
    address: "Strada 22 Decembrie 58",
    city: "Deva",
    postalCode: "330022",
    countryCode: "RO",
    phone: "+40 254 215 500",
    email: "secretariat@spitaldeva.ro",
    website: "www.spitaldeva.ro",
    latitude: "45.8833",
    longitude: "22.9000",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Reșița",
    address: "Bulevardul Alexandru Ioan Cuza 37",
    city: "Reșița",
    postalCode: "320096",
    countryCode: "RO",
    phone: "+40 255 212 022",
    email: "secretariat@spitalresita.ro",
    website: "www.spitalresita.ro",
    latitude: "45.2978",
    longitude: "21.8889",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Drobeta-Turnu Severin",
    address: "Strada Crișan 10",
    city: "Drobeta-Turnu Severin",
    postalCode: "220037",
    countryCode: "RO",
    phone: "+40 252 320 990",
    email: "secretariat@spitalmehedinti.ro",
    website: "www.spitalmehedinti.ro",
    latitude: "44.6333",
    longitude: "22.6667",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Sfântu Gheorghe",
    address: "Strada Fabricii 14",
    city: "Sfântu Gheorghe",
    postalCode: "520064",
    countryCode: "RO",
    phone: "+40 267 351 200",
    email: "secretariat@spitalcovasna.ro",
    website: "www.spitalcovasna.ro",
    latitude: "45.8667",
    longitude: "25.7833",
    category: "regional",
  },
  {
    name: "Spitalul Clinic Județean de Urgență Miercurea Ciuc",
    address: "Strada Márton Áron 2",
    city: "Miercurea Ciuc",
    postalCode: "530003",
    countryCode: "RO",
    phone: "+40 266 371 699",
    email: "secretariat@spitalharghita.ro",
    website: "www.spitalharghita.ro",
    latitude: "46.3583",
    longitude: "25.8000",
    category: "regional",
  },
  // SPITALE PRIVATE (Private Hospitals)
  {
    name: "Regina Maria - Spitalul Baneasa",
    address: "Strada Ficusului 40",
    city: "București",
    postalCode: "077190",
    countryCode: "RO",
    phone: "+40 21 9268",
    email: "contact@reginamaria.ro",
    website: "www.reginamaria.ro",
    latitude: "44.5036",
    longitude: "26.0850",
    category: "private",
  },
  {
    name: "Regina Maria - Spitalul Euroclinic",
    address: "Bulevardul Unirii 74",
    city: "București",
    postalCode: "030836",
    countryCode: "RO",
    phone: "+40 21 9268",
    email: "contact@reginamaria.ro",
    website: "www.reginamaria.ro",
    latitude: "44.4244",
    longitude: "26.1111",
    category: "private",
  },
  {
    name: "Medicover Hospital",
    address: "Strada Heliade Între Vii 54",
    city: "București",
    postalCode: "024093",
    countryCode: "RO",
    phone: "+40 21 9268",
    email: "contact@medicover.ro",
    website: "www.medicover.ro",
    latitude: "44.4356",
    longitude: "26.0722",
    category: "private",
  },
  {
    name: "Sanador Hospital",
    address: "Șoseaua Nordului 3-5",
    city: "București",
    postalCode: "014101",
    countryCode: "RO",
    phone: "+40 21 9699",
    email: "contact@sanador.ro",
    website: "www.sanador.ro",
    latitude: "44.4761",
    longitude: "26.0778",
    category: "private",
  },
  {
    name: "MedLife Spitalul Humanitas",
    address: "Piața Charles de Gaulle 15",
    city: "București",
    postalCode: "011857",
    countryCode: "RO",
    phone: "+40 21 9268",
    email: "contact@medlife.ro",
    website: "www.medlife.ro",
    latitude: "44.4681",
    longitude: "26.0800",
    category: "private",
  },
  {
    name: "MedLife - Spitalul Grivița",
    address: "Calea Griviței 365",
    city: "București",
    postalCode: "010702",
    countryCode: "RO",
    phone: "+40 21 9268",
    email: "contact@medlife.ro",
    website: "www.medlife.ro",
    latitude: "44.4583",
    longitude: "26.0611",
    category: "private",
  },
];
