export const slovakHospitals = [
  // FAKULTNÉ A UNIVERZITNÉ NEMOCNICE
  {
    name: "Univerzitná nemocnica Bratislava - Ružinov",
    address: "Ružinovská 6",
    city: "Bratislava",
    postalCode: "826 06",
    countryCode: "SK",
    phone: "+421 2 48 234 111",
    email: "sekretariat@unb.sk",
    website: "www.unb.sk",
    latitude: "48.1516",
    longitude: "17.1374",
    category: "university",
  },
  {
    name: "Univerzitná nemocnica Bratislava - Kramáre",
    address: "Limbová 5",
    city: "Bratislava",
    postalCode: "833 05",
    countryCode: "SK",
    phone: "+421 2 59 541 111",
    email: "sekretariat@unb.sk",
    website: "www.unb.sk",
    latitude: "48.1772",
    longitude: "17.1089",
    category: "university",
  },
  {
    name: "Národný ústav srdcových a cievnych chorôb",
    address: "Pod Krásnou hôrkou 1",
    city: "Bratislava",
    postalCode: "833 48",
    countryCode: "SK",
    phone: "+421 2 59 320 111",
    email: "info@nusch.sk",
    website: "www.nusch.sk",
    latitude: "48.1747",
    longitude: "17.1067",
    category: "specialized",
  },
  {
    name: "Národný ústav detských chorôb",
    address: "Limbová 1",
    city: "Bratislava",
    postalCode: "833 40",
    countryCode: "SK",
    phone: "+421 2 59 371 111",
    email: "nudc@nudc.sk",
    website: "www.nudc.sk",
    latitude: "48.1761",
    longitude: "17.1078",
    category: "specialized",
  },
  {
    name: "Nemocnica sv. Michala",
    address: "Cintorínska 16",
    city: "Bratislava",
    postalCode: "811 08",
    countryCode: "SK",
    phone: "+421 2 32 550 111",
    email: "info@nsmas.sk",
    website: "www.nsmas.sk",
    latitude: "48.1478",
    longitude: "17.1128",
    category: "general",
  },
  {
    name: "Univerzitná nemocnica L. Pasteura Košice",
    address: "Rastislavova 43",
    city: "Košice",
    postalCode: "040 01",
    countryCode: "SK",
    phone: "+421 55 615 1111",
    email: "unlp@unlp.sk",
    website: "www.unlp.sk",
    latitude: "48.7164",
    longitude: "21.2611",
    category: "university",
  },
  {
    name: "Univerzitná nemocnica Martin",
    address: "Kollárova 2",
    city: "Martin",
    postalCode: "036 01",
    countryCode: "SK",
    phone: "+421 43 420 1111",
    email: "info@unm.sk",
    website: "www.unm.sk",
    latitude: "49.0636",
    longitude: "18.9214",
    category: "university",
  },
  {
    name: "FN s poliklinikou F.D. Roosevelta Banská Bystrica",
    address: "Námestie L. Svobodu 1",
    city: "Banská Bystrica",
    postalCode: "974 01",
    countryCode: "SK",
    phone: "+421 48 441 1111",
    email: "infocentrum@nspbb.sk",
    website: "www.fnspfdr.sk",
    latitude: "48.7361",
    longitude: "19.1461",
    category: "faculty",
  },
  {
    name: "FN s poliklinikou J.A. Reimana Prešov",
    address: "Jána Hollého 14",
    city: "Prešov",
    postalCode: "080 01",
    countryCode: "SK",
    phone: "+421 51 701 1111",
    email: "riaditel@fnsppresov.sk",
    website: "www.fnsppresov.sk",
    latitude: "49.0017",
    longitude: "21.2394",
    category: "faculty",
  },
  {
    name: "FN s poliklinikou Nové Zámky",
    address: "Slovenská 11/A",
    city: "Nové Zámky",
    postalCode: "940 54",
    countryCode: "SK",
    phone: "+421 35 691 1111",
    email: "email@nspnz.sk",
    website: "www.nspnz.sk",
    latitude: "47.9856",
    longitude: "18.1611",
    category: "faculty",
  },
  {
    name: "FN s poliklinikou Žilina",
    address: "Vojtecha Spanyola 43",
    city: "Žilina",
    postalCode: "010 01",
    countryCode: "SK",
    phone: "+421 41 511 1111",
    email: "sekretariat.r@fnspza.sk",
    website: "www.fnspza.sk",
    latitude: "49.2239",
    longitude: "18.7394",
    category: "faculty",
  },
  {
    name: "Fakultná nemocnica Trenčín",
    address: "Legionárska 28",
    city: "Trenčín",
    postalCode: "911 71",
    countryCode: "SK",
    phone: "+421 32 656 6111",
    email: "riaditel@fntn.sk",
    website: "www.fntn.sk",
    latitude: "48.8917",
    longitude: "18.0378",
    category: "faculty",
  },
  {
    name: "Fakultná nemocnica Trnava",
    address: "A. Žarnova 11",
    city: "Trnava",
    postalCode: "917 01",
    countryCode: "SK",
    phone: "+421 33 593 8111",
    email: "fntt@fntt.sk",
    website: "www.fntt.sk",
    latitude: "48.3783",
    longitude: "17.5878",
    category: "faculty",
  },
  {
    name: "Ústredná vojenská nemocnica SNP Ružomberok",
    address: "Generála Miloša Vesela 21",
    city: "Ružomberok",
    postalCode: "034 01",
    countryCode: "SK",
    phone: "+421 44 438 2111",
    email: "uvn@uvn.sk",
    website: "www.uvn.sk",
    latitude: "49.0756",
    longitude: "19.3044",
    category: "military",
  },
  // REGIONÁLNE NEMOCNICE
  {
    name: "Nemocnica Poprad, a.s.",
    address: "Banícka 28",
    city: "Poprad",
    postalCode: "058 01",
    countryCode: "SK",
    phone: "+421 52 712 1111",
    email: "sekretariat@nemocnicapp.sk",
    website: "www.nemocnicapp.sk",
    latitude: "49.0583",
    longitude: "20.2972",
    category: "regional",
  },
  {
    name: "Nemocnica Alexandra Wintera Piešťany",
    address: "Winterova 66",
    city: "Piešťany",
    postalCode: "921 01",
    countryCode: "SK",
    phone: "+421 33 795 1111",
    email: "sekretariat@naw.sk",
    website: "www.naw.sk",
    latitude: "48.5917",
    longitude: "17.8361",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou Považská Bystrica",
    address: "Nemocničná 986",
    city: "Považská Bystrica",
    postalCode: "017 26",
    countryCode: "SK",
    phone: "+421 42 430 1111",
    email: "sekretariat@nemocnicapb.sk",
    website: "www.nemocnicapb.sk",
    latitude: "49.1214",
    longitude: "18.4356",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou Lučenec",
    address: "Námestie republiky 15",
    city: "Lučenec",
    postalCode: "984 01",
    countryCode: "SK",
    phone: "+421 47 431 1111",
    email: "info@nsplc.sk",
    website: "www.nsplc.sk",
    latitude: "48.3328",
    longitude: "19.6678",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou Spišská Nová Ves",
    address: "Jánskeho 1",
    city: "Spišská Nová Ves",
    postalCode: "052 01",
    countryCode: "SK",
    phone: "+421 53 417 1111",
    email: "sekretariat@nspsnv.sk",
    website: "www.nspsnv.sk",
    latitude: "48.9456",
    longitude: "20.5611",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou Trebišov",
    address: "SNP 1079/76",
    city: "Trebišov",
    postalCode: "075 01",
    countryCode: "SK",
    phone: "+421 56 672 1111",
    email: "info@nsptv.sk",
    website: "www.nsptv.sk",
    latitude: "48.6283",
    longitude: "21.7178",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou Dunajská Streda",
    address: "Veľkoblahovská 23",
    city: "Dunajská Streda",
    postalCode: "929 01",
    countryCode: "SK",
    phone: "+421 31 552 3111",
    email: "info@nspds.sk",
    website: "www.nspds.sk",
    latitude: "47.9933",
    longitude: "17.6178",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou Rimavská Sobota",
    address: "Šrobárova 1",
    city: "Rimavská Sobota",
    postalCode: "979 01",
    countryCode: "SK",
    phone: "+421 47 563 1111",
    email: "info@nsprs.sk",
    website: "www.nsprs.sk",
    latitude: "48.3831",
    longitude: "20.0222",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou Prievidza",
    address: "Nemocničná 2",
    city: "Prievidza",
    postalCode: "971 01",
    countryCode: "SK",
    phone: "+421 46 542 1111",
    email: "sekretariat@nsppd.sk",
    website: "www.nsppd.sk",
    latitude: "48.7744",
    longitude: "18.6247",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou Levice",
    address: "SNP 19",
    city: "Levice",
    postalCode: "934 01",
    countryCode: "SK",
    phone: "+421 36 635 1111",
    email: "sekretariat@nsplv.sk",
    website: "www.nsplv.sk",
    latitude: "48.2164",
    longitude: "18.6003",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou Topoľčany",
    address: "Pavlovova 17",
    city: "Topoľčany",
    postalCode: "955 01",
    countryCode: "SK",
    phone: "+421 38 532 1111",
    email: "nemocnica@nspte.sk",
    website: "www.nemocnicatovolcany.sk",
    latitude: "48.5558",
    longitude: "18.1756",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou sv. Lukáša Galanta",
    address: "Hodská 373/38",
    city: "Galanta",
    postalCode: "924 22",
    countryCode: "SK",
    phone: "+421 31 780 1111",
    email: "sekretariat@nspga.sk",
    website: "www.nspga.sk",
    latitude: "48.1872",
    longitude: "17.7272",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou sv. Jakuba Bardejov",
    address: "Sv. Jakuba 21",
    city: "Bardejov",
    postalCode: "085 01",
    countryCode: "SK",
    phone: "+421 54 478 1111",
    email: "sekretariat@nspbj.sk",
    website: "www.nspbj.sk",
    latitude: "49.2933",
    longitude: "21.2744",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou Vranov nad Topľou",
    address: "M.R. Štefánika 187/177 B",
    city: "Vranov nad Topľou",
    postalCode: "093 27",
    countryCode: "SK",
    phone: "+421 57 488 1111",
    email: "info@nspvt.sk",
    website: "www.nspvt.sk",
    latitude: "48.8831",
    longitude: "21.6819",
    category: "regional",
  },
  {
    name: "Nemocnica A. Leňa Humenné",
    address: "Nemocničná 7",
    city: "Humenné",
    postalCode: "066 01",
    countryCode: "SK",
    phone: "+421 57 772 1111",
    email: "info@nsphe.sk",
    website: "www.nsphe.sk",
    latitude: "48.9331",
    longitude: "21.9094",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou Š. Kukuru Michalovce",
    address: "Špitálska 2",
    city: "Michalovce",
    postalCode: "071 01",
    countryCode: "SK",
    phone: "+421 56 641 1111",
    email: "sekretariat@nspmi.sk",
    website: "www.nspmi.sk",
    latitude: "48.7547",
    longitude: "21.9194",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou sv. Barbory Rožňava",
    address: "Špitálska 3",
    city: "Rožňava",
    postalCode: "048 01",
    countryCode: "SK",
    phone: "+421 58 732 1111",
    email: "info@nsprv.sk",
    website: "www.nsprv.sk",
    latitude: "48.6594",
    longitude: "20.5322",
    category: "regional",
  },
  {
    name: "Nemocnica arm. generála L. Svobodu Svidník",
    address: "MUDr. Pribulu 412/4",
    city: "Svidník",
    postalCode: "089 01",
    countryCode: "SK",
    phone: "+421 54 788 1111",
    email: "info@nspsv.sk",
    website: "www.nspsv.sk",
    latitude: "49.3056",
    longitude: "21.5706",
    category: "regional",
  },
  {
    name: "Nemocnica s poliklinikou Revúca",
    address: "Litovelská 25",
    city: "Revúca",
    postalCode: "050 01",
    countryCode: "SK",
    phone: "+421 58 442 1111",
    email: "nsprevuca@nsprevuca.sk",
    website: "www.nsprevuca.sk",
    latitude: "48.6828",
    longitude: "20.1147",
    category: "regional",
  },
  // AGEL NEMOCNICE
  {
    name: "Nemocnica AGEL Košice-Šaca",
    address: "Lúčna 57",
    city: "Košice-Šaca",
    postalCode: "040 15",
    countryCode: "SK",
    phone: "+421 55 723 8111",
    email: "sekretariat.saca@agel.sk",
    website: "nemocnicasaca.agel.sk",
    latitude: "48.6661",
    longitude: "21.2086",
    category: "private",
  },
  {
    name: "Nemocnica AGEL Komárno",
    address: "Mederčská 39",
    city: "Komárno",
    postalCode: "945 05",
    countryCode: "SK",
    phone: "+421 35 790 9123",
    email: "sekretariat.komarno@agel.sk",
    website: "nemocnicakomarno.agel.sk",
    latitude: "47.7631",
    longitude: "18.1297",
    category: "private",
  },
  {
    name: "Nemocnica AGEL Banská Štiavnica",
    address: "Bratská 17",
    city: "Banská Štiavnica",
    postalCode: "969 01",
    countryCode: "SK",
    phone: "+421 45 694 1111",
    email: "sekretariat.stiavnica@agel.sk",
    website: "nemocnicabanstiavnica.agel.sk",
    latitude: "48.4589",
    longitude: "18.8958",
    category: "private",
  },
  {
    name: "Nemocnica AGEL Zvolen",
    address: "Kuzmányho nábrežie 28",
    city: "Zvolen",
    postalCode: "960 01",
    countryCode: "SK",
    phone: "+421 45 520 1111",
    email: "sekretariat.zvolen@agel.sk",
    website: "nemocnicazvolen.agel.sk",
    latitude: "48.5747",
    longitude: "19.1306",
    category: "private",
  },
  {
    name: "Nemocnica AGEL Handlová",
    address: "Nemocničná 1",
    city: "Handlová",
    postalCode: "972 51",
    countryCode: "SK",
    phone: "+421 46 519 1111",
    email: "sekretariat.handlova@agel.sk",
    website: "nemocnicahandlova.agel.sk",
    latitude: "48.7292",
    longitude: "18.7594",
    category: "private",
  },
  // ŠPECIALIZOVANÉ ÚSTAVY
  {
    name: "Stredoslovenský ústav srdcových a cievnych chorôb",
    address: "Cesta k nemocnici 1",
    city: "Banská Bystrica",
    postalCode: "974 01",
    countryCode: "SK",
    phone: "+421 48 433 3111",
    email: "kontakt@suscch.eu",
    website: "www.suscch.eu",
    latitude: "48.7389",
    longitude: "19.1514",
    category: "specialized",
  },
  {
    name: "Národný ústav reumatických chorôb Piešťany",
    address: "Nábrežie I. Krasku 4",
    city: "Piešťany",
    postalCode: "921 01",
    countryCode: "SK",
    phone: "+421 33 796 9111",
    email: "nurch@nurch.sk",
    website: "www.nurch.sk",
    latitude: "48.5917",
    longitude: "17.8264",
    category: "specialized",
  },
  {
    name: "Detská fakultná nemocnica s poliklinikou Banská Bystrica",
    address: "Námestie L. Svobodu 4",
    city: "Banská Bystrica",
    postalCode: "974 01",
    countryCode: "SK",
    phone: "+421 48 472 6111",
    email: "sekretariat@dfnbb.sk",
    website: "www.dfnbb.sk",
    latitude: "48.7367",
    longitude: "19.1453",
    category: "specialized",
  },
  {
    name: "Detská fakultná nemocnica Košice",
    address: "Trieda SNP 1",
    city: "Košice",
    postalCode: "040 11",
    countryCode: "SK",
    phone: "+421 55 235 1111",
    email: "sekretariat@dfnke.sk",
    website: "www.dfnke.sk",
    latitude: "48.7131",
    longitude: "21.2556",
    category: "specialized",
  },
  {
    name: "Východoslovenský ústav srdcových a cievnych chorôb",
    address: "Ondavská 8",
    city: "Košice",
    postalCode: "040 11",
    countryCode: "SK",
    phone: "+421 55 789 1111",
    email: "info@vuscch.sk",
    website: "www.vuscch.sk",
    latitude: "48.7153",
    longitude: "21.2592",
    category: "specialized",
  },
  {
    name: "Národný onkologický ústav",
    address: "Klenová 1",
    city: "Bratislava",
    postalCode: "831 10",
    countryCode: "SK",
    phone: "+421 2 59 378 111",
    email: "nou@nou.sk",
    website: "www.nou.sk",
    latitude: "48.1764",
    longitude: "17.1158",
    category: "specialized",
  },
  {
    name: "Psychiatrická nemocnica Pezinok",
    address: "Malacká cesta 63",
    city: "Pezinok",
    postalCode: "902 18",
    countryCode: "SK",
    phone: "+421 33 640 3111",
    email: "sekretariat@pnpp.sk",
    website: "www.pnpp.sk",
    latitude: "48.3017",
    longitude: "17.2661",
    category: "psychiatric",
  },
  {
    name: "Psychiatrická nemocnica prof. Matulaya Kremnica",
    address: "Banská cesta 1",
    city: "Kremnica",
    postalCode: "967 01",
    countryCode: "SK",
    phone: "+421 45 674 1111",
    email: "pnkremnica@pnkremnica.sk",
    website: "www.pnkremnica.sk",
    latitude: "48.7050",
    longitude: "18.9178",
    category: "psychiatric",
  },
  // PENTA HOSPITALS
  {
    name: "Nemocnica Bory",
    address: "Nemocničná 1",
    city: "Bratislava",
    postalCode: "841 03",
    countryCode: "SK",
    phone: "+421 2 210 29 111",
    email: "info@nemocnicabory.sk",
    website: "www.nemocnicabory.sk",
    latitude: "48.1769",
    longitude: "17.0561",
    category: "private",
  },
  {
    name: "Špecializovaná nemocnica sv. Svorada Zobor Nitra",
    address: "Kláštorská 134",
    city: "Nitra",
    postalCode: "949 01",
    countryCode: "SK",
    phone: "+421 37 651 1111",
    email: "riaditel@snzobor.sk",
    website: "www.snzobor.sk",
    latitude: "48.3211",
    longitude: "18.0864",
    category: "specialized",
  },
];

export async function seedSlovakHospitals(db: any) {
  console.log('Starting Slovak hospitals seed...');
  let created = 0;
  let skipped = 0;

  for (const hospital of slovakHospitals) {
    try {
      const existing = await db.query.hospitals.findFirst({
        where: (h: any, { eq }: any) => eq(h.name, hospital.name)
      });
      
      if (existing) {
        console.log(`Skipping existing hospital: ${hospital.name}`);
        skipped++;
        continue;
      }

      const { hospitals } = await import('@shared/schema');
      await db.insert(hospitals).values({
        name: hospital.name,
        fullName: hospital.name,
        streetNumber: hospital.address,
        city: hospital.city,
        postalCode: hospital.postalCode,
        countryCode: hospital.countryCode,
        phone: hospital.phone,
        email: hospital.email,
        latitude: hospital.latitude,
        longitude: hospital.longitude,
        isActive: true,
      });
      created++;
      console.log(`Created hospital: ${hospital.name}`);
    } catch (error) {
      console.error(`Error creating hospital ${hospital.name}:`, error);
    }
  }

  console.log(`Seed completed: ${created} created, ${skipped} skipped`);
  return { created, skipped };
}
