export const usaHospitals = [
  // TOP ACADEMIC MEDICAL CENTERS
  {
    name: "Massachusetts General Hospital",
    address: "55 Fruit Street",
    city: "Boston, MA",
    postalCode: "02114",
    countryCode: "US",
    phone: "+1 617 726 2000",
    email: "info@mgh.harvard.edu",
    website: "www.massgeneral.org",
    latitude: "42.3631",
    longitude: "-71.0686",
    category: "university",
  },
  {
    name: "Brigham and Women's Hospital",
    address: "75 Francis Street",
    city: "Boston, MA",
    postalCode: "02115",
    countryCode: "US",
    phone: "+1 617 732 5500",
    email: "info@bwh.harvard.edu",
    website: "www.brighamandwomens.org",
    latitude: "42.3358",
    longitude: "-71.1069",
    category: "university",
  },
  {
    name: "Johns Hopkins Hospital",
    address: "1800 Orleans Street",
    city: "Baltimore, MD",
    postalCode: "21287",
    countryCode: "US",
    phone: "+1 410 955 5000",
    email: "info@jhmi.edu",
    website: "www.hopkinsmedicine.org",
    latitude: "39.2964",
    longitude: "-76.5928",
    category: "university",
  },
  {
    name: "Mayo Clinic - Rochester",
    address: "200 First Street SW",
    city: "Rochester, MN",
    postalCode: "55905",
    countryCode: "US",
    phone: "+1 507 284 2511",
    email: "info@mayo.edu",
    website: "www.mayoclinic.org",
    latitude: "44.0225",
    longitude: "-92.4669",
    category: "university",
  },
  {
    name: "Cleveland Clinic",
    address: "9500 Euclid Avenue",
    city: "Cleveland, OH",
    postalCode: "44195",
    countryCode: "US",
    phone: "+1 216 444 2200",
    email: "info@ccf.org",
    website: "www.clevelandclinic.org",
    latitude: "41.5028",
    longitude: "-81.6208",
    category: "university",
  },
  {
    name: "NewYork-Presbyterian Hospital",
    address: "525 East 68th Street",
    city: "New York, NY",
    postalCode: "10065",
    countryCode: "US",
    phone: "+1 212 746 5454",
    email: "info@nyp.org",
    website: "www.nyp.org",
    latitude: "40.7647",
    longitude: "-73.9544",
    category: "university",
  },
  {
    name: "UCLA Medical Center",
    address: "757 Westwood Plaza",
    city: "Los Angeles, CA",
    postalCode: "90095",
    countryCode: "US",
    phone: "+1 310 825 9111",
    email: "info@mednet.ucla.edu",
    website: "www.uclahealth.org",
    latitude: "34.0667",
    longitude: "-118.4458",
    category: "university",
  },
  {
    name: "UCSF Medical Center",
    address: "505 Parnassus Avenue",
    city: "San Francisco, CA",
    postalCode: "94143",
    countryCode: "US",
    phone: "+1 415 476 1000",
    email: "info@ucsf.edu",
    website: "www.ucsfhealth.org",
    latitude: "37.7633",
    longitude: "-122.4578",
    category: "university",
  },
  {
    name: "Stanford Health Care",
    address: "300 Pasteur Drive",
    city: "Stanford, CA",
    postalCode: "94305",
    countryCode: "US",
    phone: "+1 650 723 4000",
    email: "info@stanfordhealthcare.org",
    website: "www.stanfordhealthcare.org",
    latitude: "37.4336",
    longitude: "-122.1750",
    category: "university",
  },
  {
    name: "Cedars-Sinai Medical Center",
    address: "8700 Beverly Boulevard",
    city: "Los Angeles, CA",
    postalCode: "90048",
    countryCode: "US",
    phone: "+1 310 423 3277",
    email: "info@cshs.org",
    website: "www.cedars-sinai.org",
    latitude: "34.0756",
    longitude: "-118.3806",
    category: "university",
  },
  {
    name: "Northwestern Memorial Hospital",
    address: "251 East Huron Street",
    city: "Chicago, IL",
    postalCode: "60611",
    countryCode: "US",
    phone: "+1 312 926 2000",
    email: "info@nm.org",
    website: "www.nm.org",
    latitude: "41.8947",
    longitude: "-87.6211",
    category: "university",
  },
  {
    name: "University of Chicago Medical Center",
    address: "5841 South Maryland Avenue",
    city: "Chicago, IL",
    postalCode: "60637",
    countryCode: "US",
    phone: "+1 773 702 1000",
    email: "info@uchicagomedicine.org",
    website: "www.uchicagomedicine.org",
    latitude: "41.7875",
    longitude: "-87.6028",
    category: "university",
  },
  {
    name: "Mount Sinai Hospital",
    address: "1 Gustave L. Levy Place",
    city: "New York, NY",
    postalCode: "10029",
    countryCode: "US",
    phone: "+1 212 241 6500",
    email: "info@mountsinai.org",
    website: "www.mountsinai.org",
    latitude: "40.7903",
    longitude: "-73.9525",
    category: "university",
  },
  {
    name: "NYU Langone Health",
    address: "550 First Avenue",
    city: "New York, NY",
    postalCode: "10016",
    countryCode: "US",
    phone: "+1 212 263 7300",
    email: "info@nyulangone.org",
    website: "www.nyulangone.org",
    latitude: "40.7422",
    longitude: "-73.9744",
    category: "university",
  },
  {
    name: "Hospital of the University of Pennsylvania",
    address: "3400 Spruce Street",
    city: "Philadelphia, PA",
    postalCode: "19104",
    countryCode: "US",
    phone: "+1 215 662 4000",
    email: "info@pennmedicine.org",
    website: "www.pennmedicine.org",
    latitude: "39.9494",
    longitude: "-75.1931",
    category: "university",
  },
  {
    name: "Duke University Hospital",
    address: "2301 Erwin Road",
    city: "Durham, NC",
    postalCode: "27710",
    countryCode: "US",
    phone: "+1 919 684 8111",
    email: "info@duke.edu",
    website: "www.dukehealth.org",
    latitude: "36.0069",
    longitude: "-78.9389",
    category: "university",
  },
  {
    name: "Vanderbilt University Medical Center",
    address: "1211 Medical Center Drive",
    city: "Nashville, TN",
    postalCode: "37232",
    countryCode: "US",
    phone: "+1 615 322 5000",
    email: "info@vumc.org",
    website: "www.vumc.org",
    latitude: "36.1422",
    longitude: "-86.8000",
    category: "university",
  },
  {
    name: "Emory University Hospital",
    address: "1364 Clifton Road NE",
    city: "Atlanta, GA",
    postalCode: "30322",
    countryCode: "US",
    phone: "+1 404 712 2000",
    email: "info@emoryhealthcare.org",
    website: "www.emoryhealthcare.org",
    latitude: "33.7933",
    longitude: "-84.3222",
    category: "university",
  },
  {
    name: "University of Michigan Health",
    address: "1500 East Medical Center Drive",
    city: "Ann Arbor, MI",
    postalCode: "48109",
    countryCode: "US",
    phone: "+1 734 936 4000",
    email: "info@umich.edu",
    website: "www.uofmhealth.org",
    latitude: "42.2828",
    longitude: "-83.7286",
    category: "university",
  },
  {
    name: "University of Pittsburgh Medical Center",
    address: "200 Lothrop Street",
    city: "Pittsburgh, PA",
    postalCode: "15213",
    countryCode: "US",
    phone: "+1 412 647 2345",
    email: "info@upmc.edu",
    website: "www.upmc.com",
    latitude: "40.4425",
    longitude: "-79.9572",
    category: "university",
  },
  // WOMEN'S AND CHILDREN'S HOSPITALS
  {
    name: "Children's Hospital of Philadelphia",
    address: "3401 Civic Center Boulevard",
    city: "Philadelphia, PA",
    postalCode: "19104",
    countryCode: "US",
    phone: "+1 215 590 1000",
    email: "info@chop.edu",
    website: "www.chop.edu",
    latitude: "39.9478",
    longitude: "-75.1944",
    category: "specialized",
  },
  {
    name: "Boston Children's Hospital",
    address: "300 Longwood Avenue",
    city: "Boston, MA",
    postalCode: "02115",
    countryCode: "US",
    phone: "+1 617 355 6000",
    email: "info@childrens.harvard.edu",
    website: "www.childrenshospital.org",
    latitude: "42.3367",
    longitude: "-71.1050",
    category: "specialized",
  },
  {
    name: "Children's National Hospital",
    address: "111 Michigan Avenue NW",
    city: "Washington, DC",
    postalCode: "20010",
    countryCode: "US",
    phone: "+1 202 476 5000",
    email: "info@childrensnational.org",
    website: "www.childrensnational.org",
    latitude: "38.9286",
    longitude: "-77.0156",
    category: "specialized",
  },
  {
    name: "Texas Children's Hospital",
    address: "6621 Fannin Street",
    city: "Houston, TX",
    postalCode: "77030",
    countryCode: "US",
    phone: "+1 832 824 1000",
    email: "info@texaschildrens.org",
    website: "www.texaschildrens.org",
    latitude: "29.7069",
    longitude: "-95.4019",
    category: "specialized",
  },
  {
    name: "Children's Hospital Los Angeles",
    address: "4650 Sunset Boulevard",
    city: "Los Angeles, CA",
    postalCode: "90027",
    countryCode: "US",
    phone: "+1 323 660 2450",
    email: "info@chla.usc.edu",
    website: "www.chla.org",
    latitude: "34.0989",
    longitude: "-118.2894",
    category: "specialized",
  },
  {
    name: "Nationwide Children's Hospital",
    address: "700 Children's Drive",
    city: "Columbus, OH",
    postalCode: "43205",
    countryCode: "US",
    phone: "+1 614 722 2000",
    email: "info@nationwidechildrens.org",
    website: "www.nationwidechildrens.org",
    latitude: "39.9550",
    longitude: "-82.9839",
    category: "specialized",
  },
  {
    name: "Ann & Robert H. Lurie Children's Hospital of Chicago",
    address: "225 East Chicago Avenue",
    city: "Chicago, IL",
    postalCode: "60611",
    countryCode: "US",
    phone: "+1 312 227 4000",
    email: "info@luriechildrens.org",
    website: "www.luriechildrens.org",
    latitude: "41.8967",
    longitude: "-87.6208",
    category: "specialized",
  },
  {
    name: "Cincinnati Children's Hospital Medical Center",
    address: "3333 Burnet Avenue",
    city: "Cincinnati, OH",
    postalCode: "45229",
    countryCode: "US",
    phone: "+1 513 636 4200",
    email: "info@cchmc.org",
    website: "www.cincinnatichildrens.org",
    latitude: "39.1411",
    longitude: "-84.5019",
    category: "specialized",
  },
  // REGIONAL MEDICAL CENTERS
  {
    name: "Houston Methodist Hospital",
    address: "6565 Fannin Street",
    city: "Houston, TX",
    postalCode: "77030",
    countryCode: "US",
    phone: "+1 713 790 3311",
    email: "info@houstonmethodist.org",
    website: "www.houstonmethodist.org",
    latitude: "29.7094",
    longitude: "-95.4022",
    category: "regional",
  },
  {
    name: "UT Southwestern Medical Center",
    address: "5323 Harry Hines Boulevard",
    city: "Dallas, TX",
    postalCode: "75390",
    countryCode: "US",
    phone: "+1 214 648 3111",
    email: "info@utsouthwestern.edu",
    website: "www.utsouthwestern.edu",
    latitude: "32.8125",
    longitude: "-96.8367",
    category: "university",
  },
  {
    name: "Baylor Scott & White Medical Center",
    address: "2401 South 31st Street",
    city: "Temple, TX",
    postalCode: "76508",
    countryCode: "US",
    phone: "+1 254 724 2111",
    email: "info@bswhealth.com",
    website: "www.bswhealth.com",
    latitude: "31.0911",
    longitude: "-97.3422",
    category: "regional",
  },
  {
    name: "University of Washington Medical Center",
    address: "1959 NE Pacific Street",
    city: "Seattle, WA",
    postalCode: "98195",
    countryCode: "US",
    phone: "+1 206 598 3300",
    email: "info@uwmedicine.org",
    website: "www.uwmedicine.org",
    latitude: "47.6500",
    longitude: "-122.3072",
    category: "university",
  },
  {
    name: "Oregon Health & Science University Hospital",
    address: "3181 SW Sam Jackson Park Road",
    city: "Portland, OR",
    postalCode: "97239",
    countryCode: "US",
    phone: "+1 503 494 8311",
    email: "info@ohsu.edu",
    website: "www.ohsu.edu",
    latitude: "45.4989",
    longitude: "-122.6858",
    category: "university",
  },
  {
    name: "University of Colorado Hospital",
    address: "12605 East 16th Avenue",
    city: "Aurora, CO",
    postalCode: "80045",
    countryCode: "US",
    phone: "+1 720 848 0000",
    email: "info@uchealth.org",
    website: "www.uchealth.org",
    latitude: "39.7444",
    longitude: "-104.8389",
    category: "university",
  },
  {
    name: "University of Wisconsin Hospital",
    address: "600 Highland Avenue",
    city: "Madison, WI",
    postalCode: "53792",
    countryCode: "US",
    phone: "+1 608 263 6400",
    email: "info@uwhealth.org",
    website: "www.uwhealth.org",
    latitude: "43.0767",
    longitude: "-89.4294",
    category: "university",
  },
  {
    name: "Barnes-Jewish Hospital",
    address: "1 Barnes-Jewish Hospital Plaza",
    city: "St. Louis, MO",
    postalCode: "63110",
    countryCode: "US",
    phone: "+1 314 747 3000",
    email: "info@bjc.org",
    website: "www.barnesjewish.org",
    latitude: "38.6350",
    longitude: "-90.2633",
    category: "university",
  },
  {
    name: "UNC Medical Center",
    address: "101 Manning Drive",
    city: "Chapel Hill, NC",
    postalCode: "27514",
    countryCode: "US",
    phone: "+1 984 974 1000",
    email: "info@unchealth.unc.edu",
    website: "www.unchealthcare.org",
    latitude: "35.9083",
    longitude: "-79.0556",
    category: "university",
  },
  {
    name: "Wake Forest Baptist Medical Center",
    address: "Medical Center Boulevard",
    city: "Winston-Salem, NC",
    postalCode: "27157",
    countryCode: "US",
    phone: "+1 336 716 2011",
    email: "info@wakehealth.edu",
    website: "www.wakehealth.edu",
    latitude: "36.0856",
    longitude: "-80.2694",
    category: "university",
  },
  {
    name: "University of Florida Health Shands Hospital",
    address: "1600 SW Archer Road",
    city: "Gainesville, FL",
    postalCode: "32610",
    countryCode: "US",
    phone: "+1 352 265 0111",
    email: "info@shands.ufl.edu",
    website: "www.ufhealth.org",
    latitude: "29.6403",
    longitude: "-82.3436",
    category: "university",
  },
  {
    name: "Tampa General Hospital",
    address: "1 Tampa General Circle",
    city: "Tampa, FL",
    postalCode: "33606",
    countryCode: "US",
    phone: "+1 813 844 7000",
    email: "info@tgh.org",
    website: "www.tgh.org",
    latitude: "27.9406",
    longitude: "-82.4583",
    category: "regional",
  },
  {
    name: "Jackson Memorial Hospital",
    address: "1611 NW 12th Avenue",
    city: "Miami, FL",
    postalCode: "33136",
    countryCode: "US",
    phone: "+1 305 585 1111",
    email: "info@jhsmiami.org",
    website: "www.jacksonhealth.org",
    latitude: "25.7900",
    longitude: "-80.2106",
    category: "regional",
  },
  {
    name: "Grady Memorial Hospital",
    address: "80 Jesse Hill Jr. Drive SE",
    city: "Atlanta, GA",
    postalCode: "30303",
    countryCode: "US",
    phone: "+1 404 616 1000",
    email: "info@gradyhealth.org",
    website: "www.gradyhealth.org",
    latitude: "33.7544",
    longitude: "-84.3822",
    category: "regional",
  },
  {
    name: "UAB Hospital",
    address: "619 19th Street South",
    city: "Birmingham, AL",
    postalCode: "35249",
    countryCode: "US",
    phone: "+1 205 934 4011",
    email: "info@uab.edu",
    website: "www.uabmedicine.org",
    latitude: "33.5019",
    longitude: "-86.7994",
    category: "university",
  },
];
