// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/callback-cards/VariantA.tsx": () => import("../components/mockups/callback-cards/VariantA.tsx"),
  "./components/mockups/callback-cards/VariantB.tsx": () => import("../components/mockups/callback-cards/VariantB.tsx"),
  "./components/mockups/callback-cards/VariantC.tsx": () => import("../components/mockups/callback-cards/VariantC.tsx"),
  "./components/mockups/disp-variants/ExpandedCategories.tsx": () => import("../components/mockups/disp-variants/ExpandedCategories.tsx"),
  "./components/mockups/disp-variants/FlatList.tsx": () => import("../components/mockups/disp-variants/FlatList.tsx"),
  "./components/mockups/disposition-checklist/InlineChecklist.tsx": () => import("../components/mockups/disposition-checklist/InlineChecklist.tsx"),
  "./components/mockups/disposition-checklist/TwoStepChecklist.tsx": () => import("../components/mockups/disposition-checklist/TwoStepChecklist.tsx"),
  "./components/mockups/filter-variants/ChipFilter.tsx": () => import("../components/mockups/filter-variants/ChipFilter.tsx"),
  "./components/mockups/filter-variants/SidebarFilter.tsx": () => import("../components/mockups/filter-variants/SidebarFilter.tsx"),
  "./components/mockups/filter-variants/ToolbarFilter.tsx": () => import("../components/mockups/filter-variants/ToolbarFilter.tsx"),
  "./components/mockups/result-panels/CallResult.tsx": () => import("../components/mockups/result-panels/CallResult.tsx"),
  "./components/mockups/result-panels/EmailResult.tsx": () => import("../components/mockups/result-panels/EmailResult.tsx"),
  "./components/mockups/result-panels/SmsResult.tsx": () => import("../components/mockups/result-panels/SmsResult.tsx"),
};
