// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/filter-variants/ChipFilter.tsx": () => import("../components/mockups/filter-variants/ChipFilter.tsx"),
  "./components/mockups/filter-variants/SidebarFilter.tsx": () => import("../components/mockups/filter-variants/SidebarFilter.tsx"),
  "./components/mockups/filter-variants/ToolbarFilter.tsx": () => import("../components/mockups/filter-variants/ToolbarFilter.tsx")
};
