export type PulseLocale = "sk" | "cs" | "hu" | "ro" | "it" | "de" | "en";
export interface PulseCopy {
  title:string; subtitle:string; start:string; retry:string; close:string; returnToIndexus:string; heard:string; play:string; continue:string; working:string; ready:string; warning:string; blocked:string;
  browser:string; secure:string; online:string; microphone:string; input:string; output:string; sound:string; ice:string; sip:string; notifications:string; network:string; wakeLock:string; devices:string;
  browserDetail:string; secureDetail:string; onlineDetail:string; micDetail:string; inputDetail:string; outputDetail:string; soundDetail:string; soundFail:string; iceDetail:string; iceFail:string; sipDetail:string; sipFail:string; notificationsDetail:string; networkDetail:string; ethernetDetail:string; wakeDetail:string; devicesDetail:string;
}
const en: PulseCopy = {
  title:"NEXUS Pulse readiness", subtitle:"A quick check before you start calling. Nothing is recorded or sent to the server.", start:"Start readiness check", retry:"Run check again", close:"Close", returnToIndexus:"Return to INDEXUS", heard:"I heard the test sound", play:"Play test sound", continue:"Continue to workspace", working:"Checking your calling setup…", ready:"Ready for calls", warning:"Ready with notes", blocked:"Action required",
  browser:"Supported browser", secure:"Secure connection", online:"Internet connection", microphone:"Microphone permission", input:"Audio input", output:"Audio output", sound:"Test sound", ice:"Connection path", sip:"SIP registration", notifications:"Notifications", network:"Network type", wakeLock:"Keep screen awake", devices:"Audio devices",
  browserDetail:"Use a current Chromium desktop browser.", secureDetail:"Calls require a secure production connection.", onlineDetail:"The browser is offline.", micDetail:"Allow microphone access, then try again.", inputDetail:"No microphone was found.", outputDetail:"No audio output was found.", soundDetail:"Play the sound and confirm you heard it.", soundFail:"The test sound could not be played. Try again.", iceDetail:"A public ICE path was found.", iceFail:"ICE gathering did not complete. Check your connection.", sipDetail:"SIP transport is registered and ready.", sipFail:"SIP/WSS registration is not ready.", notificationsDetail:"Notifications are unavailable or blocked. This does not prevent calling.", networkDetail:"Wi‑Fi or an unknown connection was reported. VPN and proxy status cannot be detected here.", ethernetDetail:"Ethernet connection reported. VPN and proxy status cannot be detected here.", wakeDetail:"Screen wake lock is unavailable or was denied.", devicesDetail:"Multiple audio devices detected; confirm the selected headset before calling."
};
const sk: PulseCopy = { title:"Pripravenosť NEXUS Pulse", subtitle:"Krátka kontrola pred telefonovaním. Nič sa nenahráva ani neposiela na server.", start:"Spustiť kontrolu pripravenosti", retry:"Spustiť kontrolu znova", close:"Zavrieť", returnToIndexus:"Späť do INDEXUS", heard:"Počul(a) som testovací zvuk", play:"Prehrať testovací zvuk", continue:"Pokračovať do pracoviska", working:"Kontrolujem nastavenie hovorov…", ready:"Pripravené na hovory", warning:"Pripravené s upozorneniami", blocked:"Vyžaduje pozornosť", browser:"Podporovaný prehliadač", secure:"Bezpečné pripojenie", online:"Pripojenie na internet", microphone:"Povolenie mikrofónu", input:"Zvukový vstup", output:"Zvukový výstup", sound:"Testovací zvuk", ice:"Sieťová cesta", sip:"Registrácia SIP", notifications:"Oznámenia", network:"Typ siete", wakeLock:"Udržať obrazovku aktívnu", devices:"Zvukové zariadenia", browserDetail:"Použite aktuálny desktopový prehliadač Chromium.", secureDetail:"Hovory vyžadujú bezpečné produkčné pripojenie.", onlineDetail:"Prehliadač je offline.", micDetail:"Povoľte prístup k mikrofónu a skúste znova.", inputDetail:"Mikrofón sa nenašiel.", outputDetail:"Zvukový výstup sa nenašiel.", soundDetail:"Prehrajte zvuk a potvrďte, že ste ho počuli.", soundFail:"Testovací zvuk sa nepodarilo prehrať. Skúste znova.", iceDetail:"Bola nájdená verejná ICE cesta.", iceFail:"Zhromažďovanie ICE sa nedokončilo. Skontrolujte pripojenie.", sipDetail:"SIP transport je zaregistrovaný a pripravený.", sipFail:"Registrácia SIP/WSS nie je pripravená.", notificationsDetail:"Oznámenia nie sú dostupné alebo sú zablokované. Hovory to neblokuje.", networkDetail:"Bola zistená Wi‑Fi alebo neznáma sieť. VPN ani proxy sa tu nedajú zistiť.", ethernetDetail:"Bolo zistené ethernetové pripojenie. VPN ani proxy sa tu nedajú zistiť.", wakeDetail:"Udržiavanie obrazovky aktívnej nie je dostupné alebo bolo zamietnuté.", devicesDetail:"Zistilo sa viac zvukových zariadení; pred hovorom potvrďte správne slúchadlá." };
const cs: PulseCopy = { ...sk, title:"Připravenost NEXUS Pulse", subtitle:"Krátká kontrola před voláním. Nic se nenahrává ani neposílá na server.", start:"Spustit kontrolu připravenosti", retry:"Spustit kontrolu znovu", close:"Zavřít", returnToIndexus:"Zpět do INDEXUS", heard:"Slyšel(a) jsem testovací zvuk", play:"Přehrát testovací zvuk", continue:"Pokračovat do pracovního prostoru", working:"Kontroluji nastavení hovorů…", ready:"Připraveno k volání", warning:"Připraveno s upozorněními", blocked:"Vyžaduje pozornost", browser:"Podporovaný prohlížeč", secure:"Bezpečné připojení", online:"Připojení k internetu", microphone:"Povolení mikrofonu", input:"Zvukový vstup", output:"Zvukový výstup", sound:"Testovací zvuk", ice:"Síťová cesta", sip:"Registrace SIP", notifications:"Oznámení", network:"Typ sítě", wakeLock:"Udržet obrazovku aktivní", devices:"Zvuková zařízení", browserDetail:"Použijte aktuální desktopový prohlížeč Chromium.", secureDetail:"Hovory vyžadují bezpečné produkční připojení.", onlineDetail:"Prohlížeč je offline.", micDetail:"Povolte přístup k mikrofonu a zkuste to znovu.", inputDetail:"Mikrofon nebyl nalezen.", outputDetail:"Zvukový výstup nebyl nalezen.", soundDetail:"Přehrajte zvuk a potvrďte, že jste jej slyšeli.", soundFail:"Testovací zvuk se nepodařilo přehrát. Zkuste to znovu.", iceDetail:"Byla nalezena veřejná ICE cesta.", iceFail:"Shromažďování ICE nebylo dokončeno. Zkontrolujte připojení.", sipDetail:"SIP transport je zaregistrován a připraven.", sipFail:"Registrace SIP/WSS není připravena.", notificationsDetail:"Oznámení nejsou dostupná nebo jsou zablokována. Volání to neblokuje.", networkDetail:"Byla zjištěna Wi‑Fi nebo neznámá síť. VPN ani proxy zde nelze zjistit.", ethernetDetail:"Bylo zjištěno ethernetové připojení. VPN ani proxy zde nelze zjistit.", wakeDetail:"Udržení obrazovky aktivní není dostupné nebo bylo zamítnuto.", devicesDetail:"Bylo nalezeno více zvukových zařízení; před voláním potvrďte správná sluchátka." };
const hu: PulseCopy = { ...en, title:"NEXUS Pulse készenlét", subtitle:"Rövid ellenőrzés a hívások megkezdése előtt. Semmit nem rögzítünk és nem küldünk a szerverre.", start:"Készenléti ellenőrzés indítása", retry:"Ellenőrzés újraindítása", close:"Bezárás", heard:"Hallottam a teszthangot", play:"Teszthang lejátszása", continue:"Tovább a munkaterületre", working:"A hívási beállítás ellenőrzése…", ready:"Hívásra kész", warning:"Megjegyzésekkel kész", blocked:"Beavatkozás szükséges", browser:"Támogatott böngésző", secure:"Biztonságos kapcsolat", online:"Internetkapcsolat", microphone:"Mikrofonengedély", input:"Hangbemenet", output:"Hangkimenet", sound:"Teszt hang", ice:"Kapcsolati útvonal", sip:"SIP-regisztráció", notifications:"Értesítések", network:"Hálózattípus", wakeLock:"Képernyő ébren tartása", devices:"Audioeszközök", browserDetail:"Használjon friss Chromium asztali böngészőt.", secureDetail:"A hívásokhoz biztonságos éles kapcsolat szükséges.", onlineDetail:"A böngésző offline állapotban van.", micDetail:"Engedélyezze a mikrofonhozzáférést, majd próbálja újra.", inputDetail:"Nem található mikrofon.", outputDetail:"Nem található hangkimenet.", soundDetail:"Játssza le a hangot, és erősítse meg, hogy hallotta.", soundFail:"A teszthang nem játszható le. Próbálja újra.", iceDetail:"Nyilvános ICE-útvonal található.", iceFail:"Az ICE-gyűjtés nem fejeződött be. Ellenőrizze a kapcsolatot.", sipDetail:"A SIP-átvitel regisztrált és kész.", sipFail:"A SIP/WSS-regisztráció nem áll készen.", notificationsDetail:"Az értesítések nem érhetők el vagy tiltva vannak. Ez nem akadályozza a hívást.", networkDetail:"Wi‑Fi vagy ismeretlen kapcsolatot jelentett a böngésző. A VPN és proxy állapota itt nem észlelhető.", ethernetDetail:"Ethernet kapcsolatot jelentett a böngésző. A VPN és proxy állapota itt nem észlelhető.", wakeDetail:"A képernyő ébren tartása nem érhető el vagy elutasították.", devicesDetail:"Több audioeszköz található; hívás előtt erősítse meg a fejhallgatót." };
const ro: PulseCopy = { ...en, title:"Pregătire NEXUS Pulse", subtitle:"O verificare rapidă înainte de apeluri. Nimic nu este înregistrat sau trimis serverului.", start:"Pornește verificarea", retry:"Verifică din nou", close:"Închide", heard:"Am auzit sunetul de test", play:"Redă sunetul de test", continue:"Continuă către spațiul de lucru", working:"Verificăm configurarea apelurilor…", ready:"Pregătit pentru apeluri", warning:"Pregătit cu observații", blocked:"Este necesară o acțiune", browser:"Browser compatibil", secure:"Conexiune sigură", online:"Conexiune la internet", microphone:"Permisiune microfon", input:"Intrare audio", output:"Ieșire audio", sound:"Sunet de test", ice:"Rută de conexiune", sip:"Înregistrare SIP", notifications:"Notificări", network:"Tipul rețelei", wakeLock:"Menține ecranul activ", devices:"Dispozitive audio", browserDetail:"Folosiți un browser Chromium desktop actual.", secureDetail:"Apelurile necesită o conexiune de producție sigură.", onlineDetail:"Browserul este offline.", micDetail:"Permiteți accesul la microfon și încercați din nou.", inputDetail:"Nu a fost găsit niciun microfon.", outputDetail:"Nu a fost gășită nicio ieșire audio.", soundDetail:"Redați sunetul și confirmați că l-ați auzit.", soundFail:"Sunetul de test nu a putut fi redat. Încercați din nou.", iceDetail:"A fost găsită o rută ICE publică.", iceFail:"Colectarea ICE nu s-a finalizat. Verificați conexiunea.", sipDetail:"Transportul SIP este înregistrat și pregătit.", sipFail:"Înregistrarea SIP/WSS nu este pregătită.", notificationsDetail:"Notificările nu sunt disponibile sau sunt blocate. Apelurile nu sunt împiedicate.", networkDetail:"A fost raportată o conexiune Wi‑Fi sau necunoscută. VPN-ul și proxy-ul nu pot fi detectate aici.", ethernetDetail:"A fost raportată o conexiune ethernet. VPN-ul și proxy-ul nu pot fi detectate aici.", wakeDetail:"Menținerea ecranului activ nu este disponibilă sau a fost refuzată.", devicesDetail:"Au fost detectate mai multe dispozitive audio; confirmați căștile înainte de apel." };
const it: PulseCopy = { ...en, title:"Prontezza NEXUS Pulse", subtitle:"Un controllo rapido prima di iniziare le chiamate. Nulla viene registrato o inviato al server.", start:"Avvia controllo", retry:"Controlla di nuovo", close:"Chiudi", heard:"Ho sentito il suono di test", play:"Riproduci suono di test", continue:"Vai all’area di lavoro", working:"Controllo configurazione chiamate…", ready:"Pronto per le chiamate", warning:"Pronto con note", blocked:"Azione richiesta", browser:"Browser supportato", secure:"Connessione sicura", online:"Connessione internet", microphone:"Permesso microfono", input:"Ingresso audio", output:"Uscita audio", sound:"Suono di test", ice:"Percorso di connessione", sip:"Registrazione SIP", notifications:"Notifiche", network:"Tipo di rete", wakeLock:"Mantieni schermo attivo", devices:"Dispositivi audio", browserDetail:"Usa un browser Chromium desktop aggiornato.", secureDetail:"Le chiamate richiedono una connessione di produzione sicura.", onlineDetail:"Il browser è offline.", micDetail:"Consenti l’accesso al microfono e riprova.", inputDetail:"Nessun microfono trovato.", outputDetail:"Nessuna uscita audio trovata.", soundDetail:"Riproduci il suono e conferma di averlo sentito.", soundFail:"Impossibile riprodurre il suono di test. Riprova.", iceDetail:"È stato trovato un percorso ICE pubblico.", iceFail:"La raccolta ICE non è completata. Controlla la connessione.", sipDetail:"Il trasporto SIP è registrato e pronto.", sipFail:"La registrazione SIP/WSS non è pronta.", notificationsDetail:"Le notifiche non sono disponibili o sono bloccate. Le chiamate non sono impedite.", networkDetail:"È stata rilevata una connessione Wi‑Fi o sconosciuta. VPN e proxy non possono essere rilevati qui.", ethernetDetail:"È stata rilevata una connessione ethernet. VPN e proxy non possono essere rilevati qui.", wakeDetail:"Il blocco riattivazione schermo non è disponibile o è stato negato.", devicesDetail:"Rilevati più dispositivi audio; conferma la cuffia prima di chiamare." };
const de: PulseCopy = { ...en, title:"NEXUS Pulse Bereitschaft", subtitle:"Eine kurze Prüfung vor dem Telefonieren. Es wird nichts aufgezeichnet oder an den Server gesendet.", start:"Bereitschaft prüfen", retry:"Erneut prüfen", close:"Schließen", heard:"Ich habe den Testton gehört", play:"Testton abspielen", continue:"Zum Arbeitsbereich", working:"Anrufeinrichtung wird geprüft…", ready:"Bereit für Anrufe", warning:"Bereit mit Hinweisen", blocked:"Aktion erforderlich", browser:"Unterstützter Browser", secure:"Sichere Verbindung", online:"Internetverbindung", microphone:"Mikrofonberechtigung", input:"Audioeingang", output:"Audioausgang", sound:"Testton", ice:"Verbindungsweg", sip:"SIP-Registrierung", notifications:"Benachrichtigungen", network:"Netzwerktyp", wakeLock:"Bildschirm aktiv halten", devices:"Audiogeräte", browserDetail:"Verwenden Sie einen aktuellen Chromium-Desktopbrowser.", secureDetail:"Anrufe benötigen eine sichere Produktionsverbindung.", onlineDetail:"Der Browser ist offline.", micDetail:"Erlauben Sie den Mikrofonzugriff und versuchen Sie es erneut.", inputDetail:"Kein Mikrofon gefunden.", outputDetail:"Kein Audioausgang gefunden.", soundDetail:"Spielen Sie den Ton ab und bestätigen Sie, dass Sie ihn gehört haben.", soundFail:"Der Testton konnte nicht abgespielt werden. Versuchen Sie es erneut.", iceDetail:"Ein öffentlicher ICE-Verbindungsweg wurde gefunden.", iceFail:"Die ICE-Sammlung wurde nicht abgeschlossen. Prüfen Sie die Verbindung.", sipDetail:"Der SIP-Transport ist registriert und bereit.", sipFail:"Die SIP/WSS-Registrierung ist nicht bereit.", notificationsDetail:"Benachrichtigungen sind nicht verfügbar oder blockiert. Anrufe werden dadurch nicht verhindert.", networkDetail:"Es wurde WLAN oder eine unbekannte Verbindung gemeldet. VPN- und Proxy-Status können hier nicht erkannt werden.", ethernetDetail:"Eine Ethernet-Verbindung wurde gemeldet. VPN- und Proxy-Status können hier nicht erkannt werden.", wakeDetail:"Bildschirm-Aktivhaltung ist nicht verfügbar oder wurde abgelehnt.", devicesDetail:"Mehrere Audiogeräte erkannt; bestätigen Sie vor dem Anruf das richtige Headset." };
const subtitles: Record<PulseLocale, string> = {
  en: "A quick connection and device check before you start calling. No audio is recorded or stored.",
  sk: "Krátka kontrola pripojenia a zariadení pred telefonovaním. Žiadny zvuk sa nenahráva ani neukladá.",
  cs: "Krátká kontrola připojení a zařízení před voláním. Žádný zvuk se nenahrává ani neukládá.",
  hu: "Rövid kapcsolat- és eszközellenőrzés a hívások előtt. Hangfelvétel nem készül és nem kerül tárolásra.",
  ro: "O verificare rapidă a conexiunii și dispozitivelor înainte de apeluri. Niciun sunet nu este înregistrat sau stocat.",
  it: "Un rapido controllo della connessione e dei dispositivi prima delle chiamate. Nessun audio viene registrato o archiviato.",
  de: "Eine kurze Verbindungs- und Geräteprüfung vor dem Telefonieren. Audio wird weder aufgezeichnet noch gespeichert.",
};
ro.soundFail = "Sunetul de test nu a putut fi redat. Încercați din nou.";
it.soundFail = "Impossibile riprodurre il suono di test. Riprova.";
de.soundFail = "Der Testton konnte nicht abgespielt werden. Versuchen Sie es erneut.";
const sets: Record<PulseLocale, PulseCopy> = { en, sk, cs, hu, ro, it, de };
export function pulseCopy(locale?: string): PulseCopy {
  const selectedLocale = sets[locale as PulseLocale] ? locale as PulseLocale : "en";
  return { ...sets[selectedLocale], subtitle: subtitles[selectedLocale] };
}