export type NotificationLocale = "en" | "sk" | "cs" | "hu" | "ro" | "it" | "de";

const copy: Record<NotificationLocale, {
  heading: string; description: string; priority: string; title: string; message: string;
  edit: string; editorTitle: string; editorDescription: string; cancel: string; apply: string;
  variables: string; templates: string; chooseTemplate: string; custom: string; allLanguages: string;
  snapshot: string; templateError: string; titleRequired: string; messageRequired: string;
  unsupported: string; unsupportedTemplate: string; preview: string; loading: string;
  notificationType: string; notificationTitle: string; templateVariablesHint: string; previewAction: string;
  plainTextNotice: string; htmlNotAllowed: string; removeHtmlContent: string;
  attachmentsNotAllowed: string; removeAttachment: string;
  priorityLabels: Record<"low" | "normal" | "high" | "urgent", string>;
}> = {
  en: { heading: "Notify a user", description: "Send an in-app notification when this automation runs.", priority: "Priority", title: "Title", message: "Message", edit: "Edit title and message", editorTitle: "Notification content", editorDescription: "Changes stay in this editor until you apply them.", cancel: "Cancel", apply: "Apply changes", variables: "Available variables", templates: "Basic templates", chooseTemplate: "Choose a template", custom: "Custom message", allLanguages: "All languages", snapshot: "Saved template snapshot", templateError: "Templates could not be loaded. Retry", titleRequired: "A title is required.", messageRequired: "A message is required.", unsupported: "Unsupported variables", unsupportedTemplate: "Unavailable for this WHEN: ", preview: "Current notification", loading: "Loading templates…", notificationType: "Notification", notificationTitle: "Notification title", templateVariablesHint: "Notification templates use the automation variable catalog.", previewAction: "Preview", plainTextNotice: "Notification templates are plain text only. A title and message are required; HTML and attachments are not supported.", htmlNotAllowed: "HTML content is still present. It will not be saved as a notification.", removeHtmlContent: "Remove HTML content", attachmentsNotAllowed: "Remove attachments before saving this text-only notification.", removeAttachment: "Remove", priorityLabels: { low: "Low", normal: "Normal", high: "High", urgent: "Urgent" } },
  sk: { heading: "Upozorniť používateľa", description: "Po spustení automatizácie odošle upozornenie v aplikácii.", priority: "Priorita", title: "Názov", message: "Správa", edit: "Upraviť názov a správu", editorTitle: "Obsah upozornenia", editorDescription: "Zmeny zostanú v editore, kým ich nepotvrdíte.", cancel: "Zrušiť", apply: "Použiť zmeny", variables: "Dostupné premenné", templates: "Základné šablóny", chooseTemplate: "Vybrať šablónu", custom: "Vlastná správa", allLanguages: "Všetky jazyky", snapshot: "Uložená kópia šablóny", templateError: "Šablóny sa nepodarilo načítať. Skúsiť znova", titleRequired: "Názov je povinný.", messageRequired: "Správa je povinná.", unsupported: "Nepodporované premenné", unsupportedTemplate: "Nedostupná pre túto podmienku WHEN: ", preview: "Aktuálne upozornenie", loading: "Načítavam šablóny…", notificationType: "Upozornenie", notificationTitle: "Názov upozornenia", templateVariablesHint: "Šablóny upozornení používajú katalóg premenných automatizácie.", previewAction: "Náhľad", plainTextNotice: "Šablóny upozornení podporujú iba obyčajný text. Názov a správa sú povinné; HTML a prílohy nie sú podporované.", htmlNotAllowed: "Obsah HTML je stále prítomný. Nemožno ho uložiť ako upozornenie.", removeHtmlContent: "Odstrániť obsah HTML", attachmentsNotAllowed: "Pred uložením textového upozornenia odstráňte prílohy.", removeAttachment: "Odstrániť", priorityLabels: { low: "Nízka", normal: "Normálna", high: "Vysoká", urgent: "Urgentná" } },
  cs: { heading: "Upozornit uživatele", description: "Po spuštění automatizace odešle upozornění v aplikaci.", priority: "Priorita", title: "Název", message: "Zpráva", edit: "Upravit název a zprávu", editorTitle: "Obsah upozornění", editorDescription: "Změny zůstanou v editoru, dokud je nepotvrdíte.", cancel: "Zrušit", apply: "Použít změny", variables: "Dostupné proměnné", templates: "Základní šablony", chooseTemplate: "Vybrat šablonu", custom: "Vlastní zpráva", allLanguages: "Všechny jazyky", snapshot: "Uložená kopie šablony", templateError: "Šablony se nepodařilo načíst. Zkusit znovu", titleRequired: "Název je povinný.", messageRequired: "Zpráva je povinná.", unsupported: "Nepodporované proměnné", unsupportedTemplate: "Není dostupná pro tuto podmínku WHEN: ", preview: "Aktuální upozornění", loading: "Načítání šablon…", notificationType: "Upozornění", notificationTitle: "Název upozornění", templateVariablesHint: "Šablony upozornění používají katalog proměnných automatizace.", previewAction: "Náhled", plainTextNotice: "Šablony upozornění podporují pouze prostý text. Název a zpráva jsou povinné; HTML a přílohy nejsou podporovány.", htmlNotAllowed: "Obsah HTML je stále přítomen. Nelze jej uložit jako upozornění.", removeHtmlContent: "Odstranit obsah HTML", attachmentsNotAllowed: "Před uložením textového upozornění odstraňte přílohy.", removeAttachment: "Odstranit", priorityLabels: { low: "Nízká", normal: "Normální", high: "Vysoká", urgent: "Urgentní" } },
  hu: { heading: "Felhasználó értesítése", description: "Az automatizáció futásakor alkalmazáson belüli értesítést küld.", priority: "Prioritás", title: "Cím", message: "Üzenet", edit: "Cím és üzenet szerkesztése", editorTitle: "Értesítés tartalma", editorDescription: "A módosítások csak alkalmazás után kerülnek mentésre.", cancel: "Mégse", apply: "Módosítások alkalmazása", variables: "Elérhető változók", templates: "Alapsablonok", chooseTemplate: "Sablon kiválasztása", custom: "Egyéni üzenet", allLanguages: "Minden nyelv", snapshot: "Mentett sablonmásolat", templateError: "A sablonok nem tölthetők be. Újra", titleRequired: "A cím kötelező.", messageRequired: "Az üzenet kötelező.", unsupported: "Nem támogatott változók", unsupportedTemplate: "Ehhez a WHEN feltételhez nem érhető el: ", preview: "Aktuális értesítés", loading: "Sablonok betöltése…", notificationType: "Értesítés", notificationTitle: "Értesítés címe", templateVariablesHint: "Az értesítéssablonok az automatizáció változókatalógusát használják.", previewAction: "Előnézet", plainTextNotice: "Az értesítéssablonok csak egyszerű szöveget támogatnak. A cím és az üzenet kötelező; HTML és mellékletek nem használhatók.", htmlNotAllowed: "A HTML-tartalom még jelen van. Értesítésként nem menthető.", removeHtmlContent: "HTML-tartalom eltávolítása", attachmentsNotAllowed: "A szöveges értesítés mentése előtt távolítsa el a mellékleteket.", removeAttachment: "Eltávolítás", priorityLabels: { low: "Alacsony", normal: "Normál", high: "Magas", urgent: "Sürgős" } },
  ro: { heading: "Notifică un utilizator", description: "Trimite o notificare în aplicație când rulează automatizarea.", priority: "Prioritate", title: "Titlu", message: "Mesaj", edit: "Editează titlul și mesajul", editorTitle: "Conținutul notificării", editorDescription: "Modificările rămân în editor până când le aplici.", cancel: "Anulează", apply: "Aplică modificările", variables: "Variabile disponibile", templates: "Șabloane de bază", chooseTemplate: "Alege un șablon", custom: "Mesaj personalizat", allLanguages: "Toate limbile", snapshot: "Copie salvată a șablonului", templateError: "Șabloanele nu au putut fi încărcate. Reîncearcă", titleRequired: "Titlul este obligatoriu.", messageRequired: "Mesajul este obligatoriu.", unsupported: "Variabile nesuportate", unsupportedTemplate: "Indisponibil pentru această condiție WHEN: ", preview: "Notificarea curentă", loading: "Se încarcă șabloanele…", notificationType: "Notificare", notificationTitle: "Titlul notificării", templateVariablesHint: "Șabloanele folosesc catalogul de variabile al automatizării.", previewAction: "Previzualizare", plainTextNotice: "Șabloanele de notificare acceptă doar text simplu. Titlul și mesajul sunt obligatorii; HTML și atașamentele nu sunt acceptate.", htmlNotAllowed: "Conținutul HTML este încă prezent. Nu poate fi salvat ca notificare.", removeHtmlContent: "Elimină conținutul HTML", attachmentsNotAllowed: "Elimină atașamentele înainte de a salva notificarea text.", removeAttachment: "Elimină", priorityLabels: { low: "Scăzută", normal: "Normală", high: "Ridicată", urgent: "Urgentă" } },
  it: { heading: "Notifica un utente", description: "Invia una notifica nell’app quando viene eseguita l’automazione.", priority: "Priorità", title: "Titolo", message: "Messaggio", edit: "Modifica titolo e messaggio", editorTitle: "Contenuto della notifica", editorDescription: "Le modifiche restano nell’editor finché non le applichi.", cancel: "Annulla", apply: "Applica modifiche", variables: "Variabili disponibili", templates: "Modelli di base", chooseTemplate: "Scegli un modello", custom: "Messaggio personalizzato", allLanguages: "Tutte le lingue", snapshot: "Copia salvata del modello", templateError: "Impossibile caricare i modelli. Riprova", titleRequired: "Il titolo è obbligatorio.", messageRequired: "Il messaggio è obbligatorio.", unsupported: "Variabili non supportate", unsupportedTemplate: "Non disponibile per questa condizione WHEN: ", preview: "Notifica attuale", loading: "Caricamento modelli…", notificationType: "Notifica", notificationTitle: "Titolo della notifica", templateVariablesHint: "I modelli usano il catalogo delle variabili dell’automazione.", previewAction: "Anteprima", plainTextNotice: "I modelli di notifica accettano solo testo semplice. Titolo e messaggio sono obbligatori; HTML e allegati non sono supportati.", htmlNotAllowed: "È ancora presente contenuto HTML. Non può essere salvato come notifica.", removeHtmlContent: "Rimuovi contenuto HTML", attachmentsNotAllowed: "Rimuovi gli allegati prima di salvare la notifica testuale.", removeAttachment: "Rimuovi", priorityLabels: { low: "Bassa", normal: "Normale", high: "Alta", urgent: "Urgente" } },
  de: { heading: "Benutzer benachrichtigen", description: "Sendet eine In-App-Benachrichtigung, wenn diese Automatisierung ausgeführt wird.", priority: "Priorität", title: "Titel", message: "Nachricht", edit: "Titel und Nachricht bearbeiten", editorTitle: "Benachrichtigungsinhalt", editorDescription: "Änderungen bleiben im Editor, bis du sie übernimmst.", cancel: "Abbrechen", apply: "Änderungen übernehmen", variables: "Verfügbare Variablen", templates: "Einfache Vorlagen", chooseTemplate: "Vorlage auswählen", custom: "Eigene Nachricht", allLanguages: "Alle Sprachen", snapshot: "Gespeicherte Vorlagenkopie", templateError: "Vorlagen konnten nicht geladen werden. Erneut versuchen", titleRequired: "Ein Titel ist erforderlich.", messageRequired: "Eine Nachricht ist erforderlich.", unsupported: "Nicht unterstützte Variablen", unsupportedTemplate: "Für diesen WHEN-Auslöser nicht verfügbar: ", preview: "Aktuelle Benachrichtigung", loading: "Vorlagen werden geladen…", notificationType: "Benachrichtigung", notificationTitle: "Benachrichtigungstitel", templateVariablesHint: "Benachrichtigungsvorlagen verwenden den Variablenkatalog der Automatisierung.", previewAction: "Vorschau", plainTextNotice: "Benachrichtigungsvorlagen unterstützen nur einfachen Text. Titel und Nachricht sind erforderlich; HTML und Anhänge werden nicht unterstützt.", htmlNotAllowed: "HTML-Inhalt ist noch vorhanden und kann nicht als Benachrichtigung gespeichert werden.", removeHtmlContent: "HTML-Inhalt entfernen", attachmentsNotAllowed: "Entferne Anhänge, bevor du die Textbenachrichtigung speicherst.", removeAttachment: "Entfernen", priorityLabels: { low: "Niedrig", normal: "Normal", high: "Hoch", urgent: "Dringend" } },
};

export function getNotificationCopy(locale?: string) {
  const key = (locale || "en").split(/[-_]/)[0] as NotificationLocale;
  return copy[key] || copy.en;
}
