import "./_group.css";
import { useMemo, useState } from "react";
import { Calendar, Search, SlidersHorizontal, Phone, Mic, Coffee, BookOpen, Megaphone, ChevronDown, Star, Brain, Play, Download, AlertTriangle, Smartphone, CheckCircle2, Clock3 } from "lucide-react";
import { calls, CallRecord, Chip, Direction } from "./_shared";

const nav = [["Missions", Megaphone], ["Inbound", Phone], ["Calls & Transcripts", Mic], ["Breaks", Coffee], ["SOP & Procedures", BookOpen]] as const;

function RecordRow({ call, selected, onClick }: { call: CallRecord; selected: boolean; onClick: () => void }) {
  return <button onClick={onClick} className={`w-full text-left px-3 py-2.5 border-l-[3px] border-b border-border/60 transition-colors ${selected ? "bg-primary/10 border-l-primary" : "border-l-transparent hover:bg-muted/50"}`}>
    <div className="flex items-center justify-between mb-1"><div className="flex items-center gap-1.5"><Direction call={call}/><b className="text-xs">{call.time}</b><span className="text-[10px] text-muted-foreground">{call.duration}</span></div><span className={`h-1.5 w-1.5 rounded-full ${call.sentiment === "positive" ? "bg-emerald-500" : call.sentiment === "negative" ? "bg-amber-500" : "bg-sky-500"}`}/></div>
    <div className="text-xs font-semibold truncate">{call.name}</div><div className="text-[10px] text-muted-foreground truncate">{call.phone}</div>
    <div className="text-[10px] text-muted-foreground italic truncate mt-0.5">{call.summary}</div>
    <div className="flex gap-1.5 mt-1.5">{call.status && <Chip>{call.status}</Chip>}{call.direction === "inbound" && <Chip tone="green">Inbound</Chip>}{call.important && <Chip tone="orange"><Star className="h-2.5 w-2.5 fill-amber-400 mr-0.5"/> Dôležité</Chip>}<Chip><Mic className="h-2.5 w-2.5"/></Chip></div>
  </button>;
}

function Detail({ call }: { call: CallRecord }) {
  const [important, setImportant] = useState(!!call.important);
  return <div className="flex min-h-0 flex-1 flex-col bg-background overflow-y-auto">
    <div className="px-5 pt-4 pb-3 border-b space-y-3">
      <div className="flex items-start gap-3"><div className="flex-1"><div className="flex items-center gap-2 flex-wrap"><b className="text-sm">{call.name}</b><span className="text-[10px] text-muted-foreground">{call.phone}</span><Chip tone={call.direction === "inbound" ? "green" : "blue"}>{call.direction === "inbound" ? "Inbound" : "Outbound"}</Chip></div><div className="text-[10px] text-muted-foreground mt-1">12. 06. 2025, {call.time} · {call.duration}</div></div><div className={`rounded-xl px-3 py-1.5 text-center ${call.sentiment === "positive" ? "bg-emerald-50 text-emerald-700" : call.sentiment === "negative" ? "bg-amber-50 text-amber-700" : "bg-sky-50 text-sky-700"}`}><div className="text-xs font-bold capitalize">{call.sentiment}</div><div className="text-[9px] text-muted-foreground">Sentiment</div></div><button onClick={() => setImportant(!important)} className="p-2 rounded-xl hover:bg-muted"><Star className={`h-4 w-4 ${important ? "fill-amber-400 text-amber-500" : "text-muted-foreground"}`}/></button></div>
      <div className="flex flex-wrap gap-1.5"><Chip tone="red"><Megaphone className="h-3 w-3 mr-1"/> {call.campaign}</Chip><Chip><span className="mr-1">●</span>{call.agent}</Chip>{call.queue && <Chip tone="orange"><Phone className="h-3 w-3 mr-1"/>{call.queue}</Chip>}<Chip tone="blue"><Smartphone className="h-3 w-3 mr-1"/> INDEXUS Connect</Chip></div>
    </div>
    <div className="p-5 space-y-4 max-w-4xl">
      <div className="flex border-b"><button className="px-3 py-2 text-xs font-semibold border-b-2 border-primary text-primary">Analýza hovoru</button><button className="px-3 py-2 text-xs text-muted-foreground">Prepis hovoru</button></div>
      <div className="grid grid-cols-3 gap-2"><div className="rounded-lg border bg-card p-3"><div className="text-[10px] text-muted-foreground">Kvalita hovoru</div><div className="text-xl font-bold text-amber-600">8.4 <span className="text-xs font-normal">/ 10</span></div></div><div className="rounded-lg border bg-card p-3"><div className="text-[10px] text-muted-foreground">Dĺžka</div><div className="text-xl font-bold">{call.duration}</div></div><div className="rounded-lg border bg-card p-3"><div className="text-[10px] text-muted-foreground">Hodnotenie</div><div className="text-xl font-bold text-emerald-600">92%</div></div></div>
      <section className="rounded-xl border overflow-hidden"><div className="px-3.5 py-2.5 border-b flex items-center gap-2"><Brain className="h-4 w-4 text-primary"/><span className="text-xs font-semibold">Zhrnutie hovoru</span></div><p className="p-3.5 text-xs leading-relaxed text-muted-foreground">{call.summary} Agent profesionálne reagoval na otázky a dohodol ďalší postup.</p></section>
      <section className="rounded-xl border overflow-hidden"><div className="px-3.5 py-2.5 border-b flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-600"/><span className="text-xs font-semibold">Kľúčové témy a akcie</span></div><div className="p-3.5 grid grid-cols-2 gap-2 text-xs"><div><b>Diskutované témy</b><p className="text-muted-foreground mt-1">Produktová ponuka, ceny, ďalšie kroky</p></div><div><b>Ďalšia akcia</b><p className="text-muted-foreground mt-1">Naplánovať spätný hovor do 7 dní</p></div></div></section>
      <section className="rounded-xl border overflow-hidden"><div className="px-3.5 py-2.5 border-b flex items-center gap-2"><Mic className="h-4 w-4 text-primary"/><span className="text-xs font-semibold">Nahrávka hovoru</span><button className="ml-auto flex items-center gap-1 text-[10px] text-muted-foreground border rounded px-2 py-1"><Download className="h-3 w-3"/> Export</button></div><div className="p-4 flex items-center gap-3"><button className="h-9 w-9 rounded-full bg-primary text-primary-foreground flex items-center justify-center"><Play className="h-4 w-4 fill-current ml-0.5"/></button><div className="h-1 flex-1 bg-muted rounded-full"><div className="w-1/3 h-full bg-primary rounded-full"/></div><span className="text-[10px] text-muted-foreground">{call.duration}</span></div></section>
    </div>
  </div>;
}

export function Current() {
  const [activeNav, setActiveNav] = useState("Calls & Transcripts");
  const [activeTab, setActiveTab] = useState("browse");
  const [selected, setSelected] = useState(calls[0].id);
  const [search, setSearch] = useState("");
  const [showFilters, setShowFilters] = useState(false);
  const visible = useMemo(() => calls.filter(c => `${c.name} ${c.phone} ${c.summary}`.toLowerCase().includes(search.toLowerCase())), [search]);
  const selectedCall = calls.find(c => c.id === selected) || calls[0];
  return <main className="min-h-screen bg-muted/20 text-foreground font-sans flex flex-col">
    <header className="bg-background border-b px-6 pt-5"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-bold tracking-tight">Missions</h1><p className="text-sm text-muted-foreground mt-1">Správa misií a komunikácie s klientmi</p></div></div><nav className="flex gap-1 mt-5 overflow-x-auto">{nav.map(([label, Icon]) => <button key={label} onClick={() => setActiveNav(label)} className={`flex items-center gap-2 whitespace-nowrap px-4 py-2.5 text-sm font-medium border-b-2 ${activeNav === label ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav></header>
    <div className="bg-background border-b px-4 py-2.5 flex items-center gap-3"><div className="flex items-center gap-2.5"><div className="w-7 h-7 rounded-lg bg-primary flex items-center justify-center"><Phone className="h-3.5 w-3.5 text-primary-foreground"/></div><b className="text-sm">Calls & Transcripts</b></div><div className="flex border rounded-lg overflow-hidden ml-1"><button onClick={() => setActiveTab("browse")} className={`px-3 py-1.5 text-xs font-medium ${activeTab === "browse" ? "bg-primary text-primary-foreground" : "text-muted-foreground"}`}>All calls</button><button onClick={() => setActiveTab("search")} className={`px-3 py-1.5 text-xs font-medium ${activeTab === "search" ? "bg-primary text-primary-foreground" : "text-muted-foreground"}`}>Search transcripts</button></div><div className="ml-auto flex items-center gap-3 text-xs"><b>128</b><span className="text-muted-foreground">calls</span><span className="flex items-center gap-1 text-destructive"><AlertTriangle className="h-3 w-3"/> 7</span><span className="flex items-center gap-1 text-amber-500"><Star className="h-3 w-3"/> 8.2</span></div></div>
    {activeTab === "browse" && <><div className="bg-background/95 border-b px-4 py-3"><div className="flex items-center gap-2.5 flex-wrap"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center"><Calendar className="h-4 w-4"/></div><div className="hidden xl:block leading-tight"><div className="text-[10px] uppercase tracking-wide font-semibold text-muted-foreground">Date from</div><div className="text-xs font-medium">Custom range</div></div></div><button className="h-9 w-[150px] rounded-md border bg-muted/30 px-3 text-xs text-left flex items-center justify-between">This month <ChevronDown className="h-3.5 w-3.5"/></button><button className="h-9 min-w-[310px] rounded-md border px-3 text-xs flex items-center gap-2"><Calendar className="h-3.5 w-3.5 text-primary"/> 01 Jun 2025, 00:00 <span className="text-muted-foreground">→</span> 30 Jun 2025, 23:59</button><div className="h-7 w-px bg-border hidden lg:block"/><button className="h-9 w-[190px] rounded-md border px-3 text-xs text-left flex justify-between">All campaigns <ChevronDown className="h-3.5 w-3.5"/></button><button className="h-9 w-[190px] rounded-md border px-3 text-xs text-left flex justify-between">All queues <ChevronDown className="h-3.5 w-3.5"/></button><button onClick={() => setShowFilters(!showFilters)} className={`ml-auto h-9 px-3 rounded-md border flex items-center gap-2 text-xs ${showFilters ? "bg-secondary" : ""}`}><SlidersHorizontal className="h-3.5 w-3.5"/> Filters</button></div></div>
    <div className="flex flex-1 min-h-0"><aside className="w-[280px] shrink-0 bg-background border-r flex flex-col"><div className="p-3 border-b"><div className="flex gap-1.5"><div className="flex flex-1 items-center gap-2 bg-muted/60 rounded-lg px-2.5 py-1.5"><Search className="h-3 w-3 text-muted-foreground"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search calls…" className="bg-transparent outline-none flex-1 text-xs"/></div><button onClick={() => setShowFilters(!showFilters)} className="px-2.5 rounded-lg border text-muted-foreground"><SlidersHorizontal className="h-3.5 w-3.5"/></button></div>{showFilters && <div className="grid grid-cols-2 gap-1 mt-2">{["Direction","Status","Sentiment","Recording"].map(x => <button key={x} className="h-7 border rounded text-[10px] text-muted-foreground text-left px-2">{x}<ChevronDown className="inline h-3 w-3 float-right"/></button>)}</div>}</div><div className="flex-1 overflow-y-auto">{visible.map(c => <RecordRow key={c.id} call={c} selected={selected === c.id} onClick={() => setSelected(c.id)}/>)}</div></aside><Detail call={selectedCall}/></div></>}
    {activeTab === "search" && <div className="p-8 bg-background flex-1"><div className="max-w-xl"><h2 className="text-lg font-semibold">Search transcripts</h2><div className="flex gap-2 mt-4"><input className="border rounded-md h-9 px-3 text-sm flex-1" placeholder="Search words in transcripts…" autoFocus/><button className="h-9 px-4 rounded-md bg-primary text-primary-foreground text-sm flex items-center gap-1"><Search className="h-4 w-4"/> Search</button></div></div></div>}
  </main>;
}