import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { BellRing, Maximize2, MonitorUp, Pause, Play, Radio, RotateCcw, Volume2, X } from "lucide-react";
import "./_wallboard.css";
import "./_display.css";

type _Scope = "mission" | "all";
type _State = "calling" | "working" | "available" | "break" | "ringing";
type _Agent = { id:string; name:string; campaign:string; state:_State; changed:number; detail:string };
const _seed:_Agent[]=[{id:"A-014",name:"Petra Vargová",campaign:"Obnova zmlúv / SK",state:"calling",changed:89,detail:""},{id:"A-022",name:"Marek Kováč",campaign:"Obnova zmlúv / SK",state:"working",changed:214,detail:""},{id:"A-031",name:"Lucia Bartošová",campaign:"Aktivácia klientov",state:"available",changed:8,detail:""},{id:"A-047",name:"Ivan Doležal",campaign:"Obnova zmlúv / SK",state:"ringing",changed:5,detail:""},{id:"A-053",name:"Nina Šimková",campaign:"Aktivácia klientov",state:"ringing",changed:5,detail:""},{id:"A-068",name:"Tomáš Bielik",campaign:"Obnova zmlúv / SK",state:"calling",changed:472,detail:""}];
const _meta:Record<_State,{label:string;color:string}>={calling:{label:"VOLÁ",color:"#6fd3db"},working:{label:"SPRACÚVA",color:"#a793ec"},available:{label:"VOĽNÝ",color:"#b9df74"},break:{label:"PRESTÁVKA",color:"#f2be61"},ringing:{label:"ZVONÍ",color:"#dc3348"}};
const _format=(s:number)=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;

export function _Wallboard({defaultScope}:{defaultScope:_Scope}) {
 const [scope,setScope]=useState<_Scope>(defaultScope),[agents,setAgents]=useState(() => _seed.map(a => a.id === "A-053" ? {...a, state: "break" as _State, changed: 124} : a)),[now,setNow]=useState(0),[paused,setPaused]=useState(false),[incoming,setIncoming]=useState(true),[fault,setFault]=useState(false),[presentation,setPresentation]=useState(false);
 useEffect(()=>{if(paused)return;const x=window.setInterval(()=>{setNow(n=>n+1);setAgents(a=>a.map(p=>({...p,changed:p.changed+1})))},1000);return()=>window.clearInterval(x)},[paused]);
 useEffect(()=>{if(!paused&&now>0&&now%18===0)setAgents(a=>a.map((p,i)=>i===((now/18|0)%a.length)?{...p,state:p.state==="available"?"calling":p.state==="calling"?"working":"available",changed:0}:p))},[now,paused]);
 useEffect(()=>{const leave=(e:KeyboardEvent)=>{if(e.key==="Escape")setPresentation(false)};window.addEventListener("keydown",leave);return()=>window.removeEventListener("keydown",leave)},[]);
 const view=useMemo(()=>scope==="mission"?agents.filter(a=>a.campaign==="Obnova zmlúv / SK"):agents,[agents,scope]);
 const counts=useMemo(()=>({active:view.filter(a=>a.state==="calling"||a.state==="ringing").length,ready:view.filter(a=>a.state==="available").length,work:view.filter(a=>a.state==="working").length,breaks:view.filter(a=>a.state==="break").length}),[view]);
 const trigger=()=>{const target=view.find(a=>a.state==="available")??view[0];if(!target)return;setIncoming(true);setAgents(a=>a.map(x=>x.id===target.id?{...x,state:"ringing",changed:0}:x))};
 const ringing=view.find(a=>a.state==="ringing"), queue=scope==="mission"?["02","00:32","86","00:16"]:["05","00:48","214","00:21"];
 return <main className={`wb-shell ${presentation?"wb-present":""}`}><div className="wb-board">
  <header className="wb-top"><div><div className="wb-brandline"><i className="wb-mark"/> INDEXUS · operačný wallboard <span className="wb-live"><i/> simulované dáta</span></div><h1 className="wb-title">{scope==="mission"?"Obnova zmlúv / SK":"Bežiace kampane"}</h1><p className="wb-sub">{scope==="mission"?`Mission 08 · ${view.length} prihlásení agenti`:"Všetci agenti naprieč 2 aktívnymi Mission"}</p><nav className="wb-launch" aria-label="Koncept spustenia wallboardu"><span>Mission 08 <MonitorUp size={12}/></span><button className={`wb-scope ${scope==="mission"?"active":""}`} onClick={()=>setScope("mission")}>Wallboard</button><span>Hlavné menu: Prestávky → <MonitorUp size={12}/> Wallboard</span><button className={`wb-scope ${scope==="all"?"active":""}`} onClick={()=>setScope("all")}>Všetky Mission</button></nav></div>
  <div className="wb-tools">{presentation?<button className="wb-tool" onClick={()=>setPresentation(false)}><X size={14}/> ukončiť · Esc</button>:<><button className="wb-tool" onClick={()=>setPaused(p=>!p)} aria-pressed={paused}>{paused?<Play size={14}/>:<Pause size={14}/>} {paused?"spustiť":"pozastaviť"}</button><button className="wb-tool" onClick={trigger}><BellRing size={14}/> simulovať hovor</button><button className="wb-tool" onClick={()=>setFault(f=>!f)}><RotateCcw size={14}/> {fault?"obnoviť":"test stavu"}</button><button className="wb-tool" onClick={()=>setPresentation(true)}><Maximize2 size={14}/> prezentácia</button></>}</div></header>
  <div className="wb-main"><section className="wb-stage"><div className="wb-summary"><_Metric label="Aktívne hovory" value={counts.active} total={view.length}/><_Metric label="Voľní agenti" value={counts.ready} total={view.length}/><_Metric label="Spracúvajú" value={counts.work} total={view.length}/><_Metric label="Na prestávke" value={counts.breaks} total={view.length}/></div>
  {fault?<div className="wb-error">Pripojenie k demonštračnému toku je prerušené.<br/><button onClick={()=>setFault(false)}>Skúsiť znova</button></div>:view.length?<div className={`wb-agents ${scope==="mission"?"mission":""}`}>{view.map(a=><_AgentCard key={a.id} agent={a}/>)}</div>:<div className="wb-empty"><div><b>V tejto Mission zatiaľ nikto nie je prihlásený.</b>Wallboard obnoví stav hneď po prihlásení agenta.</div></div>}</section>
  <aside className="wb-rail"><section className="wb-inbound" aria-live="polite"><div className="wb-overline"><Radio size={11}/> prichádzajúci hovor · simulácia</div>{incoming&&ringing?<><h2>Linka 204 zvoní</h2><p>Priradené: {ringing.name}</p><strong>+421 9•• ••• 771</strong><p>Volajúci: M. Nováková · údaje maskované</p></>:<><h2>Žiadny nový hovor</h2><p>Prichádzajúci hovor sa zobrazí v tomto vyhradenom paneli.</p></>}<button className="wb-alert-button" onClick={incoming&&ringing?()=>setIncoming(false):trigger}>{incoming&&ringing?"skryť ukážku":"vyvolať hovor"}</button></section><section className="wb-queue"><h3>Fiktívna fronta · ukážka</h3>{["Čaká vo fronte","Najdlhšie čakanie","Prijaté dnes","Priemerné čakanie"].map((label,i)=><div className="wb-qrow" key={label}><span>{label}</span><b>{queue[i]}</b></div>)}</section><footer className="wb-footer"><span><MonitorUp size={12}/> DEMO · bez napojenia</span><span><Volume2 size={12}/> {paused?"simulácia pozastavená":`čas relácie ${_format(now)}`}</span></footer></aside></div>
 </div></main>
}
function _Metric({label,value,total}:{label:string;value:number;total:number}){return <div className="wb-metric"><span>{label}</span><b>{String(value).padStart(2,"0")} <em>/ {String(total).padStart(2,"0")}</em></b></div>}
function _AgentCard({agent}:{agent:_Agent}){const m=_meta[agent.state],detail={calling:"Odchádzajúci hovor · +421 9•• ••• 418",working:"Kontakt karta · záznam po hovore",available:"Pripravený prijať ďalší hovor",break:"Prestávka · návrat o 10:42",ringing:"Prichádzajúci hovor · linka 204"}[agent.state];return <article className="wb-agent" style={{"--state":m.color} as CSSProperties}><div className="wb-agent-head"><div><div className="wb-agent-id">{agent.id}</div><div className="wb-agent-name">{agent.name}</div><div className="wb-campaign">{agent.campaign}</div></div></div><div><div className="wb-status">{m.label}</div><div className="wb-timer">{_format(agent.changed)}</div><div className="wb-detail">{detail}</div></div></article>}